-- ============================================================================
--  pgTAP · 06 news events (#R334) — the Event tables are readable by everyone who
--  has to read them, writable by nobody who must not, and the constraints whose
--  reasons the migration writes down actually hold.
--
--  WHY THIS FILE EXISTS
--    `current_news` shipped without a pgTAP file of its own. Nothing ever asserted
--    that `(lang, link)` is what identifies a row, so the single property the refresh
--    job depends on was never proved — it was only true. The Event tables carry more
--    of that kind of property: a fingerprint that IS the identity, a PARTIAL unique
--    index that allows a second row only when the relation is `related_context`, and
--    two CHECKs that keep a merged Event from pointing nowhere or at itself. Each one
--    is exercised here by attempting the thing it forbids and watching it fail with
--    the SQLSTATE it should fail with — a constraint nobody has ever tried to violate
--    is indistinguishable from a constraint that is not there.
--
--  ⚠ THE FIXTURES ARE THIS FILE'S OWN. Every row it inserts is keyed `pgtap-…` (ids in
--    the 900000 range) and every count is filtered to those keys, so the Source
--    Registry seed can add or remove rows without moving a single number in here. The
--    whole file runs in one transaction and rolls back.
--
--  ⚠ ROLE SWITCHING IS TOP-LEVEL, exactly as in 01_rls_matrix_test.sql: the two
--    SECURITY INVOKER helpers below run each statement AS the impersonated role and
--    stash the outcome in `_cap`, and the assertions are made afterwards as the
--    superuser. A blocked READ is 'DENIED' only when the grant is missing; when RLS
--    filters the rows it is simply 0 / 'ROWS:0'. Both shapes are asserted for.
-- ============================================================================
begin;
select plan(123);

-- The test session must be able to impersonate the platform roles (superuser can;
-- otherwise it needs membership). Grant it defensively (no-op if already a member).
do $$ begin execute format('grant anon, authenticated, service_role to %I', current_user); exception when others then null; end $$;

create table _cap (k text primary key, v text);
grant insert, select on _cap to anon, authenticated, service_role;

create function _sel(k text, q text) returns void language plpgsql as $$
declare c text;
begin
  execute q into c;
  insert into _cap values (k, coalesce(c, '<null>'));
exception
  when insufficient_privilege then insert into _cap values (k, 'DENIED');
  when others then insert into _cap values (k, 'ERR:' || sqlstate);
end;
$$;
create function _dml(k text, q text) returns void language plpgsql as $$
declare n integer;
begin
  execute q; get diagnostics n = row_count;
  insert into _cap values (k, 'ROWS:' || n);
exception
  when insufficient_privilege then insert into _cap values (k, 'DENIED');
  when others then insert into _cap values (k, 'ERR:' || sqlstate);
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
--  FIXTURES — one source, one feed, three articles (one of them withdrawn), two
--  events, the two links between them, one translation, one clustering decision,
--  and one saved Event for each of the two synthetic users.
--  Ids are explicit so nothing here depends on a sequence position, and
--  `generated BY DEFAULT as identity` permits them.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.news_sources (id, name, slug, source_type, source_family, languages, country)
values ('pgtap-wire', 'pgTAP Wire', 'pgtap-wire', 'wire', 'pgtap', array['en'], 'US');

insert into public.news_source_feeds (id, source_id, url, collection, category)
values (900001, 'pgtap-wire', 'https://pgtap.test/world.xml', 'direct_rss', 'world');

insert into public.news_articles
  (id, source_id, feed_id, canonical_url, url_fingerprint, title, title_fingerprint, language, published_at, status)
values
  (900101, 'pgtap-wire', 900001, 'https://pgtap.test/a1', 'pgtap-fp-a1',
   'pgTAP article one',   'pgtap-tfp-a1', 'en', now(), 'active'),
  (900102, 'pgtap-wire', 900001, 'https://pgtap.test/a2', 'pgtap-fp-a2',
   'pgTAP article two',   'pgtap-tfp-a2', 'en', now(), 'active'),
  (900103, 'pgtap-wire', 900001, 'https://pgtap.test/a3', 'pgtap-fp-a3',
   'pgTAP article three', 'pgtap-tfp-a3', 'en', now(), 'removed');

insert into public.news_events (id, public_id, representative_title, primary_category, first_published_at)
values (900201, 'pgtap-evt-1', 'pgTAP event one', 'world',     now()),
       (900202, 'pgtap-evt-2', 'pgTAP event two', 'disasters', now());

insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
values (900201, 900101, 'same_event', 'deterministic'),
       (900201, 900102, 'update',     'deterministic');

insert into public.news_event_i18n (event_id, lang, title, translator)
values (900201, 'ja', 'pgTAP の出来事 1', 'pgtap');

insert into public.news_cluster_decisions (id, article_id, chosen_event_id, relation, embedding_similarity)
values (900301, 900101, 900201, 'same_event', 0.91);

insert into public.saved_news_events (id, user_id, event_id, event_title)
values (900401, '11111111-1111-1111-1111-111111111111', 900201, 'pgTAP event one'),
       (900402, '22222222-2222-2222-2222-222222222222', 900202, 'pgTAP event two');

-- ─────────────────────────────────────────────────────────────────────────────
--  1. STRUCTURE — the eight tables exist and every one of them has RLS on.
--     (00_structure_test.sql asserts the same two facts for the whole schema; the
--     duplication is deliberate — this file has to be readable on its own, and every
--     policy assertion below is meaningless if RLS is off.)                16 tests
-- ─────────────────────────────────────────────────────────────────────────────
select has_table('public', t, 'table ' || t || ' exists')
from unnest(array[
  'news_sources','news_source_feeds','news_articles','news_events',
  'news_event_articles','news_cluster_decisions','news_event_i18n','saved_news_events'
]) as t;                                                    -- 8 assertions

select ok(
  (select relrowsecurity from pg_class where oid = ('public.' || t)::regclass),
  'RLS enabled on ' || t
)
from unnest(array[
  'news_sources','news_source_feeds','news_articles','news_events',
  'news_event_articles','news_cluster_decisions','news_event_i18n','saved_news_events'
]) as t;                                                    -- 8 assertions

-- ─────────────────────────────────────────────────────────────────────────────
--  2. GRANTS — the map must be drawable logged out, and nothing on it is writable
--     from a browser. ⚠ A policy alone does not grant read (#R155 closed exactly
--     that hole), so the privilege is asserted as well as the behaviour.  50 tests
-- ─────────────────────────────────────────────────────────────────────────────
select ok(has_table_privilege('anon', 'public.' || t, 'select'), 'anon CAN read ' || t)
from unnest(array['news_sources','news_source_feeds','news_articles','news_events',
                  'news_event_articles','news_event_i18n']) as t;          -- 6 assertions

-- The audit trail carries raw model responses and cost; the saved list is personal.
select ok(not has_table_privilege('anon', 'public.' || t, 'select'), 'anon cannot read ' || t)
from unnest(array['news_cluster_decisions','saved_news_events']) as t;     -- 2 assertions

-- Ingest is service_role's job. No browser role holds a write privilege on any of the
-- seven server-owned tables — the check is grant-level, so it stays meaningful even
-- where Supabase's default privileges would otherwise hand out a blanket grant.
select ok(not has_table_privilege(r, 'public.' || t, p),
          r || ' cannot ' || upper(p) || ' ' || t)
from unnest(array['anon','authenticated']) as r,
     unnest(array['news_sources','news_source_feeds','news_articles','news_events',
                  'news_event_articles','news_event_i18n','news_cluster_decisions']) as t,
     unnest(array['insert','update','delete']) as p;                       -- 42 assertions

-- ─────────────────────────────────────────────────────────────────────────────
--  3. BEHAVIOUR — what each subject actually gets back.
--     ⚠ The statements are dollar-quoted rather than single-quoted: every one of them
--     carries literals of its own, and doubling those quotes is where a file like this
--     acquires the typo that reads as a passing test.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── ANON (logged out) — the public map has to render without an account ─────
select set_config('request.jwt.claims', '{"role":"anon"}', true);
set local role anon;
select _sel('anon_sources',  $q$ select count(*) from public.news_sources where id = 'pgtap-wire' $q$);
select _sel('anon_feeds',    $q$ select count(*) from public.news_source_feeds where id = 900001 $q$);
select _sel('anon_articles', $q$ select count(*) from public.news_articles where source_id = 'pgtap-wire' $q$);
-- the withdrawn article is filtered by the POLICY, not merely left out of the UI
select _sel('anon_removed',  $q$ select count(*) from public.news_articles where url_fingerprint = 'pgtap-fp-a3' $q$);
select _sel('anon_events',   $q$ select count(*) from public.news_events where public_id like 'pgtap-evt-%' $q$);
select _sel('anon_links',    $q$ select count(*) from public.news_event_articles where event_id = 900201 $q$);
select _sel('anon_i18n',     $q$ select count(*) from public.news_event_i18n where event_id = 900201 $q$);
select _sel('anon_decisions',$q$ select count(*) from public.news_cluster_decisions $q$);
select _sel('anon_saved',    $q$ select count(*) from public.saved_news_events $q$);
select _dml('anon_ins_event',$q$ insert into public.news_events (public_id, representative_title) values ('pgtap-anon','forged') $q$);
select _dml('anon_upd_src',  $q$ update public.news_sources set name = 'HACK' where id = 'pgtap-wire' $q$);
select _dml('anon_del_art',  $q$ delete from public.news_articles where id = 900101 $q$);
reset role;

-- ── USER A (authenticated, not an admin) ────────────────────────────────────
select set_config('request.jwt.claims', '{"sub":"11111111-1111-1111-1111-111111111111","role":"authenticated"}', true);
set local role authenticated;
select _sel('a_sources',      $q$ select count(*) from public.news_sources where id = 'pgtap-wire' $q$);
select _sel('a_events',       $q$ select count(*) from public.news_events where public_id like 'pgtap-evt-%' $q$);
-- the grant exists (so this is not DENIED) but the policy is admin-only → 0 rows
select _sel('a_decisions',    $q$ select count(*) from public.news_cluster_decisions $q$);
select _sel('a_own_saved',    $q$ select count(*) from public.saved_news_events where user_id = '11111111-1111-1111-1111-111111111111' $q$);
select _sel('a_see_b_saved',  $q$ select count(*) from public.saved_news_events where user_id = '22222222-2222-2222-2222-222222222222' $q$);
select _sel('a_all_saved',    $q$ select count(*) from public.saved_news_events $q$);
select _dml('a_ins_own_saved',$q$ insert into public.saved_news_events (user_id, event_id) values ('11111111-1111-1111-1111-111111111111', 900202) $q$);
select _dml('a_ins_as_b',     $q$ insert into public.saved_news_events (user_id, event_id) values ('22222222-2222-2222-2222-222222222222', 900201) $q$);
select _dml('a_upd_b_saved',  $q$ update public.saved_news_events set event_title = 'HACK' where user_id = '22222222-2222-2222-2222-222222222222' $q$);
select _dml('a_del_b_saved',  $q$ delete from public.saved_news_events where user_id = '22222222-2222-2222-2222-222222222222' $q$);
select _dml('a_del_own_saved',$q$ delete from public.saved_news_events where user_id = '11111111-1111-1111-1111-111111111111' and event_id = 900202 $q$);
select _dml('a_ins_event',    $q$ insert into public.news_events (public_id, representative_title) values ('pgtap-usera','forged') $q$);
select _dml('a_upd_event',    $q$ update public.news_events set representative_title = 'HACK' where id = 900201 $q$);
select _dml('a_del_article',  $q$ delete from public.news_articles where id = 900101 $q$);
select _dml('a_ins_decision', $q$ insert into public.news_cluster_decisions (article_id, chosen_event_id) values (900101, 900201) $q$);
reset role;

-- ── ADMIN — the only human who may read why a cluster decision was made ─────
select set_config('request.jwt.claims', '{"sub":"33333333-3333-3333-3333-333333333333","role":"authenticated"}', true);
set local role authenticated;
select _sel('admin_decisions', $q$ select count(*) from public.news_cluster_decisions where id = 900301 $q$);
reset role;

-- ── SERVICE ROLE — the ingest path has to be able to write all of it ────────
--    ⚠ IF THESE FOUR GO RED, LOOK AT THE GRANT, NOT AT THIS FILE. Every earlier
--    migration ends with `grant all on all tables in schema public to service_role`,
--    which is a snapshot and therefore does not reach a table created afterwards; the
--    Event migration grants service_role the SEQUENCES only and leaves the table access
--    to the platform's default privileges. Where those defaults are absent, ingest
--    cannot write and this is where it shows.
select set_config('request.jwt.claims', '{"role":"service_role"}', true);
set local role service_role;
select _dml('svc_ins_source',  $q$ insert into public.news_sources (id, name, slug, source_type, source_family) values ('pgtap-svc','pgTAP Svc','pgtap-svc','digital','pgtap-svc') $q$);
select _dml('svc_ins_article', $q$ insert into public.news_articles (source_id, canonical_url, url_fingerprint, title, title_fingerprint) values ('pgtap-svc','https://pgtap.test/svc','pgtap-fp-svc','svc article','pgtap-tfp-svc') $q$);
select _dml('svc_ins_event',   $q$ insert into public.news_events (public_id, representative_title) values ('pgtap-evt-svc','svc event') $q$);
select _dml('svc_ins_decision',$q$ insert into public.news_cluster_decisions (article_id, chosen_event_id) values (900101, 900202) $q$);
reset role;

-- ── the assertions, made as the superuser ───────────────────────────── 32 tests
select is((select v from _cap where k='anon_sources'),   '1',      'anon CAN read the Source Registry');
select is((select v from _cap where k='anon_feeds'),     '1',      'anon CAN read the feed list (freshness is shown on the page)');
select is((select v from _cap where k='anon_articles'),  '2',      'anon reads the two ACTIVE articles, not the withdrawn one');
select is((select v from _cap where k='anon_removed'),   '0',      'a status=removed article is invisible to anon (the policy filters it)');
select is((select v from _cap where k='anon_events'),    '2',      'anon CAN read events (the map renders logged out)');
select is((select v from _cap where k='anon_links'),     '2',      'anon CAN read the event/article links');
select is((select v from _cap where k='anon_i18n'),      '1',      'anon CAN read the translated event (no login, no AI quota)');
select is((select v from _cap where k='anon_decisions'), 'DENIED', 'anon cannot read news_cluster_decisions (raw model output + cost)');
select is((select v from _cap where k='anon_saved'),     'DENIED', 'anon cannot read saved_news_events');
select is((select v from _cap where k='anon_ins_event'), 'DENIED', 'anon cannot create an event');
select is((select v from _cap where k='anon_upd_src'),   'DENIED', 'anon cannot rewrite a source');
select is((select v from _cap where k='anon_del_art'),   'DENIED', 'anon cannot delete an article');

select is((select v from _cap where k='a_sources'),      '1',      'A can read the Source Registry');
select is((select v from _cap where k='a_events'),       '2',      'A can read events');
select is((select v from _cap where k='a_decisions'),    '0',      'A (non-admin) holds the grant but sees no cluster decisions');
select is((select v from _cap where k='a_own_saved'),    '1',      'A can read its OWN saved events');
select is((select v from _cap where k='a_see_b_saved'),  '0',      'A cannot read B''s saved events');
select is((select v from _cap where k='a_all_saved'),    '1',      'an unfiltered read returns only A''s own row');
select is((select v from _cap where k='a_ins_own_saved'),'ROWS:1', 'A can save an event for itself');
select is((select v from _cap where k='a_ins_as_b'),     'DENIED', 'A cannot save an event AS B (WITH CHECK)');
select is((select v from _cap where k='a_upd_b_saved'),  'ROWS:0', 'A cannot rename B''s saved event');
select is((select v from _cap where k='a_del_b_saved'),  'ROWS:0', 'A cannot delete B''s saved event');
select is((select v from _cap where k='a_del_own_saved'),'ROWS:1', 'A can remove its own saved event');
select is((select v from _cap where k='a_ins_event'),    'DENIED', 'A cannot create an event');
select is((select v from _cap where k='a_upd_event'),    'DENIED', 'A cannot edit an event');
select is((select v from _cap where k='a_del_article'),  'DENIED', 'A cannot delete an article');
select is((select v from _cap where k='a_ins_decision'), 'DENIED', 'A cannot forge a cluster decision');

select is((select v from _cap where k='admin_decisions'),  '1',      'admin CAN read the cluster-decision audit trail');

select is((select v from _cap where k='svc_ins_source'),   'ROWS:1', 'service_role can write news_sources');
select is((select v from _cap where k='svc_ins_article'),  'ROWS:1', 'service_role can write news_articles');
select is((select v from _cap where k='svc_ins_event'),    'ROWS:1', 'service_role can write news_events');
select is((select v from _cap where k='svc_ins_decision'), 'ROWS:1', 'service_role can write news_cluster_decisions');

-- ─────────────────────────────────────────────────────────────────────────────
--  4. THE CONSTRAINTS THE MIGRATION ARGUES FOR — each one is attacked.  20 tests
-- ─────────────────────────────────────────────────────────────────────────────

-- ── identity is the fingerprint, not the URL (the Google News redirect and the
--    publisher's own link are two strings for one article) ───────────────────
select col_is_unique('public', 'news_articles', 'url_fingerprint',
  'news_articles.url_fingerprint is UNIQUE (the fingerprint IS the identity)');
select throws_ok(
  $$ insert into public.news_articles (source_id, canonical_url, url_fingerprint, title, title_fingerprint)
     values ('pgtap-wire','https://pgtap.test/dup','pgtap-fp-a1','dup','pgtap-tfp-dup') $$,
  '23505', null, 'a second article with the same url_fingerprint is rejected');

-- ── one article has at most ONE primary event, and any number of related ones ─
select ok(
  exists(select 1 from pg_indexes
          where schemaname = 'public' and indexname = 'news_event_articles_one_primary'),
  'the partial index news_event_articles_one_primary exists');
select ok(
  (select indexdef from pg_indexes
    where schemaname = 'public' and indexname = 'news_event_articles_one_primary') ilike '%unique%where%',
  'it is a PARTIAL UNIQUE index — a plain unique on article_id would also forbid related_context');
select throws_ok(
  $$ insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
     values (900202, 900101, 'same_event', 'llm') $$,
  '23505', null, 'the same article cannot be same_event on a SECOND event');
select throws_ok(
  $$ insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
     values (900202, 900102, 'update', 'llm') $$,
  '23505', null, 'nor `update` on a second event (both relations share the one slot)');
select lives_ok(
  $$ insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
     values (900202, 900101, 'related_context', 'human') $$,
  'but the SAME article may hang off another event as related_context');

-- ── a merged event names its successor, and never itself ────────────────────
select ok(
  exists(select 1 from pg_constraint
          where conname = 'news_events_merged_points_somewhere'
            and conrelid = 'public.news_events'::regclass),
  'news_events_merged_points_somewhere CHECK exists');
select throws_ok(
  $$ insert into public.news_events (public_id, representative_title, status)
     values ('pgtap-evt-m1','merged nowhere','merged') $$,
  '23514', null, 'status=merged with no merged_into is rejected (an alias that resolves nowhere)');
select lives_ok(
  $$ insert into public.news_events (public_id, representative_title, status, merged_into)
     values ('pgtap-evt-m2','merged somewhere','merged', 900202) $$,
  'status=merged WITH merged_into is accepted (old ids stay resolvable)');
select ok(
  exists(select 1 from pg_constraint
          where conname = 'news_events_no_self_merge'
            and conrelid = 'public.news_events'::regclass),
  'news_events_no_self_merge CHECK exists');
select throws_ok(
  $$ insert into public.news_events (id, public_id, representative_title, merged_into)
     values (900213, 'pgtap-evt-m3', 'self merge', 900213) $$,
  '23514', null, 'an event cannot be merged into itself (a one-row resolution loop)');

-- ── the enumerated columns reject a value that is not in the vocabulary ─────
select throws_ok(
  $$ insert into public.news_articles (source_id, canonical_url, url_fingerprint, title, title_fingerprint, status)
     values ('pgtap-wire','https://pgtap.test/bad','pgtap-fp-bad','bad','pgtap-tfp-bad','deleted') $$,
  '23514', null, 'news_articles.status rejects a value outside active/removed');
select lives_ok(
  $$ insert into public.news_articles (source_id, canonical_url, url_fingerprint, title, title_fingerprint, status)
     values ('pgtap-wire','https://pgtap.test/ok','pgtap-fp-ok','ok','pgtap-tfp-ok','removed') $$,
  'news_articles.status accepts removed');
select throws_ok(
  $$ insert into public.news_events (public_id, representative_title, status)
     values ('pgtap-evt-bad','bad status','dead') $$,
  '23514', null, 'news_events.status rejects a value outside active/merged/archived');
select lives_ok(
  $$ insert into public.news_events (public_id, representative_title, status)
     values ('pgtap-evt-arch','archived event','archived') $$,
  'news_events.status accepts archived');
select throws_ok(
  $$ insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
     values (900202, 900103, 'maybe', 'human') $$,
  '23514', null, 'news_event_articles.relation rejects a relation nobody defined');
select lives_ok(
  $$ insert into public.news_event_articles (event_id, article_id, relation, assigned_by)
     values (900202, 900102, 'related_context', 'human') $$,
  'news_event_articles.relation accepts related_context');
select throws_ok(
  $$ insert into public.news_source_feeds (id, source_id, url, collection, category)
     values (900002, 'pgtap-wire', 'https://pgtap.test/bad.xml', 'direct_rss', 'sports') $$,
  '23514', null, 'news_source_feeds.category rejects a category the UI cannot render');
select lives_ok(
  $$ insert into public.news_source_feeds (id, source_id, url, collection, category)
     values (900003, 'pgtap-wire', 'https://pgtap.test/disasters.xml', 'direct_rss', 'disasters') $$,
  'news_source_feeds.category accepts disasters');

-- ─────────────────────────────────────────────────────────────────────────────
--  5. ACCOUNT DELETION REACHES THE NEW TABLE. `delete_account_data` DISCOVERS the
--     owned tables from the foreign keys to auth.users (#R280), so saved_news_events
--     is covered the moment its FK exists — but "covered by construction" is the
--     claim that was wrong the last three times, so it is executed here.   5 tests
-- ─────────────────────────────────────────────────────────────────────────────
select is(
  (select confdeltype from pg_constraint
    where conrelid = 'public.saved_news_events'::regclass
      and confrelid = 'auth.users'::regclass and contype = 'f'),
  'c'::"char", 'saved_news_events.user_id -> auth.users is ON DELETE CASCADE');
select is(
  (select confdeltype from pg_constraint
    where conrelid = 'public.saved_news_events'::regclass
      and confrelid = 'public.news_events'::regclass and contype = 'f'),
  'c'::"char", 'saved_news_events.event_id -> news_events is ON DELETE CASCADE');
select ok(
  (select (public.delete_account_data('11111111-1111-1111-1111-111111111111'::uuid) ->> 'ok')::boolean),
  'the account purge reports success with a saved Event in the way');
select is(
  (select count(*)::int from public.saved_news_events where user_id = '11111111-1111-1111-1111-111111111111'),
  0, 'A''s saved events are gone with the account');
select is(
  (select count(*)::int from public.saved_news_events where user_id = '22222222-2222-2222-2222-222222222222'),
  1, 'and B''s are untouched (the purge is scoped to one account)');

reset role;
select * from finish();
rollback;
