/* ============================================================================
 *  IntMap · Atlas capabilities — ONE CAPABILITY, ONE PLACE   (js/atlas-caps.js)
 * ----------------------------------------------------------------------------
 *  A capability used to be written in five places that had to agree: its row in the registry table
 *  (js/atlas-capabilities.js), its `case` in the 2,190-line dispatch switch of js/atlas-console.js,
 *  its argument schema (js/atlas-schemas.js), its catalogue prose (js/atlas-catalog-text.js), and —
 *  through the row — the observer that judges it. check:capabilities held 23 rules over the seams.
 *
 *  Now each capability is ONE ENTRY in js/atlas-cap-<namespace>.js, where <namespace> is the first
 *  segment of its id (`view.flyTo` lives in js/atlas-cap-view.js):
 *
 *      { row:    [...],                       — the registry row; columns at «THE TABLE» in js/atlas-capabilities.js
 *        schema: () => ({ ... }),             — its argument schema, built with the builders below
 *        run(a, dctx, K) { ... } }            — what the dispatch runs for it
 *
 *  and everything else is DERIVED from the entries, by the functions in this file:
 *    · the dispatch        — capabilityRunners(): row column 1 (the dispatch spelling) → run. The
 *                            console's dispatch asks the registry which column-1 spelling `a.type`
 *                            belongs to (CAPS.dispatchName) and runs that entry; a spelling no row
 *                            owns reaches unknownAction() below, exactly as the switch's `default` did.
 *    · the schema table    — capabilitySchemas(), read by js/atlas-schemas.js.
 *    · the registry table  — capabilityRows(), copied into js/atlas-capabilities.js between its
 *                            GENERATED ROWS markers by `node scripts/atlas-caps.mjs --write`. ⚠ COPIED
 *                            BECAUSE THE REGISTRY IS EAGER: a capability must be discoverable before
 *                            Atlas loads (#R318), and the entries carry the whole kernel's executors —
 *                            importing them at boot would put them on the boot path, and a module of
 *                            rows of its own would be one more boot module. `check:capabilities` fails
 *                            while the copy and the entries disagree.
 *    · the list of namespace files — js/atlas-caps-modules.js, generated by the same command from the
 *                            directory: every js/atlas-cap-<namespace>.js. A new namespace is a new file.
 *    · the observer        — row column 4, as before.
 *    · the catalogue prose stays in js/atlas-catalog-text.js; each block names the ids it documents.
 *
 *  THE DEPENDENCY OBJECT `K`. A run is not a closure over the Atlas kernel any more, so what it needs
 *  from js/atlas-console.js (R, L, HOST, the map helpers, the highlight state …) arrives as K, built
 *  once there. A kernel `let` is read and written as `K.name` (a getter/setter pair), so a run always
 *  sees and sets the live value; everything else is destructured at the top of the run, which is also
 *  the run's own list of what it depends on. K is not published anywhere (check:surface).
 * ==========================================================================*/

/** the namespace a capability id belongs to — the file its entry must live in */
function namespaceOf(id) { return String(id || '').split('.')[0]; }

/** every entry of every module, validated; `modules` is { <namespace>: entries[] } (js/atlas-caps-modules.js) */
export function capabilityEntries(modules) {
  const out = [], seenId = new Set(), seenSpelling = new Set(), problems = [];
  Object.keys(modules || {}).forEach(function (ns) {
    const list = modules[ns];
    if (!Array.isArray(list)) { problems.push('js/atlas-cap-' + ns + '.js: the default export is not an array of entries'); return; }
    list.forEach(function (e, i) {
      const where = 'js/atlas-cap-' + ns + '.js entry ' + i;
      if (!e || !Array.isArray(e.row) || e.row.length < 11 || e.row.length > 12) { problems.push(where + ': `row` is not an 11- or 12-column registry row'); return; }
      const id = e.row[0], spelling = e.row[1];
      if (typeof id !== 'string' || !id) { problems.push(where + ': the row has no id'); return; }
      if (namespaceOf(id) !== ns) problems.push(where + ': ' + id + ' belongs in js/atlas-cap-' + namespaceOf(id) + '.js');
      if (seenId.has(id)) problems.push(where + ': ' + id + ' is declared twice');
      if (spelling && seenSpelling.has(spelling)) problems.push(where + ': the dispatch spelling «' + spelling + '» is declared twice');
      if (typeof e.run !== 'function') problems.push(where + ': ' + id + ' has no run(a, dctx, K)');
      if (typeof e.schema !== 'function') problems.push(where + ': ' + id + ' has no schema()');
      seenId.add(id); if (spelling) seenSpelling.add(spelling);
      out.push({ ns: ns, id: id, row: e.row, schema: e.schema, run: e.run });
    });
  });
  if (problems.length) { const err = new Error('js/atlas-caps: ' + problems.join('; ')); err.problems = problems; throw err; }
  return out;
}

/** dispatch spelling (row column 1) → run. A null-prototype map, so `toString` is not a capability. */
export function capabilityRunners(modules) {
  const run = Object.create(null);
  capabilityEntries(modules).forEach(function (e) { if (e.row[1]) run[e.row[1]] = e.run; });
  return run;
}

/** capability id → its argument schema, FRESH objects on every call */
export function capabilitySchemas(modules) {
  const S = {};
  capabilityEntries(modules).forEach(function (e) { S[e.id] = e.schema(); });
  return S;
}

/** the registry rows, in a stable order: the ids `previousIds` already had keep their places (the
    order is read by alias clashes, search ties and the catalogue), and new ids follow in module order */
export function capabilityRows(modules, previousIds) {
  const entries = capabilityEntries(modules);
  const byId = new Map(entries.map(function (e) { return [e.id, e]; }));
  const prev = (previousIds || []).filter(function (id) { return byId.has(id); });
  const had = new Set(prev);
  return prev.concat(entries.map(function (e) { return e.id; }).filter(function (id) { return !had.has(id); }))
    .map(function (id) { return byId.get(id).row; });
}

/* What the dispatch answers a spelling no row owns — the switch's `default`, moved whole: a control
   the action names by `target`/`name` is pressed if the page has one, otherwise 「不明な操作」. */
export async function unknownAction(a, dctx, K) { const doControl = K.doControl, R = K.R, warn = K.warn, L = K.L, esc = K.esc;
      { if(a.target||a.name){ const c=doControl({target:a.target||a.name,value:a.value,on:a.on}); if(c.ok) return c; } return R(false, warn('⚠ '+L('Unknown action','不明な操作','Unbekannte Aktion','Неизвестное действие','Acción desconocida')+': '+esc(a.type||''))); }
}

/* ══ THE ARGUMENT-SCHEMA BUILDERS ═══════════════════════════════════════════════════════════════
   Every entry's `schema` is written with these, so a schema reads as one line instead of a page of
   punctuation. The dialect and the three rules a schema follows are documented once, in
   js/atlas-schemas.js (which assembles the table from the entries). Each builder returns a FRESH
   object — a shared literal would let one consumer's annotation reach every capability that happens
   to take a latitude — and for the same reason an entry's `schema` is a function called once per
   makeAtlasSchemas(), never a literal evaluated at import. */
export function str() { return { type: 'string' }; }
export function bool() { return { type: 'boolean' }; }
export function num(min, max) { var o = { type: 'number' }; if (min != null) o.minimum = min; if (max != null) o.maximum = max; return o; }
export function int(min, max) { var o = { type: 'integer' }; if (min != null) o.minimum = min; if (max != null) o.maximum = max; return o; }
export function one() { return { type: 'string', enum: [].slice.call(arguments) }; }
export function list(item, min, max) { var o = { type: 'array' }; if (item) o.items = item; if (min != null) o.minItems = min; if (max != null) o.maxItems = max; return o; }
export function obj() { return { type: 'object' }; }
export function lat() { return { type: 'number', minimum: -90, maximum: 90 }; }
export function lng() { return { type: 'number', minimum: -180, maximum: 180 }; }
/* A field the case accepts in TWO shapes — an array OR a comma-separated string (`places`,
   `countries`, `avoid`), a number OR "5M" (`minPop`). The dialect has no union, and naming one
   of the two would reject the other, which is a shape the dispatch was written to accept. */
export function loose() { return {}; }
/* A capability whose case reads NOTHING — `clickId('btn-share')` and no more. `properties` is
   still not empty, and inventing an argument these cases do not read would be the very thing
   js/atlas-schemas.js exists to end. What they DO carry is `type`, the dispatch's own key (an
   action without one returns immediately).
   ⚠ AND IT IS PINNED TO THE ONE SPELLING THE EXECUTOR ITSELF SETS. js/atlas-toolsurface.js
   builds the action as `Object.assign({type: cap.legacy}, args)` — the arguments win — so a
   `type` the caller may choose freely is a way to send one capability's arguments into another
   capability's case. With the enum, an accepted `type` can only be the value that was going to
   be there anyway, and anything else is refused before the dispatch is reached. */
export function noArgs(legacy) { return { type: 'object', properties: { type: { type: 'string', enum: [legacy] } } }; }
