/* ============================================================================
 *  IntMap · Atlas capabilities — ONE CAPABILITY, ONE PLACE   (js/atlas-caps.js)
 * ----------------------------------------------------------------------------
 *  A capability used to be written in five places that had to agree: its row in the registry table
 *  (js/atlas-capabilities.js), its `case` in the 2,190-line dispatch switch of js/atlas-console.js,
 *  its argument schema (js/atlas-schemas.js), its catalogue prose (js/atlas-catalog-text.js), and —
 *  through the row — the observer that judges it. check:capabilities held 23 rules over the seams.
 *
 *  Now each capability is ONE ENTRY in js/atlas-cap-<namespace>.js, where <namespace> is the first
 *  segment of its id (`view.flyTo` lives in js/atlas-cap-view.js):
 *
 *      { row:    [...],                       — the registry row; columns at «THE TABLE» in js/atlas-capabilities.js
 *        doc:    [{ in, at?, text? }, …],     — what the planner reads about it: its fragment of each catalogue
 *                                               chunk it belongs to (the chunks and their order: js/atlas-catalog-text.js)
 *        phrases: () => [...],                — OPTIONAL: the reader's own words for the act, where the product holds them
 *        policy: { … },                       — OPTIONAL: how the planner may and may not use it (POLICY_KEYS below)
 *        goal(a, raw, h) { ... },             — OPTIONAL: the camera's postcondition — what the view must show after it
 *        chips: 'map.route' | [...],          — OPTIONAL: the map's on/off chip(s) a completed run switches (js/atlas-console.js)
 *        catalogueSilent: 'YYYY-MM-DD',       — OPTIONAL: check ㉓'s ledger — the day its `doc` was measured not to name its own subject
 *        schema: () => ({ ... }),             — its argument schema, built with the builders below
 *        run(a, dctx, K) { ... } }            — what the dispatch runs for it
 *
 *  and everything else is DERIVED from the entries, by the functions in this file:
 *    · the dispatch        — capabilityRunners(): row column 1 (the dispatch spelling) → run. The
 *                            console's dispatch asks the registry which column-1 spelling `a.type`
 *                            belongs to (CAPS.dispatchName) and runs that entry; a spelling no row
 *                            owns reaches unknownAction() below, exactly as the switch's `default` did.
 *    · the schema table    — capabilitySchemas(), read by js/atlas-schemas.js.
 *    · the registry table  — capabilityRows(), copied into js/atlas-capabilities.js between its
 *                            GENERATED ROWS markers by `node scripts/atlas-caps.mjs --write`. ⚠ COPIED
 *                            BECAUSE THE REGISTRY IS EAGER: a capability must be discoverable before
 *                            Atlas loads (#R318), and the entries carry the whole kernel's executors —
 *                            importing them at boot would put them on the boot path, and a module of
 *                            rows of its own would be one more boot module. `check:capabilities` fails
 *                            while the copy and the entries disagree.
 *    · the list of namespace files — js/atlas-caps-modules.js, generated by the same command from the
 *                            directory: every js/atlas-cap-<namespace>.js. A new namespace is a new file.
 *    · the observer        — row column 4 names the observer KIND (shared, js/atlas-capabilities.js
 *                            OBSERVERS); the capability's own postcondition, where it has one, is `goal`.
 *    · the catalogue       — catalogueBlocks(): each chunk of js/atlas-catalog-text.js is its heading
 *                            followed by the `doc` fragments that name it, in `at` order. Read through
 *                            js/atlas-catalog-text.js by SYS(), find_capability and the search.
 *    · the planner policy  — capabilityPolicy(): withdrawn / rule-documented / fallback / forbidden
 *                            substitutes / equivalents, and the camera goals — COPIED into the eager registry
 *                            (js/atlas-capabilities.js, between their GENERATED markers) by the same command,
 *                            for the same reason as the rows.
 *    · the audit's ledgers — read from the entries (scripts/atlas-capability-audit.mjs), never listed there.
 *  (atlas-capability-single-source) Adding a capability is ONE entry. Nothing else names it by hand:
 *  tests/atlas-capability-single-source-checks.test.mjs fails on a capability id written as a key or a
 *  list item in the files whose tables are now derived.
 *
 *  THE DEPENDENCY OBJECT `K`. A run is not a closure over the Atlas kernel any more, so what it needs
 *  from js/atlas-console.js (R, L, HOST, the map helpers, the highlight state …) arrives as K, built
 *  once there. A kernel `let` is read and written as `K.name` (a getter/setter pair), so a run always
 *  sees and sets the live value; everything else is destructured at the top of the run, which is also
 *  the run's own list of what it depends on. K is not published anywhere (check:surface).
 * ==========================================================================*/

/** what an entry may hold — a field outside this list is a typo nothing would ever read */
const ENTRY_KEYS = ['row', 'doc', 'phrases', 'policy', 'goal', 'chips', 'catalogueSilent', 'schema', 'run'];
/* What `policy` may say, and what each becomes in the eager registry (js/atlas-capabilities.js):
     withdrawn       { why, proofCode } — DELIBERATELY not offered to the planner; the audit holds the run to
                     answering `proofCode`, and it is the only way for a capability to be absent from the catalogue
     ruleDocumented  the literal the ALWAYS-SENT rules text carries for it, instead of a catalogue fragment
     fallback        true — reachable, but not a user-facing feature; kept out of the search's front rank
     forbidden       [ids] — non-equivalent substitutions the planner has actually made and must not make again
     equivalents     [ids] — genuinely interchangeable capabilities, the only substitutions repair may make
     answer          true — its result is an ANSWER about a topic (#R159): js/atlas-turn-results.js keys it by topic */
const POLICY_KEYS = ['withdrawn', 'ruleDocumented', 'fallback', 'forbidden', 'equivalents', 'answer'];

/** the namespace a capability id belongs to — the file its entry must live in */
function namespaceOf(id) { return String(id || '').split('.')[0]; }

/** every entry of every module, validated; `modules` is { <namespace>: entries[] } (js/atlas-caps-modules.js) */
export function capabilityEntries(modules) {
  const out = [], seenId = new Set(), seenSpelling = new Set(), problems = [];
  Object.keys(modules || {}).forEach(function (ns) {
    const list = modules[ns];
    if (!Array.isArray(list)) { problems.push('js/atlas-cap-' + ns + '.js: the default export is not an array of entries'); return; }
    list.forEach(function (e, i) {
      const where = 'js/atlas-cap-' + ns + '.js entry ' + i;
      if (!e || !Array.isArray(e.row) || e.row.length < 11 || e.row.length > 12) { problems.push(where + ': `row` is not an 11- or 12-column registry row'); return; }
      const id = e.row[0], spelling = e.row[1];
      if (typeof id !== 'string' || !id) { problems.push(where + ': the row has no id'); return; }
      if (namespaceOf(id) !== ns) problems.push(where + ': ' + id + ' belongs in js/atlas-cap-' + namespaceOf(id) + '.js');
      if (seenId.has(id)) problems.push(where + ': ' + id + ' is declared twice');
      if (spelling && seenSpelling.has(spelling)) problems.push(where + ': the dispatch spelling «' + spelling + '» is declared twice');
      if (typeof e.run !== 'function') problems.push(where + ': ' + id + ' has no run(a, dctx, K)');
      if (typeof e.schema !== 'function') problems.push(where + ': ' + id + ' has no schema()');
      Object.keys(e).forEach(function (k) { if (ENTRY_KEYS.indexOf(k) < 0) problems.push(where + ': ' + id + ' has an unknown field «' + k + '» (an entry holds ' + ENTRY_KEYS.join(', ') + ')'); });
      if (e.doc != null) {
        if (!Array.isArray(e.doc)) problems.push(where + ': ' + id + ' `doc` is not an array of fragments');
        else e.doc.forEach(function (d, j) {
          if (!d || typeof d.in !== 'string' || !d.in) problems.push(where + ': ' + id + ' doc[' + j + '] names no chunk (`in`)');
          else if (d.text != null && typeof d.text !== 'string' && typeof d.text !== 'function') problems.push(where + ': ' + id + ' doc[' + j + '] text is neither a string nor a function of the catalogue context');
          else if (d.at != null && !Number.isFinite(d.at)) problems.push(where + ': ' + id + ' doc[' + j + '] position `at` is not a number');
        });
      }
      if (e.catalogueSilent != null && !/^\d{4}-\d{2}-\d{2}$/.test(String(e.catalogueSilent))) problems.push(where + ': ' + id + ' `catalogueSilent` is not the YYYY-MM-DD day the silence was measured');
      if (e.phrases != null && typeof e.phrases !== 'function') problems.push(where + ': ' + id + ' `phrases` is not a function');
      if (e.goal != null && typeof e.goal !== 'function') problems.push(where + ': ' + id + ' `goal` is not a function');
      if (e.chips != null && !(typeof e.chips === 'string' || (Array.isArray(e.chips) && e.chips.every(function (k) { return typeof k === 'string'; })))) problems.push(where + ': ' + id + ' `chips` is neither a kind nor a list of kinds');
      if (e.policy != null) Object.keys(e.policy).forEach(function (k) { if (POLICY_KEYS.indexOf(k) < 0) problems.push(where + ': ' + id + ' policy has an unknown field «' + k + '» (' + POLICY_KEYS.join(', ') + ')'); });
      seenId.add(id); if (spelling) seenSpelling.add(spelling);
      out.push({ ns: ns, id: id, row: e.row, schema: e.schema, run: e.run, doc: Array.isArray(e.doc) ? e.doc : [], phrases: e.phrases || null,
        policy: e.policy || null, goal: e.goal || null, chips: e.chips || null, catalogueSilent: e.catalogueSilent || null });
    });
  });
  if (problems.length) { const err = new Error('js/atlas-caps: ' + problems.join('; ')); err.problems = problems; throw err; }
  return out;
}

/** the catalogue blocks the planner reads, ASSEMBLED from the entries (atlas-capability-single-source).
    `chunks` is the ordered list of js/atlas-catalog-text.js ({ name, head? }); `c` is what a function-valued
    text or head reads ({ lang, moduleCatalog, metricList, showcaseList, tourList }). A block is its head followed by
    the fragments that name it in `at` order; its `ids` are those fragments' capabilities, then the ones that
    name it without text (documented by the head). Throws on a fragment naming an undeclared chunk, two
    fragments at one position, or a chunk nothing documents — each is a catalogue that would be silently wrong. */
export function catalogueBlocks(modules, chunks, c) {
  const entries = capabilityEntries(modules), problems = [], slot = new Map();
  (chunks || []).forEach(function (k) {
    if (!k || !k.name) { problems.push('a catalogue chunk has no name'); return; }
    if (slot.has(k.name)) problems.push('the catalogue chunk «' + k.name + '» is declared twice');
    slot.set(k.name, { k: k, frags: [], mentions: [] });
  });
  entries.forEach(function (e) {
    e.doc.forEach(function (d, j) {
      const s = slot.get(d.in);
      if (!s) { problems.push(e.id + ' doc[' + j + '] names the chunk «' + d.in + '», which js/atlas-catalog-text.js does not declare'); return; }
      if (d.text == null) { if (s.mentions.indexOf(e.id) < 0) s.mentions.push(e.id); return; }
      const at = d.at == null ? 0 : d.at, clash = s.frags.find(function (f) { return f.at === at; });
      if (clash) problems.push(e.id + ' and ' + clash.id + ' both put their fragment of «' + d.in + '» at position ' + at);
      s.frags.push({ id: e.id, at: at, text: d.text });
    });
  });
  slot.forEach(function (s, name) { if (!s.frags.length && !s.mentions.length) problems.push('the catalogue chunk «' + name + '» documents no capability'); });
  if (problems.length) { const err = new Error('js/atlas-caps: ' + problems.join('; ')); err.problems = problems; throw err; }
  const val = function (t) { return typeof t === 'function' ? String(t(c || {})) : String(t == null ? '' : t); };
  return chunks.map(function (k) {
    const s = slot.get(k.name), ids = [];
    s.frags.sort(function (a, b) { return a.at - b.at; });
    s.frags.forEach(function (f) { if (ids.indexOf(f.id) < 0) ids.push(f.id); });
    s.mentions.forEach(function (id) { if (ids.indexOf(id) < 0) ids.push(id); });
    return { name: k.name, ids: ids, t: (k.head != null ? val(k.head) : '') + s.frags.map(function (f) { return val(f.text); }).join('') };
  });
}

/** the planner policy of every entry, keyed by id, as the eager registry holds it (scripts/atlas-caps.mjs copies it):
    { withdrawn: {id: {why, proofCode}}, ruleDocumented: {id: literal}, fallbacks: {id: 1}, forbidden: {id: [ids]},
    equivalents: {id: [ids]}, answers: {id: 1} } — in `order` (the registry's), so the copy is stable. Every id a policy names must be
    a capability. */
export function capabilityPolicy(modules, order) {
  const entries = capabilityEntries(modules), byId = new Map(entries.map(function (e) { return [e.id, e]; })), problems = [];
  const P = { withdrawn: {}, ruleDocumented: {}, fallbacks: {}, forbidden: {}, equivalents: {}, answers: {} };
  (order || entries.map(function (e) { return e.id; })).forEach(function (id) {
    const e = byId.get(id), p = e && e.policy;
    if (!p) return;
    if (p.withdrawn) {
      if (!p.withdrawn.why || !p.withdrawn.proofCode) problems.push(id + ': policy.withdrawn needs { why, proofCode }');
      P.withdrawn[id] = { why: String(p.withdrawn.why || ''), proofCode: String(p.withdrawn.proofCode || '') };
    }
    if (p.ruleDocumented) P.ruleDocumented[id] = String(p.ruleDocumented);
    if (p.fallback) P.fallbacks[id] = 1;
    if (p.answer) P.answers[id] = 1;
    ['forbidden', 'equivalents'].forEach(function (k) {
      if (!p[k]) return;
      if (!Array.isArray(p[k])) { problems.push(id + ': policy.' + k + ' is not a list of ids'); return; }
      p[k].forEach(function (o) { if (!byId.has(o)) problems.push(id + ': policy.' + k + ' names «' + o + '», which is not a capability'); });
      P[k][id] = p[k].slice();
    });
  });
  if (problems.length) { const err = new Error('js/atlas-caps: ' + problems.join('; ')); err.problems = problems; throw err; }
  return P;
}

/** dispatch spelling (row column 1) → run. A null-prototype map, so `toString` is not a capability. */
export function capabilityRunners(modules) {
  const run = Object.create(null);
  capabilityEntries(modules).forEach(function (e) { if (e.row[1]) run[e.row[1]] = e.run; });
  return run;
}

/** capability id → its argument schema, FRESH objects on every call */
export function capabilitySchemas(modules) {
  const S = {};
  capabilityEntries(modules).forEach(function (e) { S[e.id] = e.schema(); });
  return S;
}

/** the registry rows, in a stable order: the ids `previousIds` already had keep their places (the
    order is read by alias clashes, search ties and the catalogue), and new ids follow in module order */
export function capabilityRows(modules, previousIds) {
  const entries = capabilityEntries(modules);
  const byId = new Map(entries.map(function (e) { return [e.id, e]; }));
  const prev = (previousIds || []).filter(function (id) { return byId.has(id); });
  const had = new Set(prev);
  return prev.concat(entries.map(function (e) { return e.id; }).filter(function (id) { return !had.has(id); }))
    .map(function (id) { return byId.get(id).row; });
}

/* What the dispatch answers a spelling no row owns — the switch's `default`, moved whole: a control
   the action names by `target`/`name` is pressed if the page has one, otherwise 「不明な操作」. */
export async function unknownAction(a, dctx, K) { const doControl = K.doControl, R = K.R, warn = K.warn, L = K.L, esc = K.esc;
      { if(a.target||a.name){ const c=doControl({target:a.target||a.name,value:a.value,on:a.on}); if(c.ok) return c; } return R(false, warn(L('Unknown action','不明な操作','Unbekannte Aktion','Неизвестное действие','Acción desconocida')+': '+esc(a.type||''))); }
}

/* ══ THE ARGUMENT-SCHEMA BUILDERS ═══════════════════════════════════════════════════════════════
   Every entry's `schema` is written with these, so a schema reads as one line instead of a page of
   punctuation. The dialect and the three rules a schema follows are documented once, in
   js/atlas-schemas.js (which assembles the table from the entries). Each builder returns a FRESH
   object — a shared literal would let one consumer's annotation reach every capability that happens
   to take a latitude — and for the same reason an entry's `schema` is a function called once per
   makeAtlasSchemas(), never a literal evaluated at import. */
export function str() { return { type: 'string' }; }
export function bool() { return { type: 'boolean' }; }
export function num(min, max) { var o = { type: 'number' }; if (min != null) o.minimum = min; if (max != null) o.maximum = max; return o; }
export function int(min, max) { var o = { type: 'integer' }; if (min != null) o.minimum = min; if (max != null) o.maximum = max; return o; }
export function one() { return { type: 'string', enum: [].slice.call(arguments) }; }
export function list(item, min, max) { var o = { type: 'array' }; if (item) o.items = item; if (min != null) o.minItems = min; if (max != null) o.maxItems = max; return o; }
export function obj() { return { type: 'object' }; }
export function lat() { return { type: 'number', minimum: -90, maximum: 90 }; }
export function lng() { return { type: 'number', minimum: -180, maximum: 180 }; }
/* A field the case accepts in TWO shapes — an array OR a comma-separated string (`places`,
   `countries`, `avoid`), a number OR "5M" (`minPop`). The dialect has no union, and naming one
   of the two would reject the other, which is a shape the dispatch was written to accept. */
export function loose() { return {}; }
/* A capability whose case reads NOTHING — `clickId('btn-share')` and no more. `properties` is
   still not empty, and inventing an argument these cases do not read would be the very thing
   js/atlas-schemas.js exists to end. What they DO carry is `type`, the dispatch's own key (an
   action without one returns immediately).
   ⚠ AND IT IS PINNED TO THE ONE SPELLING THE EXECUTOR ITSELF SETS. js/atlas-toolsurface.js
   builds the action as `Object.assign({type: cap.legacy}, args)` — the arguments win — so a
   `type` the caller may choose freely is a way to send one capability's arguments into another
   capability's case. With the enum, an accepted `type` can only be the value that was going to
   be there anyway, and anything else is refused before the dispatch is reached. */
export function noArgs(legacy) { return { type: 'object', properties: { type: { type: 'string', enum: [legacy] } } }; }
