/* ============================================================================
 *  marketing-engine — the brand's one source, the social picture, and the historical-map entry pages
 * ----------------------------------------------------------------------------
 *  ① every file scripts/brand.mjs writes says what it would write (index.html head, docTitle/docDesc,
 *    manifest, README tagline, press kit, launch drafts) — and the manifest's own derivation agrees
 *  ② the landing page's headline IS the brand's tagline (two generators, one promise)
 *  ③ og-image.jpg is a real JPEG, light enough to unfurl, and the head states its real size
 *  ④ no number is typed into the brand's or the posts' words — they come from the files that own them
 *  ⑤ a post's link carries utm tags only where IntMap counts them, and those survive the counter's rule
 *  ⑥ the entry pages, generated by running the map's own border code, NAME A YEAR AND A PLACE and say
 *    what history says there (.agents/rules/historical-verification.md §2-1/§2-2)
 *  ⑦ the pages are coherent: runs partition the years, neighbours differ, links resolve, the map link
 *    opens the page's own region and date, hreflang is reciprocal, nothing executes, the sitemap is exact
 *  ⑧ the build writes them (vite.config.js), and the country-table fields the generator reads are the
 *    ones js/countries-ui.js reads
 * ========================================================================== */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
const { COUNTRY_HUB } = await import('../scripts/country-pages.mjs');   /* (country-pages) the history hub links it */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const norm = (s) => s.replace(/\r\n/g, '\n');

const brand = await import('../scripts/brand.mjs');
const { BRAND } = await import('../scripts/brand-text.mjs');
const { POSTS } = await import('../scripts/launch-text.mjs');

test('① every file the brand writes says what scripts/brand.mjs would write', async () => {
  const F = brand.brandFacts();
  const out = await brand.outputs(F);
  for (const [rel, body] of Object.entries(out)) {
    assert.ok(existsSync(join(ROOT, rel)), rel + ' is missing — run node scripts/brand.mjs --write');
    assert.equal(norm(read(rel)), norm(body), rel + ' differs from what scripts/brand.mjs writes — run node scripts/brand.mjs --write');
  }
  const M = await import('../scripts/build-app-manifest.mjs');
  assert.deepEqual(M.check(), [], 'manifest.webmanifest and its sources disagree');
  const doc = M.readDocument();
  const en = brand.words('en', F);
  assert.equal(doc.description, en.description, 'the manifest reads a description that is not the brand\'s');
  /* the app writes these over the head at run time: they must be the head's words, not a third answer */
  for (const [file, lang] of [['js/locales/ui.en.js', 'en'], ['js/locales/ui.jp.js', 'jp']]) {
    const W = brand.words(lang, F);
    const t = read(file);
    assert.equal(/docTitle:"([^"]*)"/.exec(t)[1], W.title, file + ' docTitle');
    assert.equal(/docDesc:"([^"]*)"/.exec(t)[1], W.description, file + ' docDesc');
  }
  /* the head is the one block, and the old promise is gone from it */
  const html = read('index.html');
  assert.equal(html.split(brand.HEAD_BEGIN).length, 2, 'one generated head block');
  assert.equal((html.match(/<title>[^<]*<\/title>/g) || []).length, 1, 'index.html has exactly one title element');
  for (const tag of ['og:title', 'og:description', 'og:image', 'og:url', 'og:image:width', 'og:image:height']) {
    assert.equal((html.match(new RegExp('property="' + tag + '"', 'g')) || []).length, 1, 'index.html states ' + tag + ' once');
  }
  for (const tag of ['twitter:card', 'twitter:title', 'twitter:description', 'twitter:image']) assert.ok(html.includes('name="' + tag + '"'), 'index.html has ' + tag);
  assert.ok(html.includes('<link rel="canonical" href="__INTMAP_SITE_URL__">'), 'index.html has a canonical that the build fills');
  const ld = JSON.parse(/<script type="application\/ld\+json">([^<]*)<\/script>/.exec(html)[1]);
  assert.equal(ld['@type'], 'WebApplication');
  assert.equal(ld.description, en.description);
  assert.deepEqual(ld.inLanguage, F.langTags, 'the app\'s languages, from the language registry');
});

test('② the landing page\'s headline is the brand\'s tagline, in both languages', async () => {
  const { TEXT } = await import('../scripts/landing-text.mjs');
  const flat = (s) => String(s).toLowerCase().replace(/[\s.。、,，]/g, '');
  assert.equal(flat(TEXT.en.about.hero.h1), flat(BRAND.en.tagline), 'about.html promises something other than the brand');
  assert.equal(flat(TEXT.jp.about.hero.h1), flat(BRAND.jp.tagline), 'ja/about.html promises something other than the brand');
});

test('③ og-image.jpg is a real JPEG, light enough to unfurl, and the head states its real size', () => {
  const info = brand.jpegInfo(brand.SOCIAL_IMAGE);
  assert.ok(info.jpeg, 'og-image.jpg must be a JPEG (it was a 1 MB PNG under a .jpg name)');
  /* ⚠ (no-ad-hoc-hardcoding §4) observation: WhatsApp is reported (not documented by Meta) to drop the preview
     picture above ~300 kB; the other card readers allow megabytes, so this is the tightest. Lapses: if that
     reader's limit moves. Canonical: here. */
  assert.ok(info.bytes <= 300 * 1024, 'og-image.jpg is ' + info.bytes + ' bytes — over the ~300 kB a WhatsApp preview is reported to take');
  const html = read('index.html');
  assert.ok(html.includes('property="og:image:width" content="' + info.width + '"') && html.includes('property="og:image:height" content="' + info.height + '"'),
    'index.html states a size that is not the file\'s');
  assert.ok(info.width >= 1200, 'the large card wants at least 1200 px across');
});

test('④ no number is typed into the brand\'s or the posts\' words', () => {
  /* the tokens that contain a digit and are NOT a fact IntMap could drift from — each says why */
  const ALLOWED = [
    [/CShapes 2\.0/g, 'the dataset\'s own name (Schvitz et al. 2022 publish it as «CShapes 2.0»)'],
    [/\?embed=1/g, 'the embed address grammar itself (js/embed-mode.js), not a quantity'],
    [/3-D/g, 'a word'],
  ];
  const strings = [];
  const walk = (v, where) => { if (typeof v === 'string') strings.push([where, v]); else if (v && typeof v === 'object') for (const [k, x] of Object.entries(v)) walk(x, where + '.' + k); };
  walk(BRAND, 'BRAND');
  walk(POSTS, 'POSTS');
  for (const [where, s] of strings) {
    let t = s.replace(/\{[^{}]*\}/g, '');
    for (const [re] of ALLOWED) t = t.replace(re, '');
    assert.ok(!/\d/.test(t), where + ' types a number: «' + s.slice(0, 120) + '» — use a placeholder filled from the file that owns it');
  }
});

test('⑤ a post\'s link carries utm tags only into the app, and the counter keeps all three', async () => {
  const { campaignOf } = await import('../supabase/functions/usage-count/shape.js');
  for (const post of POSTS) {
    const u = new URL(brand.postUrl(post));
    const tags = campaignOf(u.search);
    if (brand.countsCampaign(post)) assert.equal(tags.length, 3, post.id + ': the counter keeps ' + tags.length + ' of the three utm tags (' + u.search + ')');
    else assert.equal(u.search, '', post.id + ' links a static page, which has no counter — no utm tags');
  }
  const ids = POSTS.map((p) => p.id);
  assert.equal(new Set(ids).size, ids.length, 'post ids are unique');
});

/* ══ the entry pages ═══════════════════════════════════════════════════════════════════════════════ */
const H = await import('../scripts/history-pages.mjs');
const YEARS = [-2999, 1500, 1900, 1913, 1914, 1918, 1919, 1920, 1946, 1950];
const REGIONS = ['world', 'europe', 'east-asia'];
const M = await H.collect({ years: YEARS, regions: REGIONS });
const at = (region, y) => M.pages.find((p) => p.region === region && y >= p.first && y <= p.last);
const names = (p) => new Set(p.names.map((n) => n.en));

test('⑥ named years and places say what history says (the map\'s own labels, its own records)', () => {
  /* Europe, 1 July 1913 — before the war: the four empires; no state that only the peace made */
  const e13 = at('europe', 1913);
  assert.equal(e13.tier, 'cshapes');
  for (const n of ['Austria-Hungary', 'German Empire', 'Russian Empire', 'Ottoman Empire']) assert.ok(names(e13).has(n), 'Europe 1913 lacks ' + n);
  for (const n of ['Czechoslovakia', 'Poland', 'Weimar Republic']) assert.ok(!names(e13).has(n), 'Europe 1913 draws ' + n + ', which did not yet exist');
  /* Europe, 1 July 1920 — after it: Austria-Hungary dissolved (1918-11), Czechoslovakia (1918-10-28) and
     Poland (1918-11-11) exist, the German Empire is the Weimar Republic (1919) */
  const e20 = at('europe', 1920);
  for (const n of ['Czechoslovakia', 'Poland', 'Weimar Republic']) assert.ok(names(e20).has(n), 'Europe 1920 lacks ' + n);
  for (const n of ['Austria-Hungary', 'German Empire']) assert.ok(!names(e20).has(n), 'Europe 1920 still draws ' + n);
  /* East Asia, 1 July 1900 — Qing, the Korean Empire (1897–1910), the Empire of Japan */
  const a00 = at('east-asia', 1900);
  for (const n of ['Qing Empire', 'Korean Empire', 'Empire of Japan']) assert.ok(names(a00).has(n), 'East Asia 1900 lacks ' + n);
  assert.ok(!names(a00).has('Republic of China'), 'East Asia 1900 draws the Republic of China (1912)');
  /* the Japanese labels are the map's, from its tables — not the English carried over */
  const jp = new Map(a00.names.map((n) => [n.en, n.jp]));
  assert.equal(jp.get('Empire of Japan'), '大日本帝国');
  assert.equal(jp.get('Korean Empire'), '大韓帝国');
  /* 3000 BC is a sheet, and the sheet is the year's own */
  const w3 = at('world', -2999);
  assert.ok(w3 && w3.sheet && w3.tier === 'snapshot' && w3.first === -2999, 'the world of 3000 BC is the sheet of that year');
  assert.ok(names(w3).has('Egypt'));
  /* every listed name has area inside the region, and the list is ordered by it */
  for (const p of M.pages) {
    for (const n of p.names) assert.ok(n.km > 0, p.region + ' ' + p.first + ': ' + n.en + ' is listed with no area inside the region');
    for (let i = 1; i < p.names.length; i++) assert.ok(p.names[i - 1].km >= p.names[i].km, p.region + ' ' + p.first + ' is not ordered by area');
  }
});

/* ⑥b the names the first pass found wrong on the map (and so on these pages), read back from the map's own labels.
   ⚠ stated as the DEFECT (a state named before it existed, a place named as today's state), not as the words chosen */
test('⑥b no state is named before it existed, and a place is not named as the state of today', () => {
  const jpOf = (p) => new Map(p.names.map((n) => [n.en, n.jp]));
  /* 1500 (a sheet) and 1900 (Japanese Taiwan): the island, not the Republic of China (1912) */
  const a15 = jpOf(at('east-asia', 1500)), a00 = jpOf(at('east-asia', 1900));
  assert.ok(a15.has('Taiwan'), 'the 1500 sheet no longer draws Taiwan — re-read what it draws');
  for (const [y, m] of [[1500, a15], [1900, a00]]) for (const [en, jp] of m) assert.ok(!/中華民国/.test(jp || ''), y + ': «' + en + '» is written ' + jp + ' — the Republic of China was founded in 1912');
  /* 1946: occupied Germany and Korea — the Federal Republic (1949), the GDR (1949) and the two Korean states (1948) are not yet */
  const e46 = names(at('europe', 1946)), k46 = names(at('east-asia', 1946));
  for (const n of ['West Germany', 'East Germany']) assert.ok(!e46.has(n), 'Europe 1946 draws ' + n);
  for (const n of ['North Korea', 'South Korea']) assert.ok(!k46.has(n), 'East Asia 1946 draws ' + n);
  /* …and in 1950 they are */
  const e50 = names(at('europe', 1950)), k50 = names(at('east-asia', 1950));
  for (const n of ['West Germany', 'East Germany']) assert.ok(e50.has(n), 'Europe 1950 lacks ' + n);
  for (const n of ['North Korea', 'South Korea']) assert.ok(k50.has(n), 'East Asia 1950 lacks ' + n);
  /* a held land is not its holder: the Soviet zones are not labelled the Soviet Union */
  for (const p of [at('europe', 1946), at('east-asia', 1946)]) {
    const zone = p.names.filter((n) => /\((USSR|USA|Western Allies)\)$/.test(n.en));
    assert.ok(zone.length >= 2, p.region + ' 1946 draws no occupation zone by name');
    for (const n of zone) assert.ok(n.jp && !/ソビエト連邦/.test(n.jp), n.en + ' reads ' + n.jp);
  }
});

test('⑦ runs partition the years; neighbours differ; pages, links, map links, hreflang and sitemap are coherent', async () => {
  for (const region of REGIONS) {
    const list = M.byRegion.get(region);
    const covered = list.flatMap((p) => p.years);
    assert.equal(new Set(covered).size, covered.length, region + ': a year is on two pages');
    for (let i = 1; i < list.length; i++) {
      const a = list[i - 1], b = list[i];
      if (!a.sheet && !b.sheet && a.last + 1 === b.first) assert.notEqual(a.key, b.key, region + ': ' + a.first + ' and ' + b.first + ' are one run split in two');
    }
  }
  const out = H.outputs(M);
  const pagesIn = Object.keys(out).filter((k) => k.endsWith('index.html'));
  const STATIC = new Set(['index.html', 'about.html', 'ja/about.html', 'sources.html', 'science.html', 'privacy.html', 'terms.html',
    'IntMap.Icon.png', 'css/fonts.css', 'css/pages.css', 'css/landing.css', 'css/history-pages.css']);
  for (const rel of pagesIn) {
    const html = out[rel];
    const dir = posix.dirname(rel) + '/';
    assert.ok(!/\{\w/.test(html.replace(/<script type="application\/ld\+json">[^<]*<\/script>/g, '')), rel + ' carries an unfilled placeholder');
    /* nothing executes: the only <script> is data (in any case — HTML tag names are case-insensitive) */
    for (const m of html.matchAll(/<script\b([^>]*)>/gi)) assert.match(m[1], /type="application\/ld\+json"/, rel + ' runs a script');
    for (const m of html.matchAll(/<script type="application\/ld\+json">([^<]*)<\/script>/g)) JSON.parse(m[1]);
    /* canonical is itself; hreflang names both languages and each names the other back */
    const canon = /<link rel="canonical" href="__INTMAP_SITE_URL__([^"]*)">/.exec(html)[1];
    assert.equal(canon, dir.replace(/^\.\//, ''), rel + ' canonical');
    for (const lang of ['en', 'ja']) {
      const alt = new RegExp('hreflang="' + lang + '" href="__INTMAP_SITE_URL__([^"]*)"').exec(html)[1];
      assert.ok(out[alt + 'index.html'], rel + ' names a ' + lang + ' twin that is not generated: ' + alt);
      assert.ok(out[alt + 'index.html'].includes('href="__INTMAP_SITE_URL__' + canon + '"'), alt + ' does not name ' + canon + ' back');
    }
    /* every relative link lands on a generated page or a file the site ships */
    for (const m of html.matchAll(/(?:href|src)="([^"#:]+)(#[^"]*)?"|content="(__INTMAP_SITE_URL__[^"#]*)"/g)) {
      if (m[3]) m[1] = m[3];
      const abs = m[1].startsWith('__INTMAP_SITE_URL__');   /* an absolute address the build fills in */
      const target = abs ? m[1].slice('__INTMAP_SITE_URL__'.length) : posix.normalize(dir + m[1]);
      const ok = target === '' || out[target + (target.endsWith('/') ? 'index.html' : '')] || STATIC.has(target) || out[target] || target === 'og-image.jpg'
        || target === COUNTRY_HUB || target === 'ja/' + COUNTRY_HUB;   /* (country-pages) the history hub links the country list, which its own generator writes */
      assert.ok(ok, rel + ' links to ' + m[1] + ' (' + target + '), which is neither generated nor shipped');
    }
  }
  /* the map link opens the page's own region and first date, in the app's own grammar */
  for (const p of M.pages) {
    const region = M.regions.find((r) => r.id === p.region);
    const q = new URLSearchParams(H.mapLink(p, region).split('#')[1]);
    const v = q.get('v').split(',').map(Number);
    const want = H.regionView(region);
    assert.ok(Math.abs(v[0] - want.lng) < 1e-4 && Math.abs(v[1] - want.lat) < 1e-4 && Math.abs(v[2] - want.zoom) < 1e-2, p.region + ' ' + p.first + ' opens the wrong view: ' + v.slice(0, 3) + ' vs ' + [want.lng, want.lat, want.zoom]);
    assert.equal(q.get('tt'), H.isoDay(p.first), p.region + ' ' + p.first + ' opens the wrong date');
    const box = region.boxes[0];
    if (region.boxes.length === 1) assert.ok(want.lng >= box[0] && want.lng <= box[2] && want.lat >= box[1] && want.lat <= box[3], p.region + ': the view centre is outside its box');
  }
  /* the sitemap lists every generated page in both languages, once, and nothing else */
  const locs = [...out[H.SITEMAP].matchAll(/<loc>__INTMAP_SITE_URL__([^<]*)<\/loc>/g)].map((m) => m[1]);
  assert.equal(new Set(locs).size, locs.length, 'a URL is in the sitemap twice');
  assert.deepEqual(locs.map((l) => l + 'index.html').sort(), pagesIn.slice().sort(), 'the sitemap and the pages disagree');
  const idx = [...out[H.SITEMAP_INDEX].matchAll(/<loc>__INTMAP_SITE_URL__([^<]*)<\/loc>/g)].map((m) => m[1]);
  /* (ops-next) …and the updates pages' sitemap (scripts/whats-new.mjs SITEMAP) */
  const { OTD_SITEMAP } = await import('../scripts/on-this-day-pages.mjs');   /* (marketing-next) the third generator's sitemap */
  const { COUNTRY_SITEMAP } = await import('../scripts/country-pages.mjs');   /* (country-pages) the fourth */
  assert.deepEqual(idx, ['sitemap.xml', H.SITEMAP, 'sitemap-updates.xml', OTD_SITEMAP, COUNTRY_SITEMAP], 'the sitemap index joins the landing sitemap, this one, the one of the updates pages, the «on this day» one and the country pages’ one');
});

test('⑦b the words of the entry pages exist in both languages, key for key', async () => {
  const { TEXT } = await import('../scripts/history-pages-text.mjs');
  const shape = (v) => (typeof v === 'string' ? 's' : Object.fromEntries(Object.keys(v).sort().map((k) => [k, shape(v[k])])));
  assert.deepEqual(shape(TEXT.jp), shape(TEXT.en));
  assert.deepEqual(Object.keys(TEXT.en.regions).sort(), H.REGIONS.map((r) => r.id).sort(), 'every region has a name, and every name a region');
});

test('⑧ the build writes the pages, and the country fields read are js/countries-ui.js\'s', async () => {
  const { STATIC_ASSETS } = await import('../vite.config.js');
  assert.ok(STATIC_ASSETS.includes('css/history-pages.css'), 'the entry pages\' stylesheet is not copied into dist/');
  const vite = read('vite.config.js');
  assert.match(vite, /copyStatic\(\), historyPagesPlugin\(\)/, 'the pages are written after the static copy (and before the site URL is filled, which runs post)');
  const ui = read('js/countries-ui.js');
  for (const expr of ['nameEn:p.NAME_EN||p.ADMIN||p.NAME||code', 'nameJp:p.NAME_JA||p.NAME_EN||p.ADMIN||code', "(_neType==='Indeterminate')", "const a2=(p.ISO_A2_EH&&p.ISO_A2_EH!=='-99')?p.ISO_A2_EH:p.ISO_A2;", "a2:a2||''"]) {
    assert.ok(ui.includes(expr), 'js/countries-ui.js no longer reads «' + expr + '» — scripts/history-pages.mjs builds the country table the label pass reads the same way; change both');
  }
});
