import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { check } from '../scripts/build-border-detail.mjs';

test('persisted detail fingerprints, fragments, source ids, size bounds and manifest counts validate offline', () => {
  const stats=check();
  assert.ok(Object.values(stats).every(s=>s.refined>0&&s.bytes>0));
});

test('the offline gate rejects missing/stale assets rather than accepting an index alone', () => {
  const root=mkdtempSync(join(tmpdir(),'intmap-r711-detail-'));
  try {
    mkdirSync(join(root,'data/border-detail'),{recursive:true});
    writeFileSync(join(root,'data/border-detail/index.json'),JSON.stringify({v:1,targetTolerance:0.0005,decimals:5,inlandKm:6,
      source:'OpenHistoricalMap (CC0)',sets:{},stats:{}}));
    assert.throws(()=>check(root));
  }finally{rmSync(root,{recursive:true,force:true});}
});

test('LF and CRLF checkouts measure the same generated bytes without hiding manifest drift', () => {
  const root=mkdtempSync(join(tmpdir(),'intmap-r712-detail-eol-'));
  try {
    const out=join(root,'data/border-detail');mkdirSync(out,{recursive:true});
    const w={};new Function('window',readFileSync(new URL('../js/border-coast.js',import.meta.url),'utf8'))(w);
    const ring=[[0,0],[1,0],[1,1],[0,1],[0,0]],key=w.IntMapBorderCoast.geometryKey([[ring]]);
    const index={v:1,targetTolerance:0.0005,decimals:5,inlandKm:6,source:'OpenHistoricalMap (CC0)',sets:{},stats:{}};
    const body=JSON.stringify({lines:{[key]:[ring]},relations:{[key]:1}});
    const hash=createHash('sha256').update(body).digest('hex').slice(0,16);
    const paths=[];
    for(const [name,global] of [['hist-borders','__HISTB'],['hist-admin1','__HISTADM1'],['hist-admin2','__HISTADM2']]) {
      const file=name+'-'+hash+'.json';paths.push(join(out,file));
      writeFileSync(join(root,'data',name+'.js'),'window.'+global+'='+JSON.stringify({rings:[ring],feats:[['unit',4,1800,1,1,1900,1,1,[[0]],{},1]]})+';\n');
      index.sets[global]={0:[key,[[file,[0,0,1,1]]]]};
      index.stats[global]={records:1,refined:1,retained:0,vertices:ring.length,bytes:Buffer.byteLength(body+'\n'),chunks:1};
    }
    const saveIndex=()=>writeFileSync(join(out,'index.json'),JSON.stringify(index)+'\n');saveIndex();
    for(const eol of ['\n','\r\n']) {
      for(const path of paths)writeFileSync(path,body+eol);
      assert.deepEqual(check(root),index.stats);
    }
    index.stats.__HISTB.bytes++;saveIndex();
    assert.throws(()=>check(root),/chunk measurements differ: __HISTB/);
  }finally{rmSync(root,{recursive:true,force:true});}
});
