/* ============================================================================
 *  IntMap · WORLD WAR I — the curated record   (#R349)
 * ----------------------------------------------------------------------------
 *  The rules every row here obeys — what `control`, `fronts` and `events` are each allowed to
 *  claim, and why a day nobody wrote down gets no line — are stated once, in ./lang.mjs.
 * ==========================================================================*/
import { L, F_WW1 } from './lang.mjs';

/* ══════════════════════════════════════════════════════════════════════════════════════════════
 *  WORLD WAR I · 28 July 1914 — 11 November 1918
 * ════════════════════════════════════════════════════════════════════════════════════════════ */
const WW1 = {
  id: 'ww1',
  name: L('World War I', '第一次世界大戦', 'Erster Weltkrieg', 'Первая мировая война', 'Primera Guerra Mundial', '第一次世界大戰', '第一次世界大战', 'Première Guerre mondiale', '제1차 세계 대전'),
  from: '1914-07-28', to: '1918-11-11',
  factions: F_WW1,
  /* gwcode → [[date, faction], …]. A country absent from this table is neutral for the whole war. */
  control: {
    300: [['1914-07-28', 'CENTRAL']],                                    /* Austria-Hungary */
    /* Serbia — cleared by 15 Dec 1914 (the front above stops there); overrun again in the Oct–Nov 1915
       offensive. ⚠ THE SEVEN WEEKS OF THAT SECOND CONQUEST ARE CONTESTED, NOT A LINE: Mackensen came
       from the north and the Bulgarians from the east at once, and a country being closed on from two
       sides at speed has no single quotable front. Belgrade retaken 1 Nov 1918. */
    340: [['1914-07-28', 'ALLIED'], ['1915-10-07', 'CONTESTED'], ['1915-11-24', 'CENTRAL'], ['1918-11-01', 'ALLIED']],
    341: [['1914-08-05', 'ALLIED'], ['1916-01-25', 'CENTRAL'], ['1918-11-01', 'ALLIED']],   /* Montenegro — capitulated 25 Jan 1916 */
    255: [['1914-08-01', 'CENTRAL']],                                    /* Germany */
    365: [['1914-08-01', 'ALLIED'], ['1918-03-03', 'NEUTRAL']],          /* Russia — out at Brest-Litovsk */
    220: [['1914-08-03', 'ALLIED']],                                     /* France */
    211: [['1914-08-04', 'ALLIED'], ['1914-08-20', 'CONTESTED']],        /* Belgium — Brussels fell 20 Aug; the front takes over from 20 Nov */
    212: [['1914-08-02', 'CENTRAL']],                                    /* Luxembourg — occupied on day one, never a battlefield */
    200: [['1914-08-04', 'ALLIED']],                                     /* United Kingdom */
    740: [['1914-08-23', 'ALLIED']],                                     /* Japan */
    640: [['1914-10-29', 'CENTRAL']],                                    /* Ottoman Empire */
    325: [['1915-05-23', 'ALLIED']],                                     /* Italy */
    355: [['1915-10-14', 'CENTRAL'], ['1918-09-29', 'NEUTRAL']],         /* Bulgaria — Armistice of Salonica */
    /* Rumania — ⚠ #R381 REPLACED THE CONTESTED SPAN WITH A LINE. #R349 painted the whole country one
       colour from 6 Dec 1916 to 7 May 1918 because it had no front to quote; the Siret line held for
       seventeen months and is quotable, so the `romanian` front below divides the country and this
       row simply says whose it was. Treaty of Bucharest 7 May 1918; re-entered 10 Nov 1918. */
    360: [['1916-08-27', 'ALLIED'], ['1918-05-07', 'CENTRAL'], ['1918-11-10', 'ALLIED']],
    235: [['1916-03-09', 'ALLIED']],                                     /* Portugal */
    /* Albania — never a belligerent and never its own master either: Italy held Vlorë from Dec 1914,
       Austria-Hungary took the north when Montenegro capitulated, and the Macedonian front ran across
       it from Aug 1916. Contested until the Allies came up through it in Oct 1918. */
    339: [['1916-01-23', 'CONTESTED'], ['1918-10-15', 'ALLIED']],
    2: [['1917-04-06', 'ALLIED']],                                       /* United States */
    350: [['1917-06-29', 'ALLIED']],                                     /* Greece — after the National Schism; the Salonika front stood on its soil from 1915 */
    800: [['1917-07-22', 'ALLIED']],                                     /* Siam */
    710: [['1917-08-14', 'ALLIED']],                                     /* China */
    450: [['1917-08-04', 'ALLIED']],                                     /* Liberia */
    140: [['1917-10-26', 'ALLIED']],                                     /* Brazil */
    40: [['1917-04-07', 'ALLIED']], 95: [['1917-04-07', 'ALLIED']],      /* Cuba · Panama */
    90: [['1918-04-23', 'ALLIED']], 93: [['1918-05-08', 'ALLIED']],      /* Guatemala · Nicaragua */
    41: [['1918-07-12', 'ALLIED']], 91: [['1918-07-19', 'ALLIED']],      /* Haiti · Honduras */
    /* — the empires' territories, which entered with their metropole — */
    20: [['1914-08-04', 'ALLIED']], 21: [['1914-08-04', 'ALLIED']], 900: [['1914-08-04', 'ALLIED']],
    920: [['1914-08-04', 'ALLIED']], 560: [['1914-08-04', 'ALLIED']], 750: [['1914-08-04', 'ALLIED']],
    338: [['1914-08-04', 'ALLIED']], 31: [['1914-08-04', 'ALLIED']], 51: [['1914-08-04', 'ALLIED']],
    52: [['1914-08-04', 'ALLIED']], 53: [['1914-08-04', 'ALLIED']], 80: [['1914-08-04', 'ALLIED']],
    110: [['1914-08-04', 'ALLIED']], 420: [['1914-08-04', 'ALLIED']], 451: [['1914-08-04', 'ALLIED']],
    452: [['1914-08-04', 'ALLIED']], 475: [['1914-08-04', 'ALLIED']], 500: [['1914-08-04', 'ALLIED']],
    501: [['1914-08-04', 'ALLIED']], 511: [['1914-08-04', 'ALLIED']], 521: [['1914-08-04', 'ALLIED']],
    551: [['1914-08-04', 'ALLIED']], 552: [['1914-08-04', 'ALLIED']], 553: [['1914-08-04', 'ALLIED']],
    570: [['1914-08-04', 'ALLIED']], 571: [['1914-08-04', 'ALLIED']], 572: [['1914-08-04', 'ALLIED']],
    590: [['1914-08-04', 'ALLIED']], 625: [['1914-08-04', 'ALLIED']], 651: [['1914-08-04', 'ALLIED']],
    780: [['1914-08-04', 'ALLIED']], 781: [['1914-08-04', 'ALLIED']], 821: [['1914-08-04', 'ALLIED']],
    822: [['1914-08-04', 'ALLIED']], 823: [['1914-08-04', 'ALLIED']], 824: [['1914-08-04', 'ALLIED']],
    827: [['1914-08-04', 'ALLIED']], 835: [['1914-08-04', 'ALLIED']], 911: [['1914-08-04', 'ALLIED']],
    940: [['1914-08-04', 'ALLIED']], 950: [['1914-08-04', 'ALLIED']],
    65: [['1914-08-03', 'ALLIED']], 66: [['1914-08-03', 'ALLIED']], 120: [['1914-08-03', 'ALLIED']],
    432: [['1914-08-03', 'ALLIED']], 433: [['1914-08-03', 'ALLIED']], 434: [['1914-08-03', 'ALLIED']],
    435: [['1914-08-03', 'ALLIED']], 436: [['1914-08-03', 'ALLIED']], 437: [['1914-08-03', 'ALLIED']],
    438: [['1914-08-03', 'ALLIED']], 481: [['1914-08-03', 'ALLIED']], 482: [['1914-08-03', 'ALLIED']],
    483: [['1914-08-03', 'ALLIED']], 484: [['1914-08-03', 'ALLIED']], 522: [['1914-08-03', 'ALLIED']],
    580: [['1914-08-03', 'ALLIED']], 585: [['1914-08-03', 'ALLIED']], 600: [['1914-08-03', 'ALLIED']],
    615: [['1914-08-03', 'ALLIED']], 616: [['1914-08-03', 'ALLIED']], 811: [['1914-08-03', 'ALLIED']],
    812: [['1914-08-03', 'ALLIED']], 815: [['1914-08-03', 'ALLIED']], 930: [['1914-08-03', 'ALLIED']],
    960: [['1914-08-03', 'ALLIED']],
    490: [['1914-08-04', 'ALLIED']],                                     /* Belgian Congo */
    402: [['1916-03-09', 'ALLIED']], 404: [['1916-03-09', 'ALLIED']], 540: [['1916-03-09', 'ALLIED']],
    541: [['1916-03-09', 'ALLIED']], 860: [['1916-03-09', 'ALLIED']],
    620: [['1915-05-23', 'ALLIED']], 531: [['1915-05-23', 'ALLIED']], 5200: [['1915-05-23', 'ALLIED']],
    713: [['1914-08-23', 'ALLIED']], 730: [['1914-08-23', 'ALLIED']], 7351: [['1914-08-23', 'ALLIED']],
    /* — the German colonies, each taken on its own documented day — */
    460: [['1914-08-01', 'CENTRAL'], ['1914-08-26', 'ALLIED']],          /* Togoland — surrendered 26 Aug 1914 */
    912: [['1914-08-01', 'CENTRAL'], ['1914-09-17', 'ALLIED']],          /* German New Guinea — 17 Sep 1914 */
    565: [['1914-08-01', 'CENTRAL'], ['1915-07-09', 'ALLIED']],          /* German South West Africa — 9 Jul 1915 */
    470: [['1914-08-01', 'CENTRAL'], ['1916-02-18', 'ALLIED']],          /* Kamerun — last garrison surrendered 18 Feb 1916 */
    510: [['1914-08-01', 'CENTRAL'], ['1916-09-04', 'CONTESTED']],   /* German East Africa — Dar es Salaam fell 4 Sep 1916, and the campaign was STILL RUNNING when the armistice closed this window: von Lettow-Vorbeck did not surrender until 25 Nov 1918, a fortnight past the last day this layer draws. Contested to the end is the true answer here. */
  },
  fronts: [
    {
      id: 'west',
      name: L('Western Front', '西部戦線', 'Westfront', 'Западный фронт', 'Frente Occidental', '西方戰線', '西方战线', 'Front de l’Ouest', '서부 전선'),
      left: 'ALLIED', right: 'CENTRAL',    /* the lines run north → south, so «left» is the western side */
      dates: [
        { d: '1914-08-24', cuts: [211, 220], note: L('The Great Retreat — Brussels, Liège and Namur are gone and the armies are falling back from the Battle of the Frontiers', '大退却——ブリュッセル・リエージュ・ナミュールは失われ、国境の戦いから両軍が後退中', 'Der große Rückzug — Brüssel, Lüttich und Namur sind verloren, die Armeen weichen aus der Grenzschlacht zurück', 'Великое отступление — Брюссель, Льеж и Намюр потеряны, армии отходят после Пограничного сражения', 'La Gran Retirada: Bruselas, Lieja y Namur han caído y los ejércitos retroceden desde la Batalla de las Fronteras', '大撤退——布魯塞爾、列日、那慕爾陷落，各軍自邊境戰役後撤', '大撤退——布鲁塞尔、列日、那慕尔陷落，各军自边境战役后撤', 'La Grande Retraite — Bruxelles, Liège et Namur sont tombées et les armées refluent depuis la bataille des Frontières', '대후퇴 — 브뤼셀·리에주·나뮈르가 함락되고 국경 전투에서 양군이 후퇴 중'),
          pts: ['Ghent', 'Mons', 'Charleroi', 'Namur', 'Sedan', 'Verdun', 'Nancy', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1914-09-05', cuts: [220], note: L('The German high-water mark on the eve of the Marne', 'マルヌ会戦前夜、ドイツ軍の最大進出線', 'Der weiteste deutsche Vormarsch am Vorabend der Marneschlacht', 'Предел германского продвижения накануне Марны', 'El avance máximo alemán en vísperas del Marne', '馬恩河戰役前夕德軍推進的最遠線', '马恩河战役前夕德军推进的最远线', 'L’avance allemande maximale à la veille de la Marne', '마른 전투 전야, 독일군 최대 진출선'),
          pts: ['Meaux', 'Chateau-Thierry', 'Vitry-le-Francois', 'Douaumont', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1914-09-13', cuts: [220], pts: ['Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1914-11-20', cuts: [211, 220], note: L('The line after the Race to the Sea — it will barely move for three years', '「海への競争」後の戦線。以後3年間ほとんど動かない', 'Die Linie nach dem Wettlauf zum Meer — sie bewegt sich drei Jahre lang kaum', 'Линия после «бега к морю» — три года она почти не сдвинется', 'La línea tras la Carrera hacia el Mar: apenas se moverá en tres años', '「奔向大海」後的戰線，此後三年幾乎不動', '“奔向大海”后的战线，此后三年几乎不动', 'La ligne après la Course à la mer — elle ne bougera presque pas pendant trois ans', '“바다로의 경주” 이후의 전선 — 이후 3년간 거의 움직이지 않는다'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Peronne', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        /* ⚠ 1915 AND 1916 ARE HERE WITH THE SAME ANCHORS ON PURPOSE. Between the Race to the Sea and
           the Hindenburg withdrawal the Western Front moved in kilometres, not in towns: Second Ypres,
           Loos, Champagne, Artois, Verdun and the Somme together shifted it less than the distance
           between any two names on this line. Repeating the trace and dating it is what the record
           says; inventing a new bend for each battle would not be. */
        { d: '1915-05-01', cuts: [211, 220], note: L('Second Ypres has shrunk the salient; the line is otherwise where the Race to the Sea left it', '第二次イーペルで突出部は縮んだが、戦線はそれ以外「海への競争」の位置のまま', 'Die zweite Flandernschlacht hat den Bogen verkleinert; sonst liegt die Linie, wo der Wettlauf zum Meer sie ließ', 'Вторая битва при Ипре сузила выступ; в остальном линия там, где её оставил «бег к морю»', 'La segunda batalla de Ypres ha reducido el saliente; por lo demás la línea sigue donde la dejó la Carrera hacia el Mar', '第二次伊珀爾戰役使突出部縮小，其餘戰線仍在「奔向大海」留下的位置', '第二次伊普尔战役使突出部缩小，其余战线仍在“奔向大海”留下的位置', 'La deuxième bataille d’Ypres a réduit le saillant ; ailleurs la ligne est là où la Course à la mer l’a laissée', '제2차 이프르 전투로 돌출부는 줄었으나, 전선은 “바다로의 경주”가 남긴 자리 그대로'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Peronne', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1915-09-25', cuts: [211, 220], note: L('Loos and the Second Champagne offensive open — and end without moving the line a town’s width', 'ロース・第二次シャンパーニュ攻勢が始まり、町ひとつぶんも戦線を動かさずに終わる', 'Loos und die zweite Champagne-Offensive beginnen — und enden, ohne die Linie um eine Stadtbreite zu verschieben', 'Начинаются Лоос и вторая Шампанская операция — и заканчиваются, не сдвинув линию и на ширину города', 'Comienzan Loos y la segunda ofensiva de Champaña, y terminan sin mover la línea ni el ancho de un pueblo', '盧斯與第二次香檳攻勢展開，結束時戰線未移動一個城鎮的寬度', '卢斯与第二次香槟攻势展开，结束时战线未移动一个城镇的宽度', 'Loos et la seconde offensive de Champagne s’ouvrent — et s’achèvent sans déplacer la ligne de la largeur d’une ville', '루스와 제2차 샹파뉴 공세가 시작되어, 마을 하나 너비만큼도 전선을 옮기지 못하고 끝난다'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Peronne', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1916-07-01', cuts: [211, 220], pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Peronne', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1916-11-18', cuts: [211, 220], note: L('The Somme ends after 141 days, and Verdun a month later — both where they began', 'ソンムは141日で終わり、ヴェルダンもその1か月後に終わる——どちらも始まった場所で', 'Die Somme endet nach 141 Tagen, Verdun einen Monat später — beide dort, wo sie begannen', 'Сомма кончается на 141-й день, Верден — месяцем позже; обе там, где начались', 'El Somme termina tras 141 días, y Verdún un mes después: ambos donde empezaron', '索姆河戰役141天後結束，凡爾登再過一個月——都停在起點', '索姆河战役141天后结束，凡尔登再过一个月——都停在起点', 'La Somme s’achève après 141 jours, Verdun un mois plus tard — l’une et l’autre là où elles ont commencé', '솜 전투가 141일 만에, 베르됭은 한 달 뒤에 끝난다 — 둘 다 시작한 자리에서'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Peronne', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1917-04-05', cuts: [211, 220], note: L('After the German withdrawal to the Hindenburg Line', 'ドイツ軍のヒンデンブルク線への後退後', 'Nach dem deutschen Rückzug auf die Siegfriedstellung', 'После отхода немцев на линию Гинденбурга', 'Tras la retirada alemana a la Línea Hindenburg', '德軍後撤至興登堡防線之後', '德军后撤至兴登堡防线之后', 'Après le repli allemand sur la ligne Hindenburg', '독일군이 힌덴부르크 선으로 후퇴한 뒤'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Cambrai', 'Saint-Quentin', 'Laon', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1917-11-10', cuts: [211, 220], note: L('Passchendaele ends: three months of fighting have pushed the Ypres salient out by eight kilometres', 'パッシェンデール終結——3か月の戦闘でイーペル突出部は8キロ押し出された', 'Passchendaele endet: drei Monate Kampf haben den Ypernbogen um acht Kilometer vorgeschoben', 'Пашендейль окончен: три месяца боёв продвинули Ипрский выступ на восемь километров', 'Passchendaele termina: tres meses de combate han empujado el saliente de Ypres ocho kilómetros', '帕森達勒戰役結束：三個月的戰鬥將伊珀爾突出部推進八公里', '帕斯尚尔战役结束：三个月的战斗将伊普尔突出部推进八公里', 'Passchendaele s’achève : trois mois de combats ont poussé le saillant d’Ypres de huit kilomètres', '파스샹달 종료 — 3개월의 전투로 이프르 돌출부가 8킬로미터 밀려났다'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Cambrai', 'Saint-Quentin', 'Laon', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-03-20', cuts: [211, 220], note: L('The eve of Operation Michael — the last day the front stands where it has stood since 1914', 'ミヒャエル作戦前夜——1914年以来の位置に戦線が立つ最後の日', 'Der Vorabend der Operation Michael — der letzte Tag, an dem die Front dort steht, wo sie seit 1914 stand', 'Канун операции «Михаэль» — последний день, когда фронт стоит там, где стоял с 1914 года', 'Vísperas de la Operación Michael: el último día en que el frente está donde estaba desde 1914', '「米夏埃爾」作戰前夕——戰線停在1914年以來位置的最後一天', '“米夏埃尔”作战前夕——战线停在1914年以来位置的最后一天', 'La veille de l’opération Michael — le dernier jour où le front est là où il se tient depuis 1914', '미하엘 작전 전야 — 전선이 1914년 이래의 자리에 서 있는 마지막 날'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Cambrai', 'Saint-Quentin', 'Laon', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-04-05', cuts: [211, 220], note: L('Operation Michael has stopped short of Amiens after sixty kilometres — the deepest advance in the west since 1914', 'ミヒャエル作戦は60キロ進んでアミアン手前で止まる——1914年以来、西部で最大の前進', 'Die Operation Michael bleibt nach sechzig Kilometern vor Amiens stehen — der tiefste Vorstoß im Westen seit 1914', 'Операция «Михаэль» останавливается в шестидесяти километрах, не дойдя до Амьена, — самое глубокое продвижение на западе с 1914 года', 'La Operación Michael se detiene a las puertas de Amiens tras sesenta kilómetros: el avance más profundo en el oeste desde 1914', '「米夏埃爾」作戰推進六十公里後止於亞眠之前——1914年以來西線最深的推進', '“米夏埃尔”作战推进六十公里后止于亚眠之前——1914年以来西线最深的推进', 'L’opération Michael s’arrête à soixante kilomètres, devant Amiens — la plus profonde avancée à l’ouest depuis 1914', '미하엘 작전이 60킬로미터를 나아가 아미앵 앞에서 멈춘다 — 1914년 이래 서부에서 가장 깊은 진출'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Armentieres', 'Lens', 'Arras', 'Albert', 'Villers-Bretonneux', 'Montdidier', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-04-29', cuts: [211, 220], note: L('Georgette ends: the Lys salient reaches to within sight of Hazebrouck and Armentières is lost', 'ジョルジェット作戦終結——リス突出部はアズブルック目前まで達し、アルマンティエールが失われる', 'Georgette endet: der Lys-Bogen reicht bis in Sichtweite von Hazebrouck, Armentières ist verloren', '«Жоржетта» окончена: Лисский выступ вышел к Азбруку, Армантьер потерян', 'Georgette termina: el saliente del Lys llega a la vista de Hazebrouck y Armentières se pierde', '「喬潔特」作戰結束：利斯突出部逼近阿茲布魯克，阿爾芒蒂耶爾失守', '“乔洁特”作战结束：利斯突出部逼近阿兹布鲁克，阿尔芒蒂耶尔失守', 'Georgette s’achève : le saillant de la Lys arrive en vue d’Hazebrouck et Armentières est perdue', '조르제트 작전 종료 — 리스 돌출부가 아즈브루크를 눈앞에 두고, 아르망티에르가 상실된다'),
          pts: ['Nieuwpoort', 'Diksmuide', 'Ypres', 'Hazebrouck', 'Lens', 'Arras', 'Albert', 'Villers-Bretonneux', 'Montdidier', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-06-06', cuts: [211, 220], note: L('The deepest point of the German spring offensives', 'ドイツ軍春季攻勢の最深到達点', 'Der tiefste Punkt der deutschen Frühjahrsoffensiven', 'Наибольшее продвижение германских весенних наступлений', 'El punto más profundo de las ofensivas alemanas de primavera', '德軍春季攻勢推進最深之處', '德军春季攻势推进最深之处', 'Le point le plus profond des offensives allemandes du printemps', '독일군 춘계 공세의 최심 진출점'),
          /* ⚠ HAZEBROUCK, NOT ARMENTIÈRES. Armentières fell on 11 April in Georgette and stayed German
             until the Lys salient was given up in September, so it cannot be an anchor of the June line
             — the front stood west of it, before Hazebrouck. */
          pts: ['Nieuwpoort', 'Ypres', 'Hazebrouck', 'Arras', 'Albert', 'Montdidier', 'Compiegne', 'Chateau-Thierry', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-07-18', cuts: [211, 220], note: L('The counter-attack at Villers-Cotterêts opens the Second Marne — the last day the Germans hold ground they have taken this year', 'ヴィレル＝コトレの反攻で第二次マルヌ会戦が始まる——ドイツ軍が今年奪った土地を保つ最後の日', 'Der Gegenangriff bei Villers-Cotterêts eröffnet die zweite Marneschlacht — der letzte Tag, an dem die Deutschen das in diesem Jahr Gewonnene halten', 'Контрудар под Виллер-Котре открывает вторую битву на Марне — последний день, когда немцы удерживают взятое в этом году', 'El contraataque de Villers-Cotterêts abre la segunda batalla del Marne: el último día en que los alemanes conservan lo tomado este año', '維萊科特雷的反攻揭開第二次馬恩河戰役——德軍守住本年所得的最後一天', '维莱科特雷的反攻揭开第二次马恩河战役——德军守住本年所得的最后一天', 'La contre-attaque de Villers-Cotterêts ouvre la seconde bataille de la Marne — le dernier jour où les Allemands tiennent ce qu’ils ont pris cette année', '빌레르코트레의 반격으로 제2차 마른 전투가 시작된다 — 독일군이 올해 얻은 땅을 지키는 마지막 날'),
          pts: ['Nieuwpoort', 'Ypres', 'Hazebrouck', 'Arras', 'Albert', 'Montdidier', 'Compiegne', 'Chateau-Thierry', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-08-08', cuts: [211, 220], note: L('The Marne salient is gone and the Hundred Days open at Amiens — the black day of the German Army', 'マルヌ突出部は消え、アミアンで百日攻勢が始まる——ドイツ陸軍の「暗黒の日」', 'Der Marnebogen ist verschwunden und bei Amiens beginnen die Hundert Tage — der schwarze Tag des deutschen Heeres', 'Марнский выступ срезан, у Амьена начинаются Сто дней — чёрный день германской армии', 'El saliente del Marne ha desaparecido y los Cien Días comienzan en Amiens: el día negro del ejército alemán', '馬恩突出部消失，百日攻勢自亞眠展開——德國陸軍的「黑色之日」', '马恩突出部消失，百日攻势自亚眠展开——德国陆军的“黑色之日”', 'Le saillant de la Marne a disparu et les Cent-Jours s’ouvrent à Amiens — le jour noir de l’armée allemande', '마른 돌출부가 사라지고 아미앵에서 백일 공세가 시작된다 — 독일 육군의 “암흑의 날”'),
          pts: ['Nieuwpoort', 'Ypres', 'Hazebrouck', 'Arras', 'Albert', 'Villers-Bretonneux', 'Montdidier', 'Noyon', 'Soissons', 'Reims', 'Douaumont', 'Saint-Mihiel', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-09-12', cuts: [211, 220], note: L('The Saint-Mihiel salient is pinched out in a day — the first American army offensive of the war', 'サン＝ミエル突出部が1日で消える——アメリカ軍として最初の攻勢', 'Der Bogen von Saint-Mihiel wird an einem Tag abgeschnürt — die erste amerikanische Armeeoffensive des Krieges', 'Сен-Миельский выступ срезан за сутки — первое наступление американской армии в этой войне', 'El saliente de Saint-Mihiel se elimina en un día: la primera ofensiva de un ejército estadounidense en la guerra', '聖米耶爾突出部一日之內被削平——美軍在本戰爭中的首次軍級攻勢', '圣米耶尔突出部一日之内被削平——美军在本战争中的首次军级攻势', 'Le saillant de Saint-Mihiel est réduit en un jour — la première offensive d’armée américaine de la guerre', '생미이엘 돌출부가 하루 만에 제거된다 — 이 전쟁 최초의 미군 군단위 공세'),
          pts: ['Nieuwpoort', 'Ypres', 'Hazebrouck', 'Lens', 'Cambrai', 'Saint-Quentin', 'Laon', 'Reims', 'Douaumont', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-09-26', cuts: [211, 220], pts: ['Nieuwpoort', 'Ypres', 'Armentieres', 'Lens', 'Cambrai', 'Saint-Quentin', 'Laon', 'Reims', 'Douaumont', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-10-20', cuts: [211, 220], note: L('The Hindenburg Line is broken and the Belgian coast is free — the line is back on the Scheldt', 'ヒンデンブルク線は突破され、ベルギー沿岸は解放された——戦線はスヘルデ川まで戻る', 'Die Siegfriedstellung ist durchbrochen und die belgische Küste frei — die Linie steht wieder an der Schelde', 'Линия Гинденбурга прорвана, бельгийское побережье свободно — фронт снова на Шельде', 'La Línea Hindenburg está rota y la costa belga es libre: la línea vuelve al Escalda', '興登堡防線已被突破，比利時海岸解放——戰線退回斯海爾德河', '兴登堡防线已被突破，比利时海岸解放——战线退回斯海尔德河', 'La ligne Hindenburg est rompue et la côte belge est libre — le front est revenu sur l’Escaut', '힌덴부르크 선이 돌파되고 벨기에 해안이 해방된다 — 전선은 스헬더강으로 돌아온다'),
          /* ⚠ NOT FROM OSTEND. The coast was liberated on the 17th and the line by the 20th ran north–
             south along the Scheldt; quoting it from Ostend hooks the path east and then back west,
             and a hooked path puts Brussels — fifty kilometres behind the German line — under the
             Allies, because the nearest segment to it is the hook rather than the front. */
          pts: ['Ghent', 'Kortrijk', 'Valenciennes', 'Guise', 'Rethel', 'Douaumont', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
        { d: '1918-11-11', cuts: [211, 220], note: L('The line at 11:00 on 11 November 1918', '1918年11月11日11時の戦線', 'Die Linie um 11:00 Uhr am 11. November 1918', 'Линия на 11:00 11 ноября 1918 года', 'La línea a las 11:00 del 11 de noviembre de 1918', '1918年11月11日11時的戰線', '1918年11月11日11时的战线', 'La ligne à 11 h le 11 novembre 1918', '1918년 11월 11일 11시의 전선'),
          pts: ['Ghent', 'Mons', 'Charleroi', 'Namur', 'Sedan', 'Douaumont', 'Pont-a-Mousson', 'Luneville', 'Saint-Die', 'Thann', 'Pfetterhouse'] },
      ],
    },
    {
      id: 'east1',
      name: L('Eastern Front', '東部戦線', 'Ostfront', 'Восточный фронт', 'Frente Oriental', '東方戰線', '东方战线', 'Front de l’Est', '동부 전선'),
      left: 'CENTRAL', right: 'ALLIED',
      dates: [
        { d: '1914-09-12', cuts: [365, 300], note: L('Russian Poland holds; the Russians are deep in Galicia after Lemberg', 'ロシア領ポーランドは保持され、レンベルク会戦後ガリツィア深部までロシア軍が進出', 'Russisch-Polen hält; nach Lemberg stehen die Russen tief in Galizien', 'Русская Польша держится; после Львова русские глубоко в Галиции', 'La Polonia rusa resiste; tras Lemberg los rusos están en el fondo de Galitzia', '俄屬波蘭仍在，倫貝格會戰後俄軍深入加利西亞', '俄属波兰仍在，伦贝格会战后俄军深入加利西亚', 'La Pologne russe tient ; après Lemberg les Russes sont au fond de la Galicie', '러시아령 폴란드는 유지되고, 렘베르크 전투 후 러시아군이 갈리치아 깊숙이 진출'),
          pts: ['Memel', 'Kaunas', 'Grodno', 'Warsaw', 'Krakow', 'Tarnow', 'Przemysl', 'Chernivtsi'] },
        { d: '1914-12-15', cuts: [365, 300], note: L('Łódź has fallen and the winter line settles on the Bzura and the Rawka; Przemyśl is besieged behind the Russians', 'ウッチ陥落。冬の戦線はブズラ川・ラウカ川で固まり、プシェミシルはロシア軍の後方で包囲される', 'Łódź ist gefallen; die Winterlinie setzt sich an Bzura und Rawka fest, Przemyśl liegt hinter den Russen im Belagerungsring', 'Лодзь взята, зимняя линия встаёт на Бзуре и Равке; Перемышль осаждён в русском тылу', 'Łódź ha caído y la línea de invierno se fija en el Bzura y el Rawka; Przemyśl queda sitiada a espaldas de los rusos', '羅茲陷落，冬季戰線固定於布祖拉河與拉夫卡河，普熱梅希爾在俄軍後方被圍', '罗兹陷落，冬季战线固定于布祖拉河与拉夫卡河，普热梅希尔在俄军后方被围', 'Łódź est tombée et la ligne d’hiver se fixe sur la Bzura et la Rawka ; Przemyśl est assiégée derrière les Russes', '우치가 함락되고 겨울 전선이 브주라·라브카 강에 자리잡는다. 프셰미실은 러시아군 후방에서 포위된다'),
          pts: ['Memel', 'Kaunas', 'Grodno', 'Warsaw', 'Krakow', 'Gorlice', 'Przemysl', 'Chernivtsi'] },
        { d: '1915-05-02', cuts: [365, 300], pts: ['Memel', 'Kaunas', 'Grodno', 'Warsaw', 'Krakow', 'Gorlice', 'Przemysl', 'Chernivtsi'] },
        { d: '1915-08-05', cuts: [365], note: L('Warsaw is abandoned — the Great Retreat is at its height and Brest-Litovsk and Kovno will go this month', 'ワルシャワ放棄——大撤退は最中で、ブレスト＝リトフスクとコヴノも今月中に失われる', 'Warschau wird geräumt — die Große Rückzug steht auf dem Höhepunkt, Brest-Litowsk und Kowno fallen noch in diesem Monat', 'Варшава оставлена — Великое отступление в разгаре, Брест-Литовск и Ковно падут в этом же месяце', 'Varsovia es abandonada: la Gran Retirada está en su apogeo y Brest-Litovsk y Kovno caerán este mes', '華沙棄守——大撤退進入高潮，布列斯特—立陶夫斯克與科夫諾將於本月失守', '华沙弃守——大撤退进入高潮，布列斯特—立托夫斯克与科夫诺将于本月失守', 'Varsovie est abandonnée — la Grande Retraite est à son comble, Brest-Litovsk et Kovno tomberont ce mois-ci', '바르샤바 포기 — 대후퇴가 절정에 이르고, 브레스트-리토프스크와 코브노도 이달 안에 상실된다'),
          pts: ['Riga', 'Kaunas', 'Bialystok', 'Brest', 'Kovel', 'Lutsk', 'Ternopil', 'Chernivtsi'] },
        { d: '1915-09-19', cuts: [365], note: L('After the Great Retreat — Russian Poland, Lithuania and Courland are lost', '大撤退の後——ロシア領ポーランド・リトアニア・クールラントを喪失', 'Nach dem Großen Rückzug — Russisch-Polen, Litauen und Kurland sind verloren', 'После Великого отступления — Русская Польша, Литва и Курляндия потеряны', 'Tras la Gran Retirada: se pierden la Polonia rusa, Lituania y Curlandia', '大撤退之後——俄屬波蘭、立陶宛與庫爾蘭喪失', '大撤退之后——俄属波兰、立陶宛与库尔兰丧失', 'Après la Grande Retraite — la Pologne russe, la Lituanie et la Courlande sont perdues', '대후퇴 이후 — 러시아령 폴란드·리투아니아·쿠를란트 상실'),
          pts: ['Riga', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Rivne', 'Ternopil', 'Chernivtsi'] },
        { d: '1916-06-08', cuts: [365], note: L('Lutsk falls on the fourth day of the Brusilov offensive — the widest breakthrough on any front since 1914', 'ブルシーロフ攻勢4日目にルーツク陥落——1914年以来、どの戦線でも最大の突破', 'Luzk fällt am vierten Tag der Brussilow-Offensive — der breiteste Durchbruch an irgendeiner Front seit 1914', 'Луцк взят на четвёртый день Брусиловского прорыва — самый широкий прорыв на любом фронте с 1914 года', 'Lutsk cae al cuarto día de la ofensiva Brusílov: la brecha más ancha en cualquier frente desde 1914', '布魯西洛夫攻勢第四日盧茨克陷落——1914年以來各戰線最寬的突破', '布鲁西洛夫攻势第四日卢茨克陷落——1914年以来各战线最宽的突破', 'Loutsk tombe au quatrième jour de l’offensive Broussilov — la plus large percée sur un front depuis 1914', '브루실로프 공세 나흘째에 루츠크가 함락된다 — 1914년 이래 어느 전선에서도 가장 넓은 돌파'),
          pts: ['Riga', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Lutsk', 'Ternopil', 'Chernivtsi'] },
        { d: '1916-09-20', cuts: [365], note: L('After the Brusilov Offensive', 'ブルシーロフ攻勢の後', 'Nach der Brussilow-Offensive', 'После Брусиловского прорыва', 'Tras la Ofensiva Brusílov', '布魯西洛夫攻勢之後', '布鲁西洛夫攻势之后', 'Après l’offensive Broussilov', '브루실로프 공세 이후'),
          pts: ['Riga', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Lutsk', 'Ternopil', 'Chernivtsi'] },
        { d: '1917-07-25', cuts: [365], note: L('The Kerensky offensive has collapsed; the counter-attack has taken back Tarnopol and everything Brusilov won in Galicia', 'ケレンスキー攻勢は崩壊。反攻でタルノポリと、ブルシーロフがガリツィアで得た全てが失われる', 'Die Kerenski-Offensive ist zusammengebrochen; der Gegenstoß nimmt Tarnopol und alles zurück, was Brussilow in Galizien gewann', 'Наступление Керенского провалилось; контрудар вернул Тарнополь и всё, что Брусилов взял в Галиции', 'La ofensiva de Kérenski se ha hundido; el contraataque ha recuperado Tarnópol y todo lo que Brusílov ganó en Galitzia', '克倫斯基攻勢崩潰，反攻奪回塔爾諾波爾及布魯西洛夫在加利西亞取得的一切', '克伦斯基攻势崩溃，反攻夺回塔尔诺波尔及布鲁西洛夫在加利西亚取得的一切', 'L’offensive Kerenski s’est effondrée ; la contre-attaque a repris Tarnopol et tout ce que Broussilov avait gagné en Galicie', '케렌스키 공세가 붕괴하고, 반격이 타르노폴과 브루실로프가 갈리치아에서 얻은 모든 것을 되찾는다'),
          pts: ['Riga', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Rivne', 'Ternopil', 'Chernivtsi'] },
        { d: '1917-09-03', cuts: [365], pts: ['Riga', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Rivne', 'Ternopil', 'Chernivtsi'] },
        { d: '1917-09-06', cuts: [365], note: L('Riga has fallen; the Russians hold on the line of Wenden', 'リガ陥落。ロシア軍はツェーシス（ヴェンデン）の線で踏みとどまる', 'Riga ist gefallen; die Russen halten auf der Linie Wenden', 'Рига взята; русские держатся на линии Вендена', 'Riga ha caído; los rusos resisten en la línea de Wenden', '里加陷落，俄軍守在采西斯（溫登）一線', '里加陷落，俄军守在采西斯（温登）一线', 'Riga est tombée ; les Russes tiennent sur la ligne de Wenden', '리가가 함락되고, 러시아군은 벤덴(체시스) 선에서 저지한다'),
          pts: ['Cesis', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Rivne', 'Ternopil', 'Chernivtsi'] },
        { d: '1917-12-15', cuts: [365], note: L('The armistice of Brest-Litovsk stops the fighting along the whole of the Eastern Front', 'ブレスト＝リトフスク休戦により、東部戦線全域で戦闘が停止する', 'Der Waffenstillstand von Brest-Litowsk beendet die Kämpfe auf der ganzen Ostfront', 'Брест-Литовское перемирие останавливает бои по всему Восточному фронту', 'El armisticio de Brest-Litovsk detiene los combates en todo el Frente Oriental', '布列斯特—立陶夫斯克停戰使整條東線停火', '布列斯特—立托夫斯克停战使整条东线停火', 'L’armistice de Brest-Litovsk arrête les combats sur tout le front de l’Est', '브레스트-리토프스크 휴전으로 동부 전선 전역의 전투가 멈춘다'),
          pts: ['Cesis', 'Daugavpils', 'Baranavichy', 'Pinsk', 'Rivne', 'Ternopil', 'Chernivtsi'] },
        { d: '1918-02-24', cuts: [365], note: L('Operation Faustschlag — eleven days of unopposed advance after the Soviet delegation walked out', 'ファウストシュラーク作戦——ソヴィエト代表団の退席後、11日間の無抵抗の前進', 'Unternehmen Faustschlag — elf Tage ungehinderten Vormarsches, nachdem die sowjetische Delegation abgereist war', 'Операция «Фаустшлаг» — одиннадцать дней беспрепятственного продвижения после ухода советской делегации', 'Operación Faustschlag: once días de avance sin oposición tras la retirada de la delegación soviética', '「鐵拳」作戰——蘇俄代表團退席後，十一天無抵抗的推進', '“铁拳”作战——苏俄代表团退席后，十一天无抵抗的推进', 'Opération Faustschlag — onze jours d’avance sans opposition après le départ de la délégation soviétique', '파우스트슐라크 작전 — 소비에트 대표단 퇴장 후 11일간의 무저항 진격'),
          pts: ['Narva', 'Pskov', 'Orsha', 'Mogilev', 'Gomel', 'Kyiv', 'Kherson'] },
        { d: '1918-03-03', cuts: [365], right: 'NEUTRAL', note: L('The Brest-Litovsk line — Russia leaves the war', 'ブレスト＝リトフスク条約の線——ロシアが戦争から離脱', 'Die Linie von Brest-Litowsk — Russland scheidet aus dem Krieg aus', 'Линия Брест-Литовска — Россия выходит из войны', 'La línea de Brest-Litovsk: Rusia abandona la guerra', '布列斯特—立陶夫斯克線——俄國退出戰爭', '布列斯特—立托夫斯克线——俄国退出战争', 'La ligne de Brest-Litovsk — la Russie quitte la guerre', '브레스트-리토프스크 선 — 러시아가 전쟁에서 이탈'),
          pts: ['Narva', 'Pskov', 'Orsha', 'Mogilev', 'Gomel', 'Kyiv', 'Kherson'] },
      ],
    },
    {
      id: 'italian1',
      name: L('Italian Front', 'イタリア戦線', 'Italienfront', 'Итальянский фронт', 'Frente italiano', '義大利戰線', '意大利战线', 'Front italien', '이탈리아 전선'),
      left: 'ALLIED', right: 'CENTRAL',
      dates: [
        { d: '1915-06-23', cuts: [300], pts: ['Stelvio Pass', 'Tonale Pass', 'Asiago', 'Cortina', 'Tolmezzo', 'Kobarid', 'Gorizia', 'Monfalcone'] },
        { d: '1916-06-15', cuts: [300], note: L('The Strafexpedition has driven onto the Asiago plateau — the only Austro-Hungarian gain of the whole front', '「懲罰遠征」がアジアーゴ高原に達する——この戦線でオーストリア＝ハンガリーが得た唯一の前進', 'Die Strafexpedition ist auf die Hochebene von Asiago vorgedrungen — der einzige österreichisch-ungarische Geländegewinn dieser Front', '«Карательная экспедиция» вышла на плато Азиаго — единственный австро-венгерский успех на этом фронте', 'La Strafexpedition ha llegado a la meseta de Asiago: la única ganancia austrohúngara de todo el frente', '「懲罰遠征」推進至阿夏戈高原——奧匈在此戰線唯一的所得', '“惩罚远征”推进至阿夏戈高原——奥匈在此战线唯一的所得', 'La Strafexpedition a débouché sur le plateau d’Asiago — le seul gain austro-hongrois de tout ce front', '“징벌 원정”이 아시아고 고원에 도달한다 — 이 전선에서 오스트리아·헝가리가 얻은 유일한 전진'),
          pts: ['Stelvio Pass', 'Tonale Pass', 'Asiago', 'Cortina', 'Tolmezzo', 'Kobarid', 'Gorizia', 'Monfalcone'] },
        { d: '1916-08-09', cuts: [300], note: L('Gorizia falls in the Sixth Isonzo — eleven more battles will be fought for the next few kilometres', '第六次イゾンツォでゴリツィア陥落——次の数キロのために、なお11回の会戦が戦われる', 'Görz fällt in der sechsten Isonzoschlacht — um die nächsten Kilometer werden noch elf Schlachten geschlagen', 'Гориция взята в шестом сражении на Изонцо — за следующие несколько километров будет дано ещё одиннадцать сражений', 'Gorizia cae en la sexta batalla del Isonzo: por los siguientes kilómetros se librarán once batallas más', '第六次伊松佐戰役中戈里齊亞陷落——為了接下來的幾公里還將打十一場會戰', '第六次伊松佐战役中戈里齐亚陷落——为了接下来的几公里还将打十一场会战', 'Gorizia tombe lors de la sixième bataille de l’Isonzo — onze batailles de plus seront livrées pour les kilomètres suivants', '제6차 이손초 전투에서 고리치아가 함락된다 — 다음 몇 킬로미터를 위해 열한 번의 회전이 더 벌어진다'),
          pts: ['Stelvio Pass', 'Tonale Pass', 'Asiago', 'Cortina', 'Tolmezzo', 'Kobarid', 'Gorizia', 'Monfalcone'] },
        { d: '1917-08-19', cuts: [300], note: L('The Eleventh Isonzo takes the Bainsizza plateau — and empties the Italian army for what comes in October', '第十一次イゾンツォでバインジッツァ高原を奪うが、10月に来るものへ向けてイタリア軍は消耗し尽くす', 'Die elfte Isonzoschlacht nimmt die Hochfläche von Bainsizza — und erschöpft das italienische Heer für das, was im Oktober kommt', 'Одиннадцатое сражение на Изонцо берёт плато Байнзицца — и обескровливает итальянскую армию перед октябрём', 'La undécima batalla del Isonzo toma la meseta de Bainsizza, y vacía al ejército italiano ante lo que llegará en octubre', '第十一次伊松佐戰役奪取拜恩西扎高原，卻為十月將至之事耗盡了義軍', '第十一次伊松佐战役夺取拜恩西扎高原，却为十月将至之事耗尽了意军', 'La onzième bataille de l’Isonzo prend le plateau de la Bainsizza — et vide l’armée italienne avant ce qui vient en octobre', '제11차 이손초 전투가 바인시차 고원을 얻지만, 10월에 닥칠 일을 앞두고 이탈리아군을 소진시킨다'),
          pts: ['Stelvio Pass', 'Tonale Pass', 'Asiago', 'Cortina', 'Tolmezzo', 'Kobarid', 'Gorizia', 'Monfalcone'] },
        { d: '1917-09-12', cuts: [300], pts: ['Stelvio Pass', 'Tonale Pass', 'Asiago', 'Cortina', 'Tolmezzo', 'Kobarid', 'Gorizia', 'Monfalcone'] },
        { d: '1917-11-12', cuts: [325], note: L('After Caporetto — the Italians hold on the Piave', 'カポレットの後——イタリア軍はピアーヴェ川で踏みとどまる', 'Nach Karfreit — die Italiener halten am Piave', 'После Капоретто — итальянцы держатся на Пьяве', 'Tras Caporetto: los italianos resisten en el Piave', '卡波雷托之後——義軍守住皮亞韋河', '卡波雷托之后——意军守住皮亚韦河', 'Après Caporetto — les Italiens tiennent sur la Piave', '카포레토 이후 — 이탈리아군이 피아베강에서 저지'),
          pts: ['Tonale Pass', 'Rovereto', 'Asiago', 'Feltre', 'Montello', 'Cortellazzo'] },
        { d: '1918-06-24', cuts: [325], pts: ['Tonale Pass', 'Rovereto', 'Asiago', 'Feltre', 'Montello', 'Cortellazzo'] },
        { d: '1918-10-24', cuts: [325], note: L('Vittorio Veneto opens on the anniversary of Caporetto, on the same line the Piave gave back', 'カポレットの記念日に、ピアーヴェが取り戻したその線からヴィットリオ・ヴェネトが始まる', 'Vittorio Veneto beginnt am Jahrestag von Karfreit, auf derselben Linie, die der Piave zurückgab', 'Витторио-Венето начинается в годовщину Капоретто, на той же линии, что вернула Пьява', 'Vittorio Veneto comienza en el aniversario de Caporetto, sobre la misma línea que devolvió el Piave', '維托里奧·韋內托在卡波雷托週年之日展開，就在皮亞韋河守回的同一條線上', '维托里奥·韦内托在卡波雷托周年之日展开，就在皮亚韦河守回的同一条线上', 'Vittorio Veneto s’ouvre à l’anniversaire de Caporetto, sur la ligne même que la Piave a rendue', '카포레토 1주년에, 피아베가 되돌려준 바로 그 선에서 비토리오 베네토가 시작된다'),
          pts: ['Tonale Pass', 'Rovereto', 'Asiago', 'Feltre', 'Montello', 'Cortellazzo'] },
        { d: '1918-11-02', cuts: [300], note: L('Vittorio Veneto — the Austro-Hungarian front has collapsed', 'ヴィットリオ・ヴェネト——オーストリア＝ハンガリー戦線の崩壊', 'Vittorio Veneto — die österreichisch-ungarische Front ist zusammengebrochen', 'Витторио-Венето — австро-венгерский фронт рухнул', 'Vittorio Veneto: el frente austrohúngaro se ha derrumbado', '維托里奧·韋內托——奧匈戰線崩潰', '维托里奥·韦内托——奥匈战线崩溃', 'Vittorio Veneto — le front austro-hongrois s’est effondré', '비토리오 베네토 — 오스트리아·헝가리 전선 붕괴'),
          pts: ['Tonale Pass', 'Trento', 'Cortina', 'Udine', 'Trieste'] },
      ],
    },
    {
      id: 'salonika', until: '1918-09-30',
      name: L('Macedonian (Salonika) Front', 'マケドニア（サロニカ）戦線', 'Mazedonienfront (Saloniki)', 'Македонский (Салоникский) фронт', 'Frente de Macedonia (Salónica)', '馬其頓（薩洛尼卡）戰線', '马其顿（萨洛尼卡）战线', 'Front de Macédoine (Salonique)', '마케도니아(살로니카) 전선'),
      left: 'ALLIED', right: 'CENTRAL',
      dates: [
        { d: '1916-08-17', cuts: [350, 339], note: L('The Bulgarian offensive takes Florina in the west and crosses the Struma in the east', 'ブルガリア軍の攻勢が西でフロリナを奪い、東ではストルマ川を渡る', 'Die bulgarische Offensive nimmt im Westen Florina und überschreitet im Osten den Struma', 'Болгарское наступление берёт Флорину на западе и переходит Струму на востоке', 'La ofensiva búlgara toma Florina al oeste y cruza el Struma al este', '保加利亞攻勢西取弗洛里納，東渡斯特魯馬河', '保加利亚攻势西取弗洛里纳，东渡斯特鲁马河', 'L’offensive bulgare prend Florina à l’ouest et franchit le Strymon à l’est', '불가리아군 공세가 서쪽에서 플로리나를 빼앗고 동쪽에서 스트루마강을 건넌다'),
          pts: ['Vlore', 'Florina', 'Doiran', 'Struma'] },
        { d: '1916-11-19', cuts: [350, 339], note: L('After the Allies retook Monastir', '連合国がモナスティルを奪回した後', 'Nachdem die Alliierten Monastir zurückerobert hatten', 'После взятия союзниками Монастира', 'Tras la reconquista aliada de Monastir', '協約國奪回莫納斯提爾之後', '协约国夺回莫纳斯提尔之后', 'Après la reprise de Monastir par les Alliés', '연합군이 모나스티르를 탈환한 뒤'),
          pts: ['Vlore', 'Bitola', 'Doiran', 'Struma'] },
        { d: '1918-09-15', cuts: [350, 339], note: L('The Vardar offensive opens at Dobro Pole — the front that stood for two years will be gone in a fortnight', 'ドブロ・ポレでヴァルダル攻勢が始まる——2年間動かなかった戦線が2週間で消える', 'Die Vardar-Offensive beginnt bei Dobro Pole — die zwei Jahre unbewegte Front wird in vierzehn Tagen verschwunden sein', 'Вардарское наступление начинается у Добро Поле — простоявший два года фронт исчезнет за две недели', 'La ofensiva del Vardar comienza en Dobro Pole: el frente que resistió dos años desaparecerá en quince días', '瓦爾達爾攻勢自多布羅波列展開——僵持兩年的戰線將在兩週內消失', '瓦尔达尔攻势自多布罗波列展开——僵持两年的战线将在两周内消失', 'L’offensive du Vardar s’ouvre à Dobro Polje — le front immobile depuis deux ans aura disparu en quinze jours', '도브로폴레에서 바르다르 공세가 시작된다 — 2년간 굳어 있던 전선이 2주 만에 사라진다'),
          pts: ['Vlore', 'Bitola', 'Doiran', 'Struma'] },
        { d: '1918-09-29', cuts: [350, 339], pts: ['Vlore', 'Bitola', 'Doiran', 'Struma'] },
      ],
    },
    {
      id: 'palestine',
      name: L('Sinai and Palestine Front', 'シナイ・パレスチナ戦線', 'Sinai- und Palästinafront', 'Синайско-Палестинский фронт', 'Frente del Sinaí y Palestina', '西奈與巴勒斯坦戰線', '西奈与巴勒斯坦战线', 'Front du Sinaï et de la Palestine', '시나이·팔레스타인 전선'),
      left: 'ALLIED', right: 'CENTRAL',
      dates: [
        /* ⚠ THE FIRST TWO CUT EGYPT, NOT THE OTTOMAN EMPIRE. Sinai was Egyptian ground, and the fight
           of 1916 was for it: the Ottoman advance on the canal, then the British march back across
           the peninsula. The front only reaches Ottoman territory at Rafah, in January 1917. */
        { d: '1916-08-05', cuts: [651], note: L('Romani — the Ottoman advance on the Suez Canal is stopped, and the direction of the campaign reverses for good', 'ロマニ——スエズ運河へのオスマン軍の進撃が阻止され、戦役の向きが以後逆転する', 'Romani — der osmanische Vorstoß auf den Suezkanal wird gestoppt, und die Richtung des Feldzugs kehrt sich endgültig um', 'Романи — османское наступление на Суэцкий канал остановлено, и направление кампании меняется окончательно', 'Romani: se detiene el avance otomano sobre el canal de Suez y la campaña invierte su sentido para siempre', '羅馬尼——鄂圖曼對蘇伊士運河的推進被阻止，戰役方向自此逆轉', '罗马尼——奥斯曼对苏伊士运河的推进被阻止，战役方向自此逆转', 'Romani — l’avance ottomane sur le canal de Suez est stoppée et le sens de la campagne s’inverse définitivement', '로마니 — 수에즈 운하를 향한 오스만군의 진격이 저지되고, 전역의 방향이 이후 뒤바뀐다'),
          pts: ['Romani', 'Suez'] },
        { d: '1916-12-21', cuts: [651], note: L('El Arish is taken and the railway and water pipeline have crossed Sinai behind it', 'エル・アリーシュ占領。鉄道と送水管はその後方でシナイを横断し終えている', 'El Arisch ist genommen; Bahn und Wasserleitung haben den Sinai hinter ihr durchquert', 'Эль-Ариш взят; за ним железная дорога и водопровод уже пересекли Синай', 'El Arish es tomada y el ferrocarril y el oleoducto de agua han cruzado el Sinaí tras ella', '攻下阿里什，鐵路與輸水管已在其後方橫越西奈', '攻下阿里什，铁路与输水管已在其后方横越西奈', 'El-Arich est prise et le chemin de fer et la conduite d’eau ont traversé le Sinaï derrière elle', '엘아리시 점령. 그 후방으로 철도와 송수관이 이미 시나이를 횡단했다'),
          pts: ['El Arish', 'Aqaba'] },
        { d: '1917-03-26', cuts: [640], note: L('The Gaza–Beersheba line', 'ガザ＝ベエルシェバ線', 'Die Linie Gaza–Beerscheba', 'Линия Газа — Беэр-Шева', 'La línea Gaza–Beerseba', '加薩—貝爾謝巴線', '加沙—贝尔谢巴线', 'La ligne Gaza–Bersabée', '가자–브엘셰바 선'),
          pts: ['Gaza', 'Beersheba'] },
        { d: '1917-12-11', cuts: [640], note: L('Jerusalem has fallen', 'エルサレム陥落', 'Jerusalem ist gefallen', 'Иерусалим взят', 'Jerusalén ha caído', '耶路撒冷陷落', '耶路撒冷陷落', 'Jérusalem est tombée', '예루살렘 함락'),
          pts: ['Jaffa', 'Jerusalem'] },
        { d: '1918-09-25', cuts: [640], note: L('Megiddo has broken the Ottoman front in a single day; Haifa, Nazareth and Deraa are gone', 'メギドは1日でオスマン戦線を破った。ハイファ・ナザレ・ダルアーが失われる', 'Megiddo hat die osmanische Front an einem Tag zerbrochen; Haifa, Nazareth und Dera’a sind verloren', 'Мегиддо сломало османский фронт за один день; Хайфа, Назарет и Дераа потеряны', 'Meguido ha roto el frente otomano en un solo día; Haifa, Nazaret y Deraa han caído', '米吉多一日之內擊破鄂圖曼戰線，海法、拿撒勒、德拉相繼失守', '米吉多一日之内击破奥斯曼战线，海法、拿撒勒、德拉相继失守', 'Megiddo a brisé le front ottoman en un seul jour ; Haïfa, Nazareth et Deraa sont perdues', '메기도가 하루 만에 오스만 전선을 무너뜨린다 — 하이파·나사렛·다라가 상실된다'),
          pts: ['Haifa', 'Tiberias', 'Deraa'] },
        { d: '1918-10-01', cuts: [640], note: L('After Megiddo — Damascus taken', 'メギドの後——ダマスカス占領', 'Nach Megiddo — Damaskus eingenommen', 'После Мегиддо — взят Дамаск', 'Tras Meguido: Damasco tomado', '米吉多之後——攻下大馬士革', '米吉多之后——攻下大马士革', 'Après Megiddo — Damas prise', '메기도 이후 — 다마스쿠스 점령'),
          pts: ['Beirut', 'Damascus'] },
        { d: '1918-10-26', cuts: [640], note: L('Aleppo has fallen; four days later Mudros ends the Ottoman war', 'アレッポ陥落。4日後のムドロス休戦がオスマン帝国の戦争を終わらせる', 'Aleppo ist gefallen; vier Tage später beendet Mudros den osmanischen Krieg', 'Алеппо взят; через четыре дня Мудросское перемирие заканчивает османскую войну', 'Alepo ha caído; cuatro días después Mudros pone fin a la guerra otomana', '阿勒坡陷落，四日後的穆德羅斯停戰結束了鄂圖曼的戰爭', '阿勒颇陷落，四日后的穆德罗斯停战结束了奥斯曼的战争', 'Alep est tombée ; quatre jours plus tard Moudros met fin à la guerre ottomane', '알레포가 함락되고, 나흘 뒤 무드로스 휴전이 오스만의 전쟁을 끝낸다'),
          pts: ['Iskenderun', 'Aleppo'] },
      ],
    },

    /* ══ #R381 — THE FOUR THEATRES THE RECORD ALREADY NAMED PLACES FOR AND NEVER DREW ═══════════
       scripts/wars/places.mjs shipped with Erzurum, Trabzon, Van, Kars and Batum; with Basra, Kut,
       Baghdad, Mosul and Kirkuk; with Belgrade, Niš and Skopje; with Bucharest, Iaşi and Constanţa.
       Not one of them was quoted by a line. A campaign the gazetteer is ready for and the record is
       silent about is not a smaller claim — it is a map on which Serbia is untouched through 1914,
       the Ottoman Empire is whole from the Caucasus to the Gulf, and Romania is one colour for two
       years. Each of the four below is drawn only for the days a position can be quoted, and each
       ends with `until` on the day its army left the war. ══════════════════════════════════════ */
    {
      id: 'serbia14',
      name: L('Serbian Front (1914)', 'セルビア戦線（1914年）', 'Serbische Front (1914)', 'Сербский фронт (1914)', 'Frente serbio (1914)', '塞爾維亞戰線（1914）', '塞尔维亚战线（1914）', 'Front serbe (1914)', '세르비아 전선(1914)'),
      left: 'CENTRAL', right: 'ALLIED',
      until: '1914-12-16',
      dates: [
        { d: '1914-09-08', cuts: [340], note: L('The Battle of the Drina — the second Austro-Hungarian invasion digs in along the river and in the Mačva', 'ドリナ川の戦い——第二次オーストリア＝ハンガリー侵攻が川沿いとマチュヴァ地方で塹壕に入る', 'Die Schlacht an der Drina — die zweite österreichisch-ungarische Invasion gräbt sich am Fluss und in der Mačva ein', 'Битва на Дрине — второе австро-венгерское вторжение закрепляется по реке и в Мачве', 'La batalla del Drina: la segunda invasión austrohúngara se atrinchera junto al río y en la Mačva', '德里納河戰役——第二次奧匈入侵沿河與馬奇瓦地區掘壕固守', '德里纳河战役——第二次奥匈入侵沿河与马奇瓦地区掘壕固守', 'La bataille de la Drina — la deuxième invasion austro-hongroise s’enterre le long de la rivière et dans la Mačva', '드리나강 전투 — 제2차 오스트리아·헝가리 침공이 강변과 마치바 지방에서 참호를 판다'),
          pts: ['Sabac', 'Loznica', 'Krupanj', 'Ljubovija', 'Bajina Basta'] },
        { d: '1914-12-02', cuts: [340], note: L('Belgrade has fallen and the Kolubara line is the deepest the invasion will reach', 'ベオグラード陥落。コルバラ線が、この侵攻が到達する最深の線となる', 'Belgrad ist gefallen, und die Kolubara-Linie ist das Tiefste, was die Invasion erreichen wird', 'Белград взят, и Колубарская линия — предел, которого достигнет вторжение', 'Belgrado ha caído y la línea del Kolubara es lo más lejos que llegará la invasión', '貝爾格勒陷落，科盧巴拉一線是此次入侵所能到達的最深處', '贝尔格莱德陷落，科卢巴拉一线是此次入侵所能到达的最深处', 'Belgrade est tombée et la ligne de la Kolubara est le point le plus profond que l’invasion atteindra', '베오그라드가 함락되고, 콜루바라 선이 이 침공이 도달하는 최심선이 된다'),
          /* ⚠ BELGRADE IS AN ANCHOR BECAUSE IT FELL ON THIS DAY. The line quoted before it — Obrenovac
             southward — leaves the city on the Serbian side, which was true on 30 November and false
             on 2 December; a front that runs THROUGH Belgrade says neither, which is what the record
             says of a city being fought for. */
          pts: ['Belgrade', 'Lazarevac', 'Gornji Milanovac', 'Uzice'] },
      ],
    },
    {
      id: 'caucasus',
      name: L('Caucasus Front', 'コーカサス戦線', 'Kaukasusfront', 'Кавказский фронт', 'Frente del Cáucaso', '高加索戰線', '高加索战线', 'Front du Caucase', '캅카스 전선'),
      /* ⚠ WEST IS THE OTTOMAN SIDE HERE, WHICH IS THE OPPOSITE OF EVERY OTHER FRONT IN THIS FILE.
         These lines are quoted from the Black Sea coast SOUTHWARD down eastern Anatolia, and the
         Russians came from the east — so `left` (the western side, for a line listed north to south)
         is CENTRAL. Authored the other way round it drew perfectly and put Erzurum, Aleppo, Gaza and
         Jerusalem under the Russian army; the self-audit below is what said so. */
      left: 'CENTRAL', right: 'ALLIED',
      until: '1918-04-26',
      dates: [
        /* ⚠ THE FIRST LINE CUTS RUSSIA, BECAUSE IN DECEMBER 1914 THE FIGHTING WAS ON RUSSIAN GROUND.
           Enver's Third Army crossed the 1878 frontier at Ardahan and Sarıkamış; it was destroyed
           there, and every line after this one is inside the Ottoman Empire. */
        { d: '1914-12-25', cuts: [365], note: L('Sarıkamış — the Ottoman Third Army is over the frontier and about to be destroyed by the winter', 'サルカムシュ——オスマン第3軍は国境を越えており、冬によって壊滅する寸前にある', 'Sarıkamış — die osmanische 3. Armee steht jenseits der Grenze und wird gleich vom Winter vernichtet', 'Сарыкамыш — османская 3-я армия перешла границу и вот-вот будет уничтожена зимой', 'Sarıkamış: el Tercer Ejército otomano ha cruzado la frontera y está a punto de ser destruido por el invierno', '薩勒卡默什——鄂圖曼第三軍越過邊界，即將被寒冬摧毀', '萨勒卡默什——奥斯曼第三军越过边界，即将被寒冬摧毁', 'Sarıkamış — la IIIᵉ armée ottomane a franchi la frontière et va être détruite par l’hiver', '사르카므시 — 오스만 제3군이 국경을 넘었고, 곧 겨울에 의해 궤멸된다'),
          pts: ['Hopa', 'Ardahan', 'Sarikamis', 'Kagizman', 'Igdir'] },
        { d: '1916-02-16', cuts: [640], note: L('Erzurum has fallen — the fortress the whole Ottoman east was built around', 'エルズルム陥落——オスマン帝国東部全体がその周りに築かれていた要塞', 'Erzurum ist gefallen — die Festung, um die der ganze osmanische Osten gebaut war', 'Эрзурум взят — крепость, вокруг которой был выстроен весь османский восток', 'Erzurum ha caído: la fortaleza en torno a la cual se construyó todo el oriente otomano', '埃爾祖魯姆陷落——鄂圖曼整個東部賴以構築的要塞', '埃尔祖鲁姆陷落——奥斯曼整个东部赖以构筑的要塞', 'Erzeroum est tombée — la forteresse autour de laquelle tout l’Orient ottoman était bâti', '에르주룸 함락 — 오스만 동부 전체가 그 주위에 세워졌던 요새'),
          pts: ['Of', 'Bayburt', 'Mus', 'Bitlis', 'Van'] },
        { d: '1916-07-25', cuts: [640], note: L('Erzincan is taken: the Russian high-water mark, and the last Russian offensive of this war', 'エルズィンジャン占領——ロシア軍の最大進出点であり、この戦争で最後のロシア軍攻勢', 'Erzincan wird genommen: der weiteste russische Vorstoß und die letzte russische Offensive dieses Krieges', 'Взят Эрзинджан: предел русского продвижения и последнее русское наступление этой войны', 'Erzincan es tomada: el punto más avanzado ruso y la última ofensiva rusa de esta guerra', '攻下埃爾津詹：俄軍推進的最遠點，也是此戰最後一次俄軍攻勢', '攻下埃尔津詹：俄军推进的最远点，也是此战最后一次俄军攻势', 'Erzincan est prise : le point extrême de l’avance russe et la dernière offensive russe de cette guerre', '에르진잔 점령 — 러시아군 최대 진출점이자, 이 전쟁 마지막 러시아군 공세'),
          pts: ['Tirebolu', 'Erzincan', 'Mus', 'Bitlis', 'Van', 'Rowanduz'] },
        { d: '1917-12-18', cuts: [640], note: L('The Armistice of Erzincan freezes a line no Russian army is left to hold', 'エルズィンジャン休戦は、もはや守るロシア軍のいない線を凍結する', 'Der Waffenstillstand von Erzincan friert eine Linie ein, die keine russische Armee mehr hält', 'Эрзинджанское перемирие замораживает линию, которую больше некому держать', 'El armisticio de Erzincan congela una línea que ya no queda ejército ruso para sostener', '埃爾津詹停戰凍結了一條已無俄軍可守的戰線', '埃尔津詹停战冻结了一条已无俄军可守的战线', 'L’armistice d’Erzincan gèle une ligne qu’aucune armée russe ne tient plus', '에르진잔 휴전이, 지킬 러시아군이 남아 있지 않은 선을 동결한다'),
          pts: ['Tirebolu', 'Erzincan', 'Mus', 'Bitlis', 'Van', 'Rowanduz'] },
        { d: '1918-03-14', cuts: [640], note: L('The Ottomans walk back to the 1914 frontier as the Russian army dissolves; Brest-Litovsk hands them Kars, Ardahan and Batum', 'ロシア軍の解体とともにオスマン軍は1914年の国境まで戻り、ブレスト＝リトフスクがカルス・アルダハン・バトゥムを与える', 'Die Osmanen gehen zur Grenze von 1914 zurück, während die russische Armee zerfällt; Brest-Litowsk gibt ihnen Kars, Ardahan und Batum', 'Османы возвращаются к границе 1914 года по мере распада русской армии; Брест-Литовск отдаёт им Карс, Ардаган и Батум', 'Los otomanos regresan a la frontera de 1914 mientras el ejército ruso se disuelve; Brest-Litovsk les entrega Kars, Ardahan y Batum', '隨著俄軍瓦解，鄂圖曼軍走回1914年邊界；布列斯特條約將卡爾斯、阿爾達漢、巴統交予他們', '随着俄军瓦解，奥斯曼军走回1914年边界；布列斯特条约将卡尔斯、阿尔达汉、巴统交予他们', 'Les Ottomans reviennent à la frontière de 1914 tandis que l’armée russe se dissout ; Brest-Litovsk leur rend Kars, Ardahan et Batoum', '러시아군이 해체되면서 오스만군은 1914년 국경까지 돌아가고, 브레스트 조약이 카르스·아르다한·바투미를 넘긴다'),
          pts: ['Hopa', 'Sarikamis', 'Igdir'] },
      ],
    },
    {
      id: 'mesopotamia',
      name: L('Mesopotamian Front', 'メソポタミア戦線', 'Mesopotamienfront', 'Месопотамский фронт', 'Frente de Mesopotamia', '美索不達米亞戰線', '美索不达米亚战线', 'Front de Mésopotamie', '메소포타미아 전선'),
      left: 'ALLIED', right: 'CENTRAL',
      dates: [
        { d: '1914-12-09', cuts: [640], note: L('Basra and Qurna are held — the oil at the head of the Gulf is what this campaign was sent for', 'バスラとクルナを確保——湾奥の石油こそ、この戦役が送り出された理由である', 'Basra und Qurna sind gehalten — das Öl am Kopf des Golfes ist der Grund, aus dem dieser Feldzug entsandt wurde', 'Басра и Курна взяты — нефть в вершине залива и есть то, ради чего послана эта кампания', 'Basora y Qurna están en manos británicas: el petróleo del fondo del Golfo es aquello para lo que se envió esta campaña', '巴斯拉與庫爾納在握——灣頂的石油正是此戰役出動的理由', '巴士拉与库尔纳在握——湾顶的石油正是此战役出动的理由', 'Bassora et Qurna sont tenues — le pétrole au fond du Golfe est ce pour quoi cette campagne a été envoyée', '바스라와 쿠르나를 확보 — 만 안쪽의 석유야말로 이 전역이 파견된 이유다'),
          pts: ['Zubayr', 'Qurna'] },
        { d: '1915-09-28', cuts: [640], note: L('Kut is taken, and the decision is made to go on to Baghdad', 'クートを占領し、バグダードへ進むことが決まる', 'Kut ist genommen, und es wird entschieden, weiter nach Bagdad zu gehen', 'Кут взят, и принято решение идти на Багдад', 'Kut es tomada y se decide continuar hacia Bagdad', '攻下庫特，並決定繼續進軍巴格達', '攻下库特，并决定继续进军巴格达', 'Kut est prise, et la décision est prise de marcher sur Bagdad', '쿠트를 점령하고, 바그다드로 진격하기로 결정된다'),
          pts: ['Nasiriyah', 'Kut'] },
        { d: '1916-04-29', cuts: [640], note: L('Kut surrenders after 147 days of siege — the whole advance of 1915 has been given back', '147日の包囲の末にクート降伏——1915年の前進はすべて失われた', 'Kut kapituliert nach 147 Tagen Belagerung — der ganze Vormarsch von 1915 ist zurückgegeben', 'Кут капитулирует после 147 дней осады — всё продвижение 1915 года отдано обратно', 'Kut se rinde tras 147 días de asedio: todo el avance de 1915 se ha perdido', '庫特在147天圍困後投降——1915年的全部推進盡失', '库特在147天围困后投降——1915年的全部推进尽失', 'Kut capitule après 147 jours de siège — toute l’avance de 1915 est rendue', '147일 포위 끝에 쿠트가 항복한다 — 1915년의 전진이 모두 되돌려졌다'),
          pts: ['Nasiriyah', 'Al Amarah'] },
        { d: '1917-03-11', cuts: [640], note: L('Baghdad has fallen', 'バグダード陥落', 'Bagdad ist gefallen', 'Багдад взят', 'Bagdad ha caído', '巴格達陷落', '巴格达陷落', 'Bagdad est tombée', '바그다드 함락'),
          pts: ['Ramadi', 'Baghdad', 'Khanaqin'] },
        { d: '1917-11-06', cuts: [640], note: L('Tikrit is taken and the front moves up the Tigris towards Mosul', 'ティクリート占領。戦線はティグリス川を遡ってモースルへ向かう', 'Tikrit ist genommen, und die Front rückt den Tigris hinauf auf Mossul zu', 'Тикрит взят, и фронт поднимается по Тигру к Мосулу', 'Tikrit es tomada y el frente asciende el Tigris hacia Mosul', '攻下提克里特，戰線沿底格里斯河北上直指摩蘇爾', '攻下提克里特，战线沿底格里斯河北上直指摩苏尔', 'Tikrit est prise et le front remonte le Tigre vers Mossoul', '티크리트 점령. 전선이 티그리스강을 거슬러 모술로 향한다'),
          pts: ['Hit', 'Samarra', 'Tikrit', 'Khanaqin'] },
        { d: '1918-11-03', cuts: [640], note: L('Mosul is occupied four days after the armistice of Mudros — the last ground taken in this war', 'ムドロス休戦の4日後にモースル占領——この戦争で最後に取られた土地', 'Mossul wird vier Tage nach dem Waffenstillstand von Mudros besetzt — der letzte in diesem Krieg genommene Boden', 'Мосул занят через четыре дня после Мудросского перемирия — последняя земля, взятая в этой войне', 'Mosul es ocupada cuatro días después del armisticio de Mudros: el último terreno tomado en esta guerra', '穆德羅斯停戰四日後佔領摩蘇爾——此戰最後奪取的土地', '穆德罗斯停战四日后占领摩苏尔——此战最后夺取的土地', 'Mossoul est occupée quatre jours après l’armistice de Moudros — la dernière terre prise dans cette guerre', '무드로스 휴전 나흘 뒤 모술을 점령한다 — 이 전쟁에서 마지막으로 얻은 땅'),
          pts: ['Hit', 'Sharqat', 'Kirkuk'] },
      ],
    },
    {
      id: 'romanian',
      name: L('Romanian Front', 'ルーマニア戦線', 'Rumänische Front', 'Румынский фронт', 'Frente rumano', '羅馬尼亞戰線', '罗马尼亚战线', 'Front roumain', '루마니아 전선'),
      left: 'ALLIED', right: 'CENTRAL',
      until: '1918-05-07',
      dates: [
        { d: '1916-10-25', cuts: [360], note: L('Constanța has fallen: Mackensen holds the Dobruja while the Carpathian passes are being forced', 'コンスタンツァ陥落。カルパティアの峠が突破されつつある間に、マッケンゼンはドブロジャを制する', 'Constanța ist gefallen: Mackensen hält die Dobrudscha, während die Karpatenpässe erzwungen werden', 'Констанца взята: Макензен держит Добруджу, пока прорываются карпатские перевалы', 'Constanza ha caído: Mackensen domina la Dobruja mientras se fuerzan los pasos de los Cárpatos', '康斯坦察陷落：馬肯森掌控多布羅加，同時喀爾巴阡各山口正被強行突破', '康斯坦察陷落：马肯森掌控多布罗加，同时喀尔巴阡各山口正被强行突破', 'Constanța est tombée : Mackensen tient la Dobroudja tandis que les cols des Carpates sont forcés', '콘스탄차 함락. 카르파티아 고개들이 돌파되는 사이 마켄젠이 도브루자를 장악한다'),
          /* ⚠ THE DANUBE, NOT THE ISTHMUS. Quoted across Dobruja — Cernavodă to Constanța — the chord
             has to be extended westward to leave the country, and west of Cernavodă the Danube bends
             north: the extension sweeps the whole of Wallachia and hands Bucharest to Mackensen six
             weeks early. Quoted ALONG the river it leaves Romania within a degree at each end. */
          pts: ['Braila', 'Cernavoda'] },
        { d: '1916-12-06', cuts: [360], left: 'CENTRAL', right: 'ALLIED', note: L('Bucharest has fallen; what is left of Romania is Moldavia behind the Siret', 'ブカレスト陥落。ルーマニアに残されたのは、シレト川の背後のモルダヴィアだけである', 'Bukarest ist gefallen; was von Rumänien bleibt, ist die Moldau hinter dem Sereth', 'Бухарест взят; от Румынии осталась Молдова за Серетом', 'Bucarest ha caído; lo que queda de Rumanía es Moldavia tras el Siret', '布加勒斯特陷落，羅馬尼亞所剩者唯錫雷特河後方的摩爾多瓦', '布加勒斯特陷落，罗马尼亚所剩者唯锡雷特河后方的摩尔多瓦', 'Bucarest est tombée ; ce qui reste de la Roumanie est la Moldavie derrière le Siret', '부쿠레슈티 함락. 루마니아에 남은 것은 시레트강 뒤편의 몰다비아뿐이다'),
          pts: ['Oituz', 'Marasesti', 'Focsani', 'Braila'] },
        { d: '1917-08-06', cuts: [360], left: 'CENTRAL', right: 'ALLIED', note: L('Mărăşeşti — the reorganised Romanian army holds the Siret line that will not move again', 'マラシェシュティ——再建されたルーマニア軍が、以後動かないシレト線を守り抜く', 'Mărășești — die neu aufgestellte rumänische Armee hält die Sereth-Linie, die sich nicht mehr bewegen wird', 'Мэрэшешть — воссозданная румынская армия удерживает Серетскую линию, которая больше не сдвинется', 'Mărășești: el ejército rumano reorganizado sostiene la línea del Siret, que ya no se moverá', '默勒謝什蒂——重整後的羅馬尼亞軍守住了此後不再移動的錫雷特防線', '默勒谢什蒂——重整后的罗马尼亚军守住了此后不再移动的锡雷特防线', 'Mărășești — l’armée roumaine réorganisée tient la ligne du Siret, qui ne bougera plus', '머러셰슈티 — 재편된 루마니아군이, 이후 다시 움직이지 않을 시레트 선을 지킨다'),
          pts: ['Oituz', 'Marasesti', 'Focsani', 'Braila'] },
      ],
    },
  ],
  events: [
    { d: '1914-06-28', at: 'Sarajevo', wiki: 'Assassination_of_Archduke_Franz_Ferdinand', kind: 'political', name: L('Assassination of Archduke Franz Ferdinand', 'サラエヴォ事件', 'Attentat von Sarajevo', 'Сараевское убийство', 'Atentado de Sarajevo', '塞拉耶佛事件', '萨拉热窝事件', 'Attentat de Sarajevo', '사라예보 사건') },
    { d: '1914-08-04', d2: '1914-08-16', at: 'Liege', wiki: 'Battle_of_Liège', name: L('Battle of Liège', 'リエージュ要塞攻防戦', 'Schlacht um Lüttich', 'Осада Льежа', 'Batalla de Lieja', '列日戰役', '列日战役', 'Bataille de Liège', '리에주 전투') },
    { d: '1914-08-26', d2: '1914-08-30', at: 'Olsztynek', wiki: 'Battle_of_Tannenberg', name: L('Battle of Tannenberg', 'タンネンベルクの戦い', 'Schlacht bei Tannenberg', 'Битва при Танненберге', 'Batalla de Tannenberg', '坦能堡戰役', '坦能堡战役', 'Bataille de Tannenberg', '타넨베르크 전투') },
    { d: '1914-09-06', d2: '1914-09-12', at: 'Meaux', wiki: 'First_Battle_of_the_Marne', name: L('First Battle of the Marne', '第一次マルヌ会戦', 'Erste Marneschlacht', 'Первая битва на Марне', 'Primera batalla del Marne', '第一次馬恩河戰役', '第一次马恩河战役', 'Première bataille de la Marne', '제1차 마른 전투') },
    { d: '1914-10-19', d2: '1914-11-22', at: 'Ypres', wiki: 'First_Battle_of_Ypres', name: L('First Battle of Ypres', '第一次イーペルの戦い', 'Erste Flandernschlacht', 'Первая битва при Ипре', 'Primera batalla de Ypres', '第一次伊珀爾戰役', '第一次伊普尔战役', 'Première bataille d’Ypres', '제1차 이프르 전투') },
    { d: '1915-04-25', d2: '1916-01-09', at: 'Cape Helles', wiki: 'Gallipoli_campaign', name: L('Gallipoli campaign', 'ガリポリの戦い', 'Schlacht von Gallipoli', 'Дарданелльская операция', 'Campaña de Galípoli', '加里波利之戰', '加里波利之战', 'Bataille des Dardanelles', '갈리폴리 전투') },
    { d: '1915-05-02', d2: '1915-09-19', at: 'Gorlice', wiki: 'Gorlice–Tarnów_offensive', name: L('Gorlice–Tarnów offensive', 'ゴルリツェ＝タルヌフ攻勢', 'Schlacht von Gorlice-Tarnów', 'Горлицкий прорыв', 'Ofensiva de Gorlice-Tarnów', '戈爾利采—塔爾努夫攻勢', '戈尔利采—塔尔努夫攻势', 'Offensive de Gorlice-Tarnów', '고를리체–타르누프 공세') },
    { d: '1916-02-21', d2: '1916-12-18', at: 'Verdun', wiki: 'Battle_of_Verdun', name: L('Battle of Verdun', 'ヴェルダンの戦い', 'Schlacht um Verdun', 'Верденская битва', 'Batalla de Verdún', '凡爾登戰役', '凡尔登战役', 'Bataille de Verdun', '베르됭 전투') },
    { d: '1916-05-31', d2: '1916-06-01', at: 'Jutland', wiki: 'Battle_of_Jutland', kind: 'naval', name: L('Battle of Jutland', 'ユトランド沖海戦', 'Skagerrakschlacht', 'Ютландское сражение', 'Batalla de Jutlandia', '日德蘭海戰', '日德兰海战', 'Bataille du Jutland', '유틀란트 해전') },
    { d: '1916-06-04', d2: '1916-09-20', at: 'Lutsk', wiki: 'Brusilov_offensive', name: L('Brusilov Offensive', 'ブルシーロフ攻勢', 'Brussilow-Offensive', 'Брусиловский прорыв', 'Ofensiva Brusílov', '布魯西洛夫攻勢', '布鲁西洛夫攻势', 'Offensive Broussilov', '브루실로프 공세') },
    { d: '1916-07-01', d2: '1916-11-18', at: 'Albert', wiki: 'Battle_of_the_Somme', name: L('Battle of the Somme', 'ソンムの戦い', 'Schlacht an der Somme', 'Битва на Сомме', 'Batalla del Somme', '索姆河戰役', '索姆河战役', 'Bataille de la Somme', '솜 전투') },
    { d: '1917-04-09', d2: '1917-05-16', at: 'Arras', wiki: 'Battle_of_Arras_(1917)', name: L('Battle of Arras', 'アラスの戦い', 'Schlacht bei Arras', 'Битва при Аррасе', 'Batalla de Arrás', '阿拉斯戰役', '阿拉斯战役', 'Bataille d’Arras', '아라스 전투') },
    { d: '1917-07-31', d2: '1917-11-10', at: 'Ypres', wiki: 'Battle_of_Passchendaele', name: L('Battle of Passchendaele', 'パッシェンデールの戦い', 'Dritte Flandernschlacht', 'Битва при Пашендейле', 'Batalla de Passchendaele', '帕森達勒戰役', '帕斯尚尔战役', 'Bataille de Passchendaele', '파스샹달 전투') },
    { d: '1917-10-24', d2: '1917-11-19', at: 'Kobarid', wiki: 'Battle_of_Caporetto', name: L('Battle of Caporetto', 'カポレットの戦い', 'Schlacht von Karfreit', 'Битва при Капоретто', 'Batalla de Caporetto', '卡波雷托戰役', '卡波雷托战役', 'Bataille de Caporetto', '카포레토 전투') },
    { d: '1918-03-21', d2: '1918-07-18', at: 'Saint-Quentin', wiki: 'German_spring_offensive', name: L('German spring offensive', 'ドイツ軍春季攻勢', 'Deutsche Frühjahrsoffensive', 'Весеннее наступление германской армии', 'Ofensiva alemana de primavera', '德軍春季攻勢', '德军春季攻势', 'Offensive allemande du printemps', '독일군 춘계 공세') },
    { d: '1918-08-08', d2: '1918-11-11', at: 'Amiens', wiki: 'Hundred_Days_Offensive', name: L('Hundred Days Offensive', '百日攻勢', 'Hundert-Tage-Offensive', 'Стодневное наступление', 'Ofensiva de los Cien Días', '百日攻勢', '百日攻势', 'Offensive des Cent-Jours', '백일 공세') },
    { d: '1918-09-19', d2: '1918-10-31', at: 'Megiddo', wiki: 'Battle_of_Megiddo_(1918)', name: L('Battle of Megiddo', 'メギドの戦い', 'Schlacht von Megiddo', 'Битва при Мегиддо', 'Batalla de Meguido', '米吉多戰役', '米吉多战役', 'Bataille de Megiddo', '메기도 전투') },
    { d: '1918-11-11', at: 'Compiegne', wiki: 'Armistice_of_11_November_1918', kind: 'political', name: L('Armistice of 11 November 1918', 'コンピエーニュ休戦協定', 'Waffenstillstand von Compiègne', 'Компьенское перемирие', 'Armisticio del 11 de noviembre de 1918', '康白尼停戰協定', '康边停战协定', 'Armistice du 11 novembre 1918', '콩피에뉴 휴전 협정') },

    /* ══ #R381 — THE REST OF THE WAR ═══════════════════════════════════════════════════════════
       #R349 shipped eighteen operations for fifty-two months, which is a list of the famous ones
       rather than a record: nothing at all for Serbia, the Caucasus, Mesopotamia, Romania or the
       Arab Revolt, and nothing for any of the three revolutions and armistices that decided how the
       war ended. Every row below has the dates the operation actually ran and the place it is named
       after, and every one of them is reachable from the layer's legend on the day it was running. */
    { d: '1914-08-12', d2: '1914-08-24', at: 'Sabac', wiki: 'Battle_of_Cer', name: L('Battle of Cer — the first Allied victory of the war', 'ツェル山の戦い——連合国側にとって開戦後初の勝利', 'Schlacht am Cer — der erste Sieg der Entente in diesem Krieg', 'Битва при Цере — первая победа Антанты в этой войне', 'Batalla de Cer, la primera victoria aliada de la guerra', '采爾山戰役——協約國在此戰中的首場勝利', '采尔山战役——协约国在此战中的首场胜利', 'Bataille de Cer — la première victoire alliée de la guerre', '체르 전투 — 이 전쟁에서 협상국의 첫 승리') },
    { d: '1914-08-20', at: 'Brussels', wiki: 'German_occupation_of_Belgium_during_World_War_I', kind: 'political', name: L('Brussels is occupied', 'ブリュッセル占領', 'Brüssel wird besetzt', 'Брюссель занят', 'Bruselas es ocupada', '布魯塞爾被佔領', '布鲁塞尔被占领', 'Bruxelles est occupée', '브뤼셀 점령') },
    { d: '1914-08-23', at: 'Mons', wiki: 'Battle_of_Mons', name: L('Battle of Mons — the British Army’s first action of the war', 'モンスの戦い——イギリス軍にとって開戦後最初の戦闘', 'Schlacht bei Mons — das erste Gefecht der britischen Armee in diesem Krieg', 'Битва при Монсе — первый бой британской армии в этой войне', 'Batalla de Mons, la primera acción del ejército británico en la guerra', '蒙斯戰役——英軍在此戰中的首次交戰', '蒙斯战役——英军在此战中的首次交战', 'Bataille de Mons — le premier engagement de l’armée britannique', '몽스 전투 — 이 전쟁에서 영국군의 첫 전투') },
    { d: '1914-09-28', d2: '1914-10-10', at: 'Antwerp', wiki: 'Siege_of_Antwerp_(1914)', name: L('Siege of Antwerp', 'アントウェルペン包囲戦', 'Belagerung von Antwerpen', 'Осада Антверпена', 'Sitio de Amberes', '安特衛普圍城戰', '安特卫普围城战', 'Siège d’Anvers', '안트베르펀 공방전') },
    { d: '1914-11-22', d2: '1914-12-17', at: 'Qurna', wiki: 'Mesopotamian_campaign', name: L('The Mesopotamian campaign opens at Basra and Qurna', 'メソポタミア戦役がバスラとクルナで始まる', 'Der Mesopotamienfeldzug beginnt bei Basra und Qurna', 'Месопотамская кампания начинается у Басры и Курны', 'La campaña de Mesopotamia se abre en Basora y Qurna', '美索不達米亞戰役自巴斯拉與庫爾納展開', '美索不达米亚战役自巴士拉与库尔纳展开', 'La campagne de Mésopotamie s’ouvre à Bassora et Qurna', '메소포타미아 전역이 바스라와 쿠르나에서 시작된다') },
    { d: '1914-12-02', d2: '1914-12-15', at: 'Lazarevac', wiki: 'Battle_of_Kolubara', name: L('Battle of Kolubara — Serbia retakes Belgrade and clears its territory', 'コルバラの戦い——セルビアがベオグラードを奪回し、領土から敵を一掃する', 'Schlacht an der Kolubara — Serbien nimmt Belgrad zurück und räumt sein Gebiet', 'Колубарская битва — Сербия возвращает Белград и очищает свою территорию', 'Batalla del Kolubara: Serbia recupera Belgrado y despeja su territorio', '科盧巴拉戰役——塞爾維亞奪回貝爾格勒並肅清國土', '科卢巴拉战役——塞尔维亚夺回贝尔格莱德并肃清国土', 'Bataille de la Kolubara — la Serbie reprend Belgrade et libère son territoire', '콜루바라 전투 — 세르비아가 베오그라드를 탈환하고 국토를 되찾는다') },
    { d: '1914-12-22', d2: '1915-01-17', at: 'Sarikamis', wiki: 'Battle_of_Sarikamish', name: L('Battle of Sarikamish — the Ottoman Third Army is destroyed by the winter', 'サルカムシュの戦い——オスマン第3軍が冬に壊滅する', 'Schlacht von Sarıkamış — die osmanische 3. Armee wird vom Winter vernichtet', 'Сарыкамышское сражение — османская 3-я армия гибнет от зимы', 'Batalla de Sarikamish: el Tercer Ejército otomano es destruido por el invierno', '薩勒卡默什戰役——鄂圖曼第三軍為寒冬所滅', '萨勒卡默什战役——奥斯曼第三军为寒冬所灭', 'Bataille de Sarıkamış — la IIIᵉ armée ottomane est détruite par l’hiver', '사르카므시 전투 — 오스만 제3군이 겨울에 궤멸된다') },
    { d: '1915-04-22', d2: '1915-05-25', at: 'Ypres', wiki: 'Second_Battle_of_Ypres', name: L('Second Ypres — the first large-scale use of poison gas on the Western Front', '第二次イーペル——西部戦線で初めて毒ガスが大規模に使われる', 'Zweite Flandernschlacht — der erste Großeinsatz von Giftgas an der Westfront', 'Вторая битва при Ипре — первое массовое применение отравляющих газов на Западном фронте', 'Segunda batalla de Ypres: primer uso masivo de gas venenoso en el frente occidental', '第二次伊珀爾戰役——西線首次大規模使用毒氣', '第二次伊普尔战役——西线首次大规模使用毒气', 'Deuxième bataille d’Ypres — premier emploi massif de gaz de combat sur le front occidental', '제2차 이프르 전투 — 서부 전선에서 독가스가 처음 대규모로 사용된다') },
    { d: '1915-04-25', d2: '1915-12-20', at: 'Anzac Cove', wiki: 'Landing_at_Anzac_Cove', name: L('The landing at Anzac Cove', 'アンザック湾への上陸', 'Die Landung in der Anzac-Bucht', 'Высадка в бухте Анзак', 'El desembarco en la ensenada de Anzac', '澳紐灣登陸', '澳新湾登陆', 'Le débarquement de la baie d’Anzac', '앤잭 코브 상륙') },
    { d: '1915-05-23', at: 'Rome', wiki: 'Treaty_of_London_(1915)', kind: 'political', name: L('Italy declares war on Austria-Hungary', 'イタリアがオーストリア＝ハンガリーに宣戦布告', 'Italien erklärt Österreich-Ungarn den Krieg', 'Италия объявляет войну Австро-Венгрии', 'Italia declara la guerra a Austria-Hungría', '義大利對奧匈帝國宣戰', '意大利对奥匈帝国宣战', 'L’Italie déclare la guerre à l’Autriche-Hongrie', '이탈리아가 오스트리아·헝가리에 선전포고') },
    { d: '1915-08-06', d2: '1915-08-29', at: 'Suvla', wiki: 'Battle_of_Sari_Bair', name: L('The Suvla landings — the last attempt to break out of the Gallipoli beachheads', 'スヴラ湾上陸——ガリポリの橋頭堡から脱出する最後の試み', 'Die Landung bei Suvla — der letzte Versuch, aus den Brückenköpfen von Gallipoli auszubrechen', 'Высадка у Сувлы — последняя попытка вырваться с галлиполийских плацдармов', 'Los desembarcos de Suvla: el último intento de salir de las cabezas de playa de Galípoli', '蘇弗拉灣登陸——突破加里波利灘頭陣地的最後嘗試', '苏弗拉湾登陆——突破加里波利滩头阵地的最后尝试', 'Le débarquement de Suvla — la dernière tentative de sortir des têtes de pont de Gallipoli', '수블라 상륙 — 갈리폴리 교두보를 벗어나려는 마지막 시도') },
    { d: '1915-09-25', d2: '1915-10-14', at: 'Lens', wiki: 'Battle_of_Loos', name: L('Battle of Loos — the British Army’s largest attack of 1915', 'ロースの戦い——1915年におけるイギリス軍最大の攻撃', 'Schlacht bei Loos — der größte britische Angriff des Jahres 1915', 'Битва при Лоосе — крупнейшее британское наступление 1915 года', 'Batalla de Loos, el mayor ataque británico de 1915', '盧斯戰役——英軍1915年最大規模的攻擊', '卢斯战役——英军1915年最大规模的攻击', 'Bataille de Loos — la plus grande attaque britannique de 1915', '루스 전투 — 1915년 영국군 최대의 공격') },
    { d: '1915-10-06', d2: '1915-11-24', at: 'Belgrade', wiki: 'Serbian_campaign', name: L('The conquest of Serbia — the army retreats across Albania to the sea', 'セルビア征服——軍はアルバニアを越えて海へ退却する', 'Die Eroberung Serbiens — die Armee zieht sich über Albanien zum Meer zurück', 'Завоевание Сербии — армия отступает через Албанию к морю', 'La conquista de Serbia: el ejército se retira a través de Albania hasta el mar', '塞爾維亞被征服——軍隊穿越阿爾巴尼亞退向海邊', '塞尔维亚被征服——军队穿越阿尔巴尼亚退向海边', 'La conquête de la Serbie — l’armée se replie à travers l’Albanie jusqu’à la mer', '세르비아 정복 — 군대가 알바니아를 넘어 바다로 후퇴한다') },
    { d: '1915-12-07', d2: '1916-04-29', at: 'Kut', wiki: 'Siege_of_Kut', name: L('Siege of Kut — 13,000 surrender after 147 days', 'クート包囲戦——147日の後、1万3千が降伏する', 'Belagerung von Kut — nach 147 Tagen kapitulieren 13.000 Mann', 'Осада Эль-Кута — через 147 дней сдаются 13 000 человек', 'Sitio de Kut: 13.000 se rinden tras 147 días', '庫特圍城戰——147天後一萬三千人投降', '库特围城战——147天后一万三千人投降', 'Siège de Kut — 13 000 hommes capitulent après 147 jours', '쿠트 공방전 — 147일 만에 1만 3천 명이 항복한다') },
    { d: '1916-02-16', at: 'Erzurum', wiki: 'Erzurum_offensive', name: L('Erzurum offensive — the fortress of the Ottoman east falls to the Russians', 'エルズルム攻勢——オスマン東部の要塞がロシア軍の手に落ちる', 'Erzurum-Offensive — die Festung des osmanischen Ostens fällt an die Russen', 'Эрзурумская операция — крепость османского востока переходит к русским', 'Ofensiva de Erzurum: la fortaleza del oriente otomano cae ante los rusos', '埃爾祖魯姆攻勢——鄂圖曼東部要塞落入俄軍之手', '埃尔祖鲁姆攻势——奥斯曼东部要塞落入俄军之手', 'Offensive d’Erzeroum — la forteresse de l’Orient ottoman tombe aux mains des Russes', '에르주룸 공세 — 오스만 동부의 요새가 러시아군에 넘어간다') },
    { d: '1916-04-18', at: 'Trabzon', wiki: 'Trebizond_campaign', name: L('Trebizond is taken — the Russians hold the Black Sea coast', 'トレビゾンド占領——ロシア軍が黒海沿岸を押さえる', 'Trapezunt wird genommen — die Russen halten die Schwarzmeerküste', 'Взят Трапезунд — русские держат черноморское побережье', 'Se toma Trebisonda: los rusos dominan la costa del mar Negro', '攻下特拉布宗——俄軍控制黑海沿岸', '攻下特拉布宗——俄军控制黑海沿岸', 'Trébizonde est prise — les Russes tiennent la côte de la mer Noire', '트라브존 점령 — 러시아군이 흑해 연안을 장악한다') },
    { d: '1916-06-10', d2: '1918-10-25', at: 'Mecca', wiki: 'Arab_Revolt', kind: 'political', name: L('The Arab Revolt begins at Mecca', 'メッカでアラブ反乱が始まる', 'Die Arabische Revolte beginnt in Mekka', 'Арабское восстание начинается в Мекке', 'La Revuelta Árabe comienza en La Meca', '阿拉伯起義自麥加開始', '阿拉伯起义自麦加开始', 'La révolte arabe commence à La Mecque', '메카에서 아랍 반란이 시작된다') },
    { d: '1916-08-04', d2: '1916-08-05', at: 'Romani', wiki: 'Battle_of_Romani', name: L('Battle of Romani — the last Ottoman threat to the Suez Canal', 'ロマニの戦い——スエズ運河へのオスマン軍最後の脅威', 'Schlacht von Romani — die letzte osmanische Bedrohung des Suezkanals', 'Битва при Романи — последняя османская угроза Суэцкому каналу', 'Batalla de Romani: la última amenaza otomana al canal de Suez', '羅馬尼戰役——鄂圖曼對蘇伊士運河的最後威脅', '罗马尼战役——奥斯曼对苏伊士运河的最后威胁', 'Bataille de Romani — la dernière menace ottomane sur le canal de Suez', '로마니 전투 — 수에즈 운하에 대한 오스만의 마지막 위협') },
    { d: '1916-08-27', at: 'Bucharest', wiki: 'Romania_during_World_War_I', kind: 'political', name: L('Romania enters the war', 'ルーマニアが参戦する', 'Rumänien tritt in den Krieg ein', 'Румыния вступает в войну', 'Rumanía entra en la guerra', '羅馬尼亞參戰', '罗马尼亚参战', 'La Roumanie entre en guerre', '루마니아가 참전한다') },
    { d: '1916-12-06', at: 'Bucharest', wiki: 'Battle_of_Bucharest', name: L('Bucharest falls; the government and the army withdraw to Iași', 'ブカレスト陥落。政府と軍はヤシへ退く', 'Bukarest fällt; Regierung und Armee ziehen sich nach Iași zurück', 'Бухарест взят; правительство и армия отходят в Яссы', 'Bucarest cae; el gobierno y el ejército se retiran a Iași', '布加勒斯特陷落，政府與軍隊撤往雅西', '布加勒斯特陷落，政府与军队撤往雅西', 'Bucarest tombe ; le gouvernement et l’armée se replient sur Iași', '부쿠레슈티 함락. 정부와 군대가 야시로 물러난다') },
    { d: '1917-03-08', d2: '1917-03-16', at: 'Leningrad', wiki: 'February_Revolution', kind: 'political', name: L('The February Revolution — the Tsar abdicates', '二月革命——皇帝が退位する', 'Februarrevolution — der Zar dankt ab', 'Февральская революция — царь отрекается от престола', 'La Revolución de Febrero: el zar abdica', '二月革命——沙皇退位', '二月革命——沙皇退位', 'La révolution de Février — le tsar abdique', '2월 혁명 — 차르가 퇴위한다') },
    { d: '1917-03-11', at: 'Baghdad', wiki: 'Fall_of_Baghdad_(1917)', name: L('Baghdad is taken', 'バグダード占領', 'Bagdad wird eingenommen', 'Багдад взят', 'Bagdad es tomada', '攻下巴格達', '攻下巴格达', 'Bagdad est prise', '바그다드 점령') },
    { d: '1917-04-06', at: 'Washington', wiki: 'American_entry_into_World_War_I', kind: 'political', name: L('The United States declares war on Germany', 'アメリカ合衆国がドイツに宣戦布告する', 'Die Vereinigten Staaten erklären Deutschland den Krieg', 'США объявляют войну Германии', 'Estados Unidos declara la guerra a Alemania', '美國對德宣戰', '美国对德宣战', 'Les États-Unis déclarent la guerre à l’Allemagne', '미국이 독일에 선전포고한다') },
    { d: '1917-04-16', d2: '1917-05-09', at: 'Laon', wiki: 'Nivelle_offensive', name: L('The Nivelle Offensive — its failure sets off mutinies in half the French army', 'ニヴェル攻勢——その失敗がフランス軍の半数で反乱を引き起こす', 'Die Nivelle-Offensive — ihr Scheitern löst Meutereien in der halben französischen Armee aus', 'Наступление Нивеля — его провал вызывает мятежи в половине французской армии', 'La ofensiva Nivelle: su fracaso desata motines en media Francia militar', '尼維爾攻勢——其失敗引發法軍半數部隊譁變', '尼维尔攻势——其失败引发法军半数部队哗变', 'L’offensive Nivelle — son échec déclenche des mutineries dans la moitié de l’armée française', '니벨 공세 — 그 실패가 프랑스군 절반에 항명을 불러온다') },
    { d: '1917-06-07', d2: '1917-06-14', at: 'Armentieres', wiki: 'Battle_of_Messines_(1917)', name: L('Messines — nineteen mines under the ridge, heard in London', 'メシーヌ——尾根の下で19個の地雷が爆発し、ロンドンでも聞こえた', 'Messines — neunzehn Minen unter dem Höhenrücken, in London zu hören', 'Мессин — девятнадцать мин под грядой, слышных в Лондоне', 'Messines: diecinueve minas bajo la cresta, oídas en Londres', '梅西訥——山脊下十九處爆破，倫敦亦可聽聞', '梅西讷——山脊下十九处爆破，伦敦亦可听闻', 'Messines — dix-neuf mines sous la crête, entendues jusqu’à Londres', '메신 — 능선 아래 열아홉 개의 갱도 폭파, 런던에서도 들렸다') },
    { d: '1917-11-07', at: 'Leningrad', wiki: 'October_Revolution', kind: 'political', name: L('The October Revolution', '十月革命', 'Oktoberrevolution', 'Октябрьская революция', 'La Revolución de Octubre', '十月革命', '十月革命', 'La révolution d’Octobre', '10월 혁명') },
    { d: '1917-11-20', d2: '1917-12-07', at: 'Cambrai', wiki: 'Battle_of_Cambrai_(1917)', name: L('Cambrai — the first mass tank attack, and the first German counter-attack to take it all back', 'カンブレー——最初の大規模戦車攻撃と、それを全て奪い返した最初のドイツ軍逆襲', 'Cambrai — der erste Massenangriff mit Panzern, und der erste deutsche Gegenangriff, der alles zurücknahm', 'Камбре — первая массовая танковая атака и первый германский контрудар, вернувший всё обратно', 'Cambrai: el primer ataque masivo de tanques, y el primer contraataque alemán que lo recuperó todo', '康布雷——首次大規模坦克攻擊，以及首次將其全數奪回的德軍反擊', '康布雷——首次大规模坦克攻击，以及首次将其全数夺回的德军反击', 'Cambrai — la première attaque massive de chars, et la première contre-attaque allemande qui reprit tout', '캉브레 — 최초의 대규모 전차 공격, 그리고 그것을 모두 되찾은 최초의 독일군 반격') },
    { d: '1917-12-09', at: 'Jerusalem', wiki: 'Battle_of_Jerusalem', name: L('Jerusalem surrenders', 'エルサレム降伏', 'Jerusalem kapituliert', 'Иерусалим сдаётся', 'Jerusalén se rinde', '耶路撒冷投降', '耶路撒冷投降', 'Jérusalem capitule', '예루살렘이 항복한다') },
    { d: '1918-02-18', d2: '1918-03-03', at: 'Pskov', wiki: 'Operation_Faustschlag', name: L('Operation Faustschlag — 240 km in eleven days against no opposition', 'ファウストシュラーク作戦——抵抗なしに11日で240キロ', 'Unternehmen Faustschlag — 240 km in elf Tagen ohne Gegenwehr', 'Операция «Фаустшлаг» — 240 км за одиннадцать дней без сопротивления', 'Operación Faustschlag: 240 km en once días sin oposición', '「鐵拳」作戰——十一天推進240公里，未遇抵抗', '“铁拳”作战——十一天推进240公里，未遇抵抗', 'Opération Faustschlag — 240 km en onze jours sans résistance', '파우스트슐라크 작전 — 저항 없이 11일에 240킬로미터') },
    { d: '1918-03-03', at: 'Brest', wiki: 'Treaty_of_Brest-Litovsk', kind: 'political', name: L('The Treaty of Brest-Litovsk takes Russia out of the war', 'ブレスト＝リトフスク条約でロシアが戦争から離脱する', 'Der Friede von Brest-Litowsk nimmt Russland aus dem Krieg', 'Брест-Литовский мир выводит Россию из войны', 'El Tratado de Brest-Litovsk saca a Rusia de la guerra', '布列斯特—立陶夫斯克條約使俄國退出戰爭', '布列斯特—立托夫斯克条约使俄国退出战争', 'Le traité de Brest-Litovsk fait sortir la Russie de la guerre', '브레스트-리토프스크 조약으로 러시아가 전쟁에서 이탈한다') },
    { d: '1918-06-01', d2: '1918-06-26', at: 'Chateau-Thierry', wiki: 'Battle_of_Belleau_Wood', name: L('Belleau Wood — the first sustained American action of the war', 'ベロー・ウッド——アメリカ軍にとって最初の本格的戦闘', 'Belleau Wood — das erste anhaltende amerikanische Gefecht dieses Krieges', 'Белло-Вуд — первое затяжное сражение американцев в этой войне', 'Belleau Wood: la primera acción estadounidense sostenida de la guerra', '貝勒森林——美軍在此戰中首次持久作戰', '贝洛森林——美军在此战中首次持久作战', 'Bois Belleau — le premier engagement américain prolongé de la guerre', '벨로 숲 — 이 전쟁에서 미군의 첫 지속 전투') },
    { d: '1918-07-15', d2: '1918-08-06', at: 'Reims', wiki: 'Second_Battle_of_the_Marne', name: L('The Second Battle of the Marne — the last German offensive of the war', '第二次マルヌ会戦——この戦争で最後のドイツ軍攻勢', 'Die zweite Marneschlacht — die letzte deutsche Offensive des Krieges', 'Вторая битва на Марне — последнее германское наступление войны', 'La segunda batalla del Marne: la última ofensiva alemana de la guerra', '第二次馬恩河戰役——德軍在此戰中最後一次攻勢', '第二次马恩河战役——德军在此战中最后一次攻势', 'La seconde bataille de la Marne — la dernière offensive allemande de la guerre', '제2차 마른 전투 — 이 전쟁 마지막 독일군 공세') },
    { d: '1918-09-12', d2: '1918-09-15', at: 'Saint-Mihiel', wiki: 'Battle_of_Saint-Mihiel', name: L('Saint-Mihiel — the first offensive by an American army', 'サン＝ミエル——アメリカ軍として最初の攻勢', 'Saint-Mihiel — die erste Offensive einer amerikanischen Armee', 'Сен-Миель — первое наступление американской армии', 'Saint-Mihiel: la primera ofensiva de un ejército estadounidense', '聖米耶爾——美軍首次以軍團規模發動攻勢', '圣米耶尔——美军首次以军团规模发动攻势', 'Saint-Mihiel — la première offensive d’une armée américaine', '생미이엘 — 미군 군단위 최초의 공세') },
    { d: '1918-09-15', d2: '1918-09-29', at: 'Bitola', wiki: 'Vardar_offensive', name: L('The Vardar Offensive — Bulgaria signs an armistice a fortnight later', 'ヴァルダル攻勢——2週間後にブルガリアが休戦協定に署名する', 'Die Vardar-Offensive — vierzehn Tage später unterzeichnet Bulgarien einen Waffenstillstand', 'Вардарское наступление — через две недели Болгария подписывает перемирие', 'La ofensiva del Vardar: quince días después Bulgaria firma un armisticio', '瓦爾達爾攻勢——兩週後保加利亞簽署停戰協定', '瓦尔达尔攻势——两周后保加利亚签署停战协定', 'L’offensive du Vardar — quinze jours plus tard la Bulgarie signe un armistice', '바르다르 공세 — 2주 뒤 불가리아가 휴전 협정에 서명한다') },
    { d: '1918-09-26', d2: '1918-11-11', at: 'Sedan', wiki: 'Meuse–Argonne_offensive', name: L('The Meuse–Argonne offensive — 1.2 million Americans, the largest battle in United States history', 'ムーズ・アルゴンヌ攻勢——120万のアメリカ兵、合衆国史上最大の戦闘', 'Die Maas-Argonnen-Offensive — 1,2 Millionen Amerikaner, die größte Schlacht der US-Geschichte', 'Мёз-Аргоннское наступление — 1,2 миллиона американцев, крупнейшее сражение в истории США', 'La ofensiva Mosa-Argonne: 1,2 millones de estadounidenses, la mayor batalla de la historia de EE. UU.', '默茲—阿爾貢攻勢——一百二十萬美軍，美國史上最大規模的戰役', '默兹—阿尔贡攻势——一百二十万美军，美国史上最大规模的战役', 'L’offensive Meuse-Argonne — 1,2 million d’Américains, la plus grande bataille de l’histoire des États-Unis', '뫼즈-아르곤 공세 — 미군 120만 명, 미국사 최대의 전투') },
    { d: '1918-10-30', at: 'Istanbul', wiki: 'Armistice_of_Mudros', kind: 'political', name: L('The Armistice of Mudros ends the Ottoman war', 'ムドロス休戦協定がオスマン帝国の戦争を終わらせる', 'Der Waffenstillstand von Mudros beendet den osmanischen Krieg', 'Мудросское перемирие заканчивает войну Османской империи', 'El Armisticio de Mudros pone fin a la guerra otomana', '穆德羅斯停戰協定結束鄂圖曼的戰爭', '穆德罗斯停战协定结束奥斯曼的战争', 'L’armistice de Moudros met fin à la guerre ottomane', '무드로스 휴전 협정이 오스만의 전쟁을 끝낸다') },
    { d: '1918-11-03', at: 'Trieste', wiki: 'Armistice_of_Villa_Giusti', kind: 'political', name: L('The Armistice of Villa Giusti — Austria-Hungary leaves the war and ceases to exist', 'ヴィラ・ジュスティ休戦協定——オーストリア＝ハンガリーは戦争を離れ、そして消滅する', 'Der Waffenstillstand von Villa Giusti — Österreich-Ungarn scheidet aus dem Krieg aus und hört auf zu bestehen', 'Перемирие на Вилла-Джусти — Австро-Венгрия выходит из войны и перестаёт существовать', 'El armisticio de Villa Giusti: Austria-Hungría abandona la guerra y deja de existir', '維拉朱斯蒂停戰協定——奧匈帝國退出戰爭並就此消亡', '维拉朱斯蒂停战协定——奥匈帝国退出战争并就此消亡', 'L’armistice de Villa Giusti — l’Autriche-Hongrie quitte la guerre et cesse d’exister', '빌라 주스티 휴전 협정 — 오스트리아·헝가리가 전쟁에서 이탈하고 소멸한다') },

    /* ── #R381 · the last of the anchors, each with the operation it was added for ─────────── */
    { d: '1916-09-26', d2: '1916-09-29', at: 'Sibiu', wiki: 'Battle_of_Sibiu', name: L('Battle of Sibiu — the Romanian invasion of Transylvania is thrown back through the passes', 'ナジセベン（シビウ）の戦い——トランシルヴァニアへのルーマニア侵攻が峠の向こうへ押し返される', 'Schlacht bei Hermannstadt — der rumänische Einmarsch in Siebenbürgen wird durch die Pässe zurückgeworfen', 'Битва при Сибиу — румынское вторжение в Трансильванию отброшено обратно через перевалы', 'Batalla de Sibiu: la invasión rumana de Transilvania es rechazada a través de los pasos', '錫比烏戰役——羅馬尼亞對特蘭西瓦尼亞的入侵被逐回山口以東', '锡比乌战役——罗马尼亚对特兰西瓦尼亚的入侵被逐回山口以东', 'Bataille de Sibiu — l’invasion roumaine de la Transylvanie est rejetée par-delà les cols', '시비우 전투 — 트란실바니아를 향한 루마니아의 침공이 고개 너머로 밀려난다') },
    { d: '1916-10-07', d2: '1916-10-09', at: 'Brasov', wiki: 'Battle_of_Brașov', name: L('Battle of Brașov — the furthest the Romanian army ever got', 'ブラショフの戦い——ルーマニア軍が到達した最遠点', 'Schlacht bei Kronstadt — der weiteste Punkt, den die rumänische Armee je erreichte', 'Битва при Брашове — предел, которого достигла румынская армия', 'Batalla de Brașov: lo más lejos que llegó el ejército rumano', '布拉索夫戰役——羅馬尼亞軍推進的最遠處', '布拉索夫战役——罗马尼亚军推进的最远处', 'Bataille de Brașov — le point le plus avancé jamais atteint par l’armée roumaine', '브라쇼브 전투 — 루마니아군이 도달한 최원점') },
    { d: '1917-01-09', at: 'Rafah', wiki: 'Battle_of_Rafa', name: L('Battle of Rafa — the last Ottoman post in Sinai falls and the campaign crosses the frontier', 'ラファの戦い——シナイ最後のオスマン軍拠点が落ち、戦役は国境を越える', 'Schlacht von Rafa — der letzte osmanische Posten auf dem Sinai fällt und der Feldzug überschreitet die Grenze', 'Битва при Рафе — последний османский пост на Синае пал, и кампания переходит границу', 'Batalla de Rafa: cae el último puesto otomano del Sinaí y la campaña cruza la frontera', '拉法戰役——西奈半島最後的鄂圖曼據點陷落，戰役越過邊界', '拉法战役——西奈半岛最后的奥斯曼据点陷落，战役越过边界', 'Bataille de Rafa — le dernier poste ottoman du Sinaï tombe et la campagne franchit la frontière', '라파 전투 — 시나이 최후의 오스만 거점이 함락되고 전역이 국경을 넘는다') },
    { d: '1917-11-11', d2: '1917-12-23', at: 'Monte Grappa', wiki: 'Battle_of_Monte_Grappa', name: L('Monte Grappa — the mountain anchor of the Piave line, held through two winters', 'モンテ・グラッパ——ピアーヴェ線の山側の要であり、二度の冬を守り抜いた', 'Monte Grappa — der Bergpfeiler der Piave-Linie, zwei Winter lang gehalten', 'Монте-Граппа — горный якорь линии Пьявы, удержанный две зимы подряд', 'Monte Grappa: el ancla montañosa de la línea del Piave, sostenida dos inviernos', '格拉帕山——皮亞韋防線的山地支點，堅守兩個冬天', '格拉帕山——皮亚韦防线的山地支点，坚守两个冬天', 'Le mont Grappa — l’ancrage montagneux de la ligne de la Piave, tenu deux hivers durant', '몬테그라파 — 피아베 선의 산악 축, 두 번의 겨울을 지켜냈다') },
    { d: '1918-03-21', d2: '1918-05-04', at: 'Amman', wiki: 'Transjordan_attacks_on_Amman', name: L('The Transjordan raids — two attempts on Amman and the Hejaz railway, both repulsed', 'ヨルダン川東岸の襲撃——アンマンとヒジャーズ鉄道への2度の攻撃は、いずれも撃退される', 'Die Transjordanien-Vorstöße — zwei Versuche gegen Amman und die Hedschasbahn, beide abgewiesen', 'Заиорданские рейды — две попытки на Амман и Хиджазскую железную дорогу, обе отбиты', 'Las incursiones de Transjordania: dos intentos sobre Amán y el ferrocarril del Hiyaz, ambos rechazados', '外約旦突襲——兩次進攻安曼與漢志鐵路，皆被擊退', '外约旦突袭——两次进攻安曼与汉志铁路，皆被击退', 'Les raids de Transjordanie — deux tentatives sur Amman et le chemin de fer du Hedjaz, toutes deux repoussées', '트란스요르단 습격 — 암만과 헤자즈 철도를 노린 두 차례의 시도가 모두 격퇴된다') },
    { d: '1918-04-14', at: 'Batumi', wiki: 'Battle_of_Batum', name: L('Batum is occupied — Brest-Litovsk gave it back to the Ottomans and they walked in and took it', 'バトゥム占領——ブレスト＝リトフスク条約で返還され、オスマン軍がそのまま入って接収した', 'Batum wird besetzt — Brest-Litowsk gab es den Osmanen zurück, und sie marschierten hinein', 'Батум занят — Брест-Литовск вернул его османам, и они просто вошли', 'Batumi es ocupada: Brest-Litovsk se la devolvió a los otomanos, y entraron a tomarla', '巴統被佔領——布列斯特條約將其歸還鄂圖曼，鄂軍遂長驅直入', '巴统被占领——布列斯特条约将其归还奥斯曼，奥军遂长驱直入', 'Batoum est occupée — Brest-Litovsk l’avait rendue aux Ottomans, qui sont entrés la prendre', '바투미 점령 — 브레스트 조약이 오스만에 돌려준 땅에 그대로 진주했다') },
    { d: '1918-04-23', at: 'Ostend', wiki: 'Zeebrugge_Raid', kind: 'naval', name: L('The Zeebrugge and Ostend raids — an attempt to bottle up the U-boat bases behind the Belgian coast', 'ゼーブルッヘ・オーステンデ襲撃——ベルギー沿岸のUボート基地を封じ込める試み', 'Die Raids auf Zeebrügge und Ostende — der Versuch, die U-Boot-Basen hinter der belgischen Küste einzuschließen', 'Рейды на Зеебрюгге и Остенде — попытка запереть базы подлодок за бельгийским побережьем', 'Las incursiones de Zeebrugge y Ostende: un intento de embotellar las bases de submarinos tras la costa belga', '澤布呂赫與奧斯坦德突襲——試圖封鎖比利時海岸後方的U艇基地', '泽布吕赫与奥斯坦德突袭——试图封锁比利时海岸后方的U艇基地', 'Les raids de Zeebruges et d’Ostende — une tentative d’enfermer les bases de sous-marins derrière la côte belge', '제이브뤼허·오스텐더 기습 — 벨기에 해안 뒤편의 U보트 기지를 봉쇄하려는 시도') },
  /* ⚠ SORTED HERE RATHER THAN BY HAND. scripts/build-wars.mjs requires events in date order and the
     block above was written by theatre, which is how the record reads. Array.prototype.sort is stable,
     so two operations that begin on the same day keep the order they were written in. */
  ].sort((a, b) => (a.d < b.d ? -1 : a.d > b.d ? 1 : 0)),
};

export { WW1 };
