/* ============================================================================
 *  IntMap · js/locales/_langs.js — the language list, FOR THE TWO SHELLS   (#R232)
 * ----------------------------------------------------------------------------
 *  「今後IntMapの設定言語を追加するのが、1発で終わるように。」
 *
 *  In the app the language list is the locale DIRECTORY: js/locale-boot.js globs js/locales/ui.*.js
 *  and hands the codes (and their lazy loaders) to js/lang-registry.js. sources.html and science.html
 *  cannot do that — they are static shells served verbatim, with plain <script src> tags and no
 *  bundler — so this script writes the same list out as one generated global they can load.
 *
 *  ⚠ IT IS GENERATED, NOT MAINTAINED, WHICH IS THE WHOLE POINT. `npm run build` runs it (package.json
 *  `prebuild`), and tests/r232-checks.test.mjs regenerates it and fails if the committed copy differs
 *  — so a language added to js/locales/ reaches the reading pages whether or not anybody remembered
 *  this file exists. #R231 shipped 「読み物ページに中国語が一度も届いていなかった」 precisely because
 *  the equivalent list was a literal somebody had to remember.
 *
 *  Run directly:  node scripts/i18n-langs.mjs           (writes)
 *                 node scripts/i18n-langs.mjs --check   (exit 1 if stale)
 * ==========================================================================*/
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'js', 'locales');
const OUT = join(DIR, '_langs.js');

export function localeCodes() {
  return readdirSync(DIR)
    .map((f) => /^ui\.([A-Za-z0-9-]+)\.js$/.exec(f))
    .filter(Boolean)
    .map((m) => m[1].toLowerCase())
    .sort();
}

export function render(codes) {
  return `/* GENERATED by scripts/i18n-langs.mjs — do not edit.
 * (#R232) The language list for sources.html / science.html, which have no bundler and therefore no
 * import.meta.glob. js/lang-registry.js reads this global if it is present; in the app the same list
 * comes from the real module graph (js/locale-boot.js), so neither depends on the other being right.
 * Adding a language means adding js/locales/ui.<code>.js — this file follows on the next build. */
window.IntMapLangCodes = ${JSON.stringify(codes)};
`;
}

const codes = localeCodes();
const text = render(codes);
const check = process.argv.includes('--check');
const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';

if (check) {
  if (current !== text) {
    console.error('js/locales/_langs.js is stale — run `node scripts/i18n-langs.mjs`');
    process.exit(1);
  }
  console.log('js/locales/_langs.js is current (' + codes.length + ' languages)');
} else if (current !== text) {
  writeFileSync(OUT, text);
  console.log('wrote js/locales/_langs.js — ' + codes.join(', '));
} else {
  console.log('js/locales/_langs.js already current (' + codes.length + ' languages)');
}
