/* ============================================================================
 *  IntMap · js/locales/_langs.js — the language list, FOR THE TWO SHELLS   (#R232)
 * ----------------------------------------------------------------------------
 *  「今後IntMapの設定言語を追加するのが、1発で終わるように。」
 *
 *  In the app the language list is the locale DIRECTORY: js/locale-boot.js globs js/locales/ui.*.js
 *  and hands the codes (and their lazy loaders) to js/lang-registry.js. sources.html and science.html
 *  cannot do that — they are static shells served verbatim, with plain <script src> tags and no
 *  bundler — so this script writes the same list out as one generated global they can load.
 *
 *  ⚠ IT IS GENERATED, NOT MAINTAINED, WHICH IS THE WHOLE POINT. `npm run build` runs it (package.json
 *  `prebuild`), and tests/r232-checks.test.mjs regenerates it and fails if the committed copy differs
 *  — so a language added to js/locales/ reaches the reading pages whether or not anybody remembered
 *  this file exists. #R231 shipped 「読み物ページに中国語が一度も届いていなかった」 precisely because
 *  the equivalent list was a literal somebody had to remember.
 *
 *  Run directly:  node scripts/i18n-langs.mjs           (writes)
 *                 node scripts/i18n-langs.mjs --check   (exit 1 if stale)
 * ==========================================================================*/
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'js', 'locales');
const OUT = join(DIR, '_langs.js');

export function localeCodes() {
  return readdirSync(DIR)
    .map((f) => /^ui\.([A-Za-z0-9-]+)\.js$/.exec(f))
    .filter(Boolean)
    .map((m) => m[1].toLowerCase())
    .sort();
}

/* ══ (#R232) …AND WHICH OF THEM ARE STILL (beta) ═════════════════════════════════════════════
   「(beta)表記」 is how a reader learns how finished a translation is (#R223), and until now it was
   a literal somebody typed into the label — which means it says whatever it said the day it was
   typed. It is MEASURED here instead: a language whose inline table is below BETA_AT is beta, and
   the mark appears and disappears on its own as the table fills. The first five are positional
   (their translations are arguments at the call site, not rows in a table) and are never marked.
   ⚠ The two Chinese rows carry their mark in an explicit label in js/lang-registry.js — an explicit
   label always wins, because their reading pages are still partial even though the app is at 100%. */
const BETA_AT = 0.98;
/* ⚠⚠ (#R239) MEASURED BY THE INSTRUMENT, NOT BY A REGEX OF ITS OWN. This used to count lines in
   ui.<code>.js that looked like `'key':` and divide by the same count taken from ui.zh.js — a THIRD
   way of measuring inline coverage, beside scripts/i18n-report.mjs and scripts/i18n-audit.mjs, and
   the one that drifted: after fr and ko were completed to 2,132/2,132 it still marked both (beta),
   because its regex does not match every row shape the appender writes. One quantity, one place
   ([[intmap-recurring-lessons]] G) — so it asks the report, which parses. */
function coverage() {
  const out = JSON.parse(execFileSync(process.execPath,
    [join(ROOT, 'scripts', 'i18n-report.mjs'), '--json'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }));
  const m = new Map();
  for (const r of out.rows) m.set(r.code, r.positional ? 1 : (r.inline / Math.max(1, out.inlineWant)));
  return m;
}
const COVER = coverage();
const inlineCoverage = (code) => (COVER.has(code) ? COVER.get(code) : 0);

export function render(codes) {
  return `/* GENERATED by scripts/i18n-langs.mjs — do not edit.
 * (#R232) The language list for sources.html / science.html, which have no bundler and therefore no
 * import.meta.glob. js/lang-registry.js reads this global if it is present; in the app the same list
 * comes from the real module graph (js/locale-boot.js), so neither depends on the other being right.
 * Adding a language means adding js/locales/ui.<code>.js — this file follows on the next build. */
window.IntMapLangCodes = ${JSON.stringify(codes)};
window.IntMapLangBeta  = ${JSON.stringify(codes.filter((c) => inlineCoverage(c) < BETA_AT))};
`;
}

const codes = localeCodes();
const text = render(codes);
const check = process.argv.includes('--check');
const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';

if (check) {
  if (current !== text) {
    console.error('js/locales/_langs.js is stale — run `node scripts/i18n-langs.mjs`');
    process.exit(1);
  }
  console.log('js/locales/_langs.js is current (' + codes.length + ' languages)');
} else if (current !== text) {
  writeFileSync(OUT, text);
  console.log('wrote js/locales/_langs.js — ' + codes.join(', '));
} else {
  console.log('js/locales/_langs.js already current (' + codes.length + ' languages)');
}
