/* ============================================================================
 *  IntMap · THE UPSTREAM'S DESCRIPTIONS, IN THE READER'S LANGUAGE          (#R695)
 * ----------------------------------------------------------------------------
 *  ⚠ THE MEMBERSHIP OF THIS TABLE IS NOT WRITTEN HERE — scripts/histnames/prose.mjs DERIVES it
 *  from the shipped bundle, and scripts/build-histnames.mjs REFUSES TO BUILD when the classifier
 *  finds a string this table has no line for. So the list cannot silently go stale the way a
 *  hand-kept list does (`.agents/rules/no-ad-hoc-hardcoding.md`); what is written here is the one
 *  thing no measurement can produce, which is the words themselves.
 *
 *  ⚠ THE ENGLISH KEYS ARE THE UPSTREAM'S, MISSPELLINGS AND ALL — «Eastern North Amercian»,
 *  «Plateau fichers», «Zhow states», «Celltic Hallsatt». IntMap never corrects an upstream's own
 *  words (#R650), so the key is copied exactly and an English reader still sees that English. The
 *  translation reads what was MEANT, because a Japanese reader served 「周の諸国」 is not being
 *  told anything false — they are being told what the cartographer said.
 *
 *  ⚠ EVERY LANGUAGE IS ITS OWN TABLE, AND A MISSING ONE COSTS NOTHING. Under the amended policy
 *  (scripts/histnames/langs.mjs) only `jp` is written; a language with no table here contributes
 *  no rows and the upstream English stands, exactly as it did before this round. Adding the other
 *  seven is adding seven keys below — the build, the gate and js/time-borders.js name none of them.
 * ==========================================================================*/
export const PROSE = {
  jp: {
    'Australian aboriginal hunter-gatherers': 'オーストラリア先住民の狩猟採集民',
    'Pampas cultures': 'パンパの諸文化',
    'Patagonian shellfish and marine mammal hunters': 'パタゴニアの貝類・海獣狩猟民',
    'Amazon hunter-gatherers': 'アマゾンの狩猟採集民',
    'Andean hunter-gatherers': 'アンデスの狩猟採集民',
    'Savanna hunter-gatherers': 'サバンナの狩猟採集民',
    'Subarctic forest hunter-gatherers': '亜寒帯林の狩猟採集民',
    'Tasmanian hunter-gatherers': 'タスマニアの狩猟採集民',
    'Caribbean hunter-gatherers': 'カリブ海域の狩猟採集民',
    'Plateau fichers and hunter gatherers': '高原の漁労民・狩猟採集民',
    'Desert hunter-gatherers': '砂漠の狩猟採集民',
    'Finno-Ugric taiga hunter-gatherers': 'フィン・ウゴル系タイガの狩猟採集民',
    'Plain bison hunters': '平原のバイソン狩猟民',
    'West African cereal farmers': '西アフリカの穀作農耕民',
    'Arctic marine mammal hunters': '北極圏の海獣狩猟民',
    'Paleo-Siberian hunter-gatherers': '古シベリア系の狩猟採集民',
    'Eastern North Amercian hunter-gatherers': '北米東部の狩猟採集民',
    'Shellfish gatherers': '貝類採集民',
    'Hindu kingdoms': 'ヒンドゥー諸王国',
    'Greek city-states': 'ギリシアの都市国家',
    'Islamic city-states': 'イスラームの都市国家',
    'Manioc farmers': 'キャッサバ農耕民',
    'Maya chiefdoms and states': 'マヤの首長国と諸国家',
    'Maya city-states': 'マヤの都市国家',
    'Bell-shaped burials culture': '鐘形墓文化',
    'Brushed Pottery culture': '刷毛目土器文化',
    'Eastern Masurian culture': '東マズーリ文化',
    'Plain-Pottery culture': '無文土器文化',
    'Sambian-Nothangian culture': 'ザンビア・ノータンゲン文化',
    'Western Masurian culture': '西マズーリ文化',
    'Maize farmers': 'トウモロコシ農耕民',
    'minor Hindu and Buddhist states': 'ヒンドゥー・仏教系の小国家群',
    'Ethiopian highland farmers': 'エチオピア高原の農耕民',
    'state societies and Aramaean kingdoms': '国家社会とアラム諸王国',
    'Aboriginal tribes': '先住民の諸部族',
    'Celtic kingdoms': 'ケルト諸王国',
    'Chola state': 'チョーラ朝',
    'Late Jomon culture': '縄文時代後期の文化',
    'Mesoamerican city-states and chiefdoms': 'メソアメリカの都市国家と首長国',
    'N. European Bronze Age cultures': '北ヨーロッパ青銅器時代の諸文化',
    'Pandya state': 'パーンディヤ朝',
    'Papuan neolithic farmers': 'パプアの新石器農耕民',
    'Shan states': 'シャン諸国',
    'Austro-Asiatic rice farmers': 'オーストロアジア系の稲作農耕民',
    'Hindu states': 'ヒンドゥー諸国家',
    'Islamic and Hindu states': 'イスラーム・ヒンドゥー諸国家',
    'Malaysian Islamic states': 'マレーのイスラーム諸国',
    'Saharan pastoral nomads': 'サハラの遊牧民',
    'Urnfield cultures': '骨壺墓地文化',
    'minor states under Indian influence': 'インドの影響下にある小国家群',
    'Andean states and chiefdoms': 'アンデスの諸国家と首長国',
    'Arabian pastoral nomads': 'アラビアの遊牧民',
    'Dapenkeng culture': '大坌坑文化',
    'Hindu kingdoms and republics': 'ヒンドゥー諸王国と共和国',
    'Indus valley civilization': 'インダス文明',
    'Iranian pastoralists': 'イラン系の牧畜民',
    'Laotian states': 'ラオスの諸国家',
    'Maya states': 'マヤ諸国家',
    'Mon state': 'モン族の国家',
    'Prot-Altaic pastoralists': '原アルタイ系の牧畜民',
    'Pyu state': 'ピュー国家',
    'Sinhalese kingdom': 'シンハラ王国',
    'Sinhalese kingdoms': 'シンハラ諸王国',
    'Veracruz civilization': 'ベラクルス文明',
    'city-states': '都市国家',
    'Arakan (Indian princely state)': 'アラカン（インド藩王国）',
    'Baltic tribes': 'バルト諸部族',
    'Poverty point culture': 'ポバティ・ポイント文化',
    'Proto-Altaic pastoralists': '原アルタイ系の牧畜民',
    'Zhou states': '周の諸国',
    'Zhow states': '周の諸国',
    'minor Hindu & Buddhist states': 'ヒンドゥー・仏教系の小国家群',
    'minor Hindu and Buddhist kingdoms': 'ヒンドゥー・仏教系の小王国群',
    'minor Hindu kingdoms': 'ヒンドゥー系の小王国群',
    'minor states': '小国家群',
    'Anatolian tribes': 'アナトリアの諸部族',
    'Archaic Amerindian hunter-gatherers': '古期アメリカ先住民の狩猟採集民',
    'Austroasian rice cultures': 'オーストロアジア系の稲作文化',
    'British American colonies': 'イギリス領アメリカ植民地',
    'Cardial Ware culture': '刻文土器文化',
    'Celltic Hallsatt culture': 'ケルトのハルシュタット文化',
    'Croatian kingdom': 'クロアチア王国',
    'Dakapeng culture': '大坌坑文化',
    'Donghu tribes': '東胡の諸部族',
    'Germanic tribes': 'ゲルマン諸部族',
    'Iron Age megalith cultures': '鉄器時代の巨石文化',
    'La Almagra culture': 'ラ・アルマグラ文化',
    'Mahratta states': 'マラーター諸国',
    'Mesoamerican hunter-gatherers and maïze farmers': 'メソアメリカの狩猟採集民とトウモロコシ農耕民',
    'Mysore (Indian princely state)': 'マイソール（インド藩王国）',
    'Pallava state': 'パッラヴァ朝',
    'Proto-Scythian culture': '原スキタイ文化',
    'Proto-Thai cultures': '原タイ系の諸文化',
    'Proto-Tibetan cultures': '原チベット系の諸文化',
    'Rajput kingdoms': 'ラージプート諸王国',
    'Rashtrakuta state': 'ラーシュトラクータ朝',
    'Sikkim (Indian princely state)': 'シッキム（インド藩王国）',
    'Slavic tribes': 'スラヴ諸部族',
    'Slavonic tribes': 'スラヴ諸部族',
    'Tamaulipeco tribes': 'タマウリペコの諸部族',
    'Turcik tribes': 'テュルク系の諸部族',
  },
};
