/* GENERATED by scripts/i18n-langs.mjs — do not edit.
 * (#R232) The language list for sources.html / science.html, which have no bundler and therefore no
 * import.meta.glob. js/lang-registry.js reads this global if it is present; in the app the same list
 * comes from the real module graph (js/locale-boot.js), so neither depends on the other being right.
 * Adding a language means adding js/locales/ui.<code>.js — this file follows on the next build. */
window.IntMapLangCodes = ["de","en","es","fr","jp","ko","ru","zh","zh-hans"];
window.IntMapLangBeta  = ["fr","ko","zh","zh-hans"];
