/* ============================================================================
 *  IntMap · UI STRINGS — German (Deutsch)   (#R221)
 * ----------------------------------------------------------------------------
 *  ONE LANGUAGE, ONE FILE. Moved out of js/i18n.js verbatim — not a character of the text below
 *  was retyped; only the object it sits in changed owner. See js/lang-registry.js for what a new
 *  language costs (this file, one row in LANGS, one import in src/main.js) and for why the
 *  the `inline` table exists (a NEW language uses it; the first five do not).
 *
 *  ⚠ A KEY MISSING FROM THIS FILE FALLS BACK TO ENGLISH, PER KEY — js/i18n.js chains the table
 *  onto the English one with Object.create, so a young translation shows its own language wherever
 *  it has one and English only where it does not. Nothing has to be kept in sync by hand.
 * ========================================================================== */
window.IntMapLang.define('de', { ui: {
      lnkTerms:"Nutzungsbedingungen", lnkPrivacy:"Datenschutzerklärung", legalTabTerms:"Bedingungen", legalTabPrivacy:"Datenschutz", commAddImage:"Bild hinzufügen",
      tabNews:"Nachrichten", tabSaved:"★ Gespeichert", tabInfo:"Informationen", tabCompanies:"Unternehmen", tabStats:"Länder", tabCommunity:"Community",
      searchPh:"Nachrichten / Orte suchen...", filterCountriesPh:"Länder filtern...", filterCompaniesPh:"Unternehmen filtern...", pickCountryMap:"Land auf der Karte wählen", searchBtn:"Suchen", searchLoadBtn:"Suchen / Laden", msPh:"Beliebigen Ort auf der Erde suchen...",
      viewMap:"Karte", viewSat:"Satellit", flat:"Flach", globe:"Globus", threeD:"⛰️ 3D", gridBtn:"🌐 Gitter", gridLayer:"🌐 Gitter & Beschriftung",
      settings:"Einstellungen", modalTitle:"Einstellungen", close:"Schließen", btnApply:"Übernehmen", lblLang:"Sprache",
      setSecAppearance:"Aussehen", setSecLayout:"Layout & Panels", setSecMap:"Kartenverhalten", setSecUnits:"Einheiten & Zeit", setSecNews:"Nachrichten & Ticker", setSecAI:"KI", setSecKeys:"Integrationen & Schlüssel", setSecAbout:"Info & Support",
      lblTheme:"Darstellung", optAuto:"Systemstandard", optLight:"Hell", optDark:"Dunkel", optClassic:"Klassisch", optCyber:"Cyber",
      lblMapColor:"Kartenfarbe", mapColorAuto:"Wie Darstellung", mapColorLight:"Hell (weiß)", mapColorDark:"Dunkel (schwarz)",
      lblUnits:"Maßeinheiten", unitBoth:"Metrisch + Imperial", unitMetric:"Nur metrisch", unitImperial:"Nur imperial",
      lblTempUnit:"Temperatur", tempBoth:"°C + °F", tempC:"Nur °C", tempF:"Nur °F",
      lblTz:"Zeitzone", tzSearch:"Zeitzone suchen…", optLocal:"Lokal (Systemstandard)",
      lblNewsLang:"Nachrichtensprachen", newsLangUi:"Nur aktuelle Sprache", newsLangMultiSel:"Mehrere Sprachen…", newsLangMulti:"Alle Sprachen (Titel automatisch übersetzen)", newsLangHint:"Schlagzeilen aller Sprachen erscheinen gemeinsam; mit einem KI-Schlüssel werden die Titel automatisch übersetzt.",
      lblAiLocate:"KI-Standortanalyse", aiLocManual:"Manuell (Schaltfläche)", aiLocAuto:"Automatisch für alle Nachrichten",
      lblSidebarStyle:"Seitenleiste", sidebarOpaque:"Solide (Standard)", sidebarTranslucent:"Mattglas", sidebarGlass2:"Mattglas (transparenter)",
      lblLabelLang:"Ortsbeschriftungen", labelLangUi:"Wie App-Sprache", labelLangLocal:"Lokale Sprache (Originalschrift)", labelLangEn:"Immer Englisch",
      lblFlatPan:"Flache Kartenansicht", flatPanFixed:"Fester Ausschnitt (Europa)", flatPanFree:"Frei schwenken (Welt umrunden)",
      /* (#R180) Render-Engine */
      lblEngine:"Karten-Engine", engineMapLibre:"MapLibre — 2-D/3-D-Karte (Vorgabe)", engineCesium:"Cesium — echter 3-D-Globus mit realem Gelände",
      engineHint:"Cesium stellt die Erde in jedem Zoom als echtes Ellipsoid dar, mit denselben Satellitenbildern und denselben Höhendaten. Sie wird nur bei Auswahl heruntergeladen, und der Wechsel lädt die Seite neu. Höhenlinien und das geschlossene 3-D-Körper-Werkzeug bleiben MapLibre vorbehalten.",
      engineSwitching:"Engine wird gewechselt — neu laden…", engineFellBack:"Cesium konnte nicht starten, diese Sitzung läuft daher mit MapLibre.",
      engineActive:"Aktiv: ",
      /* (#R171) Neigungsgrenze + Kamerahöhe */
      lblTiltLimit:"Neigungsgrenze der Karte", tiltStandard:"Standard — bis 78° (Vorgabe)", tiltUnlimited:"Unbegrenzt — der volle Bereich 0–180°",
      tiltHint:"Unbegrenzt lässt die Karte über den Horizont hinaus kippen, bis die Kamera senkrecht nach oben blickt. Jenseits von 180° wiederholt sich die Ansicht mit umgekehrter Blickrichtung — per Rechtsklick auf den Kompass lässt sich jeder Winkel von 0 bis 360 eingeben.",
      lblEyeAlt:"Kamerahöhe in der Anzeige", eyeAltOff:"Aus (Vorgabe)", eyeAltOn:"An — Höhe des Blickpunkts zeigen", lblNightSide:"Tag-/Nachtschattierung", nightSideOn:"An (Vorgabe) — Nachtseite abdunkeln & Stadtlichter zeigen", nightSideOff:"Aus — gleichmäßig beleuchteter Globus",
      lblNavSens:"Navigationsempfindlichkeit", lblNavZoom:"Zoom", lblNavPan:"Schwenken",
      satKeysTitle:"Satellitenbilder (BYOK)", satKeyHint:"Geben Sie einen API-Schlüssel ein, um diese Anbieter im Satelliten-Panel freizuschalten. Schlüssel werden nur in diesem Browser gespeichert.",
      aisKeyLabel:"Live-Schiffsverkehr (AISstream-Schlüssel)", aisKeyHint:"Holen Sie sich einen kostenlosen Schlüssel bei aisstream.io und fügen Sie ihn hier ein. Wird nur in diesem Browser gespeichert.",
      aiSecTitle:"KI-Funktionen", aiSecHint:"Integrierte KI — nach der Anmeldung kostenlos nutzbar (bis zu 10×/Tag). Kein API-Schlüssel erforderlich.",
      blueberryBtn:"Unterstützen", borders:"Ländergrenzen", countries:"Länder (Info)", placeNames:"Ortsnamen", geoLabels:"Gewässer- & Geländenamen", adminBounds:"Bundesland-/Provinzgrenzen", roadsLayer:"Straßen", railLayer:"Eisenbahnen", favLayers:"★ Favoriten",
      measureMenuBtn:"Messen", measureDistBtn:"📏 Distanz / Fläche", drawBtn:"✏️ Zeichnen", vol3dBtn:"🧊 3-D-Volumen", droneBtn:"🛸 Drohne", radiusBtn:"⭕ Radius", objectsBtn:"🗂 Objekte", mScreenshot:"Karten-Screenshot", shareMenuBtn:"Teilen", shareLinkBtn:"Teilen / Link", screenshotBtn:"Karten-Screenshot (blendet Bedienelemente aus, behält Legenden)", layersBtn:"Ebenen ▾", uploadGeoJSON:"GeoJSON hochladen",
      lblDataSources:"Datenquellen", viewDataSources:"Kurzliste in der App", lblScience:"Wissenschaft & Logik", viewScience:"Wie jede Simulation rechnet ↗", lblSourcesPage:"Datenquellen", viewSourcesPage:"Datenquellen-Seite öffnen ↗", lblNewsCountries:"Nachrichten-Länder", newsCountriesHint:"Lassen Sie das Feld leer für weltweite Nachrichten.",
      lyrGrpGeo:"Strategische Geografie", lyrGrpStrat:"Strategische Netze", lyrGrpOthers:"Weitere (Beta)",
      filtCiv:"Zivil", filtMil:"Militär", filtAll:"Alle", thermWin24:"Letzte 24 Std", thermWin48:"Letzte 48 Std", thermWin72:"Letzte 72 Std",
      tlTitle:"Zeitmaschine", tlMachine:"Zeitmaschine", tlToday:"Heute", tl10y:"−10 J", tl5y:"−5 J", tlNow:"Jetzt",
      lblPinMode:"Nachrichten-Pin-Position", pinModeLoc:"Ort des Themas", pinModePub:"Ort des Herausgebers",
      aiTranslateTitles:"Titel übersetzen", aiViewSumBtn:"Diese Ansicht zusammenfassen",
      /* (#R37) full DE coverage — the 184 keys that were falling back to English (measure/stats/community/AI/satellite/context). */
      loading:"Artikel werden geladen...", noMatch:"Keine Ergebnisse gefunden.", networkError:"Nachrichten konnten nicht geladen werden. Erneuter Versuch…", emptyHint:"Kein Tab ausgewählt — die Karte ist frei.<br>Wählen Sie oben einen Tab, um Inhalte anzuzeigen.",
      dashCatMil:"Militärbasen", dashCatTech:"Technik / Cyber", dashCatMar:"Maritim / Engpässe", dashCatGeo:"Geo / Klima", readWiki:"Auf Wikipedia lesen ↗",
      measure:"Messen", areaTool:"Fläche", radius:"Radius", vol3dTool:"3-D-Volumen", points:"Punkte", total:"Gesamt", perimeter:"Umfang", area:"Fläche", clear:"Löschen", undoPt:"Punkt zurück",
      measureHint:"Klicken zum Hinzufügen von Punkten · Doppelklick zum Abschließen", areaHint:"3+ Punkte zum Umschließen · Doppelklick zum Abschließen", radiusHint:"Klicken Sie auf die Karte, um einen Kreis zu platzieren. Mehrere Kreise möglich.", addCircle:"Kreis platzieren", removeAll:"Alle löschen", color:"Farbe",
      statPop:"Bevölkerung", statGdp:"BIP (nominal)", statGdpPc:"BIP pro Kopf", statGdpPPP:"BIP (KKP)", statGdpPcPPP:"BIP pro Kopf (KKP)", statArea:"Fläche", statDensity:"Bevölkerungsdichte", statRegion:"Region", statSub:"Subregion", statCapital:"Hauptstadt", statCurrency:"Währung", statLang:"Sprachen", statHDI:"HDI", statDem:"Demokratie-Index", statMil:"Militärausgaben", statLife:"Lebenserwartung", statInet:"Internetnutzer",
      details:"Details ↗", loadingData:"Länderdaten werden geladen...", dataNA:"k. A.", noData:"Länderdaten nicht verfügbar.",
      sortGdp:"BIP", sortPop:"Bev.", sortArea:"Fläche", sortName:"A–Z", sortHDI:"HDI", sortMil:"Mil.$", elev:"Höhe", bearing:"Peilung", presetNone:"— wählen —", presetLbl:"Bereichsvorgaben", opacity:"Deckkraft", circumference:"Umfang",
      spRunway:"Start-/Landebahn", spGarrison:"Garnison", spOperator:"Betreiber", spEstd:"Gegründet", spAircraft:"Flugzeuge", spType:"Typ", spCapacity:"Kapazität", spDepth:"Tiefe", spOutput:"Förderung", spReserves:"Reserven",
      widgetsBtn:"Widgets", measureBtn:"📏 Messen", areaBtn:"📐 Fläche",
      ctxDropPin:"Pin setzen", ctxMeasureFrom:"Messung beginnen", ctxPostHere:"In der Community posten", ctxDistFrom:"Entfernung vom vorherigen Pin", ctxCopy:"Koordinaten kopieren", ctxClearPins:"Alle Pins entfernen", ctxThisPoint:"Dieser Punkt", coords:"Koordinaten", depth:"Tiefe", climate:"Klima",
      lyrEEZ:"Meeres-AWZ / 12 sm", lyrShips:"Live-Schiffsverkehr", lyrPlanes:"Live-Flugverkehr", lyrSats:"Live-Satelliten", lyrThermal:"Wärmeanomalien (Brände)", planesZoomHint:"Hineinzoomen, um Live-Flugzeuge zu laden", planesAreaHint:"Hineinzoomen — Live-Flugzeuge decken den mittleren Bereich dieser Ansicht ab", poiLabels:"Orte, Betriebe & Einrichtungen", shipsZoomHint:"Hineinzoomen, um Live-Schiffe zu laden", aisNoKey:"Live-Schiffe benötigen einen kostenlosen AISstream.io-API-Schlüssel — in den Einstellungen hinzufügen.", trafficFilter:"Filter", lyrTime:"Ebenen-Datum",
      commAdd:"+ Neuer Beitrag", commAddArmed:"Auf die Karte klicken, um einen Pin zu setzen", commTitle:"Titel", commBody:"Teilen Sie eine Beobachtung, Frage oder Theorie...", commPost:"Posten", commCancel:"Abbrechen", commEmpty:"Noch keine Beiträge. Klicken Sie auf \"+ Neuer Beitrag\", um die Diskussion zu starten.", commComment:"Kommentar", commLocate:"Auf Karte zeigen", commDelete:"Löschen", commReply:"Antworten", commWrite:"Kommentar schreiben...", commPostNew:"Neuer Beitrag", commPlacedAt:"Platziert bei", commSortHot:"Angesagt", commSortNew:"Neu", commSortTop:"Top", commSearchPh:"Beiträge suchen…", commInView:"Im Sichtfeld", commCat:"Kategorie", commCatAll:"Alle", commEdit:"Bearbeiten", commEdited:"bearbeitet", commEditPost:"Beitrag bearbeiten", commSaveEdit:"Änderungen speichern", commNoMatch:"Keine Beiträge entsprechen Ihren Filtern.",
      compare:"Vergleichen", compareEmpty:"Länderzeilen antippen zum Auswählen und Vergleichen.", coCompareEmpty:"Unternehmenszeilen antippen zum Auswählen und Vergleichen.", compareView:"Vergleich anzeigen", compareClear:"Löschen", back:"Zurück", deletePin:"Löschen",
      satCtrlTitle:"Satellitenbilder", satProvider:"Anbieter", satDate:"Aufnahmedatum", satLatest:"Neueste verfügbar", satMosaicSuffix:"wolkenloses Mosaik", satLocked:"API-Schlüssel hinzufügen", satPrevDay:"Vorheriger Tag", satNextDay:"Nächster Tag", satKeyConnected:"Verbunden", satKeyNone:"Kein Schlüssel", satErrAuth:"{provider}: Authentifizierung fehlgeschlagen — API-Schlüssel prüfen", satErrTiles:"{provider}: Bilder nicht verfügbar — auf Ersatz umgeschaltet",
      aiProvider:"KI-Anbieter", aiModel:"Modell", aiApiKey:"API-Schlüssel", aiKeyConnected:"Verbunden", aiKeyNone:"Kein Schlüssel", aiGetKey:"Schlüssel erhalten ↗", aiOnDevice:"Läuft lokal in Chrome — kein API-Schlüssel nötig.", aiTest:"Verbindung testen", aiTesting:"Test läuft…", aiTestOk:"Verbindung OK ✓", aiNoKey:"Fügen Sie zuerst einen KI-API-Schlüssel unter Einstellungen → KI-Funktionen hinzu.", aiNoVision:"Dieses Modell kann keine Bilder lesen. Wählen Sie GPT-4o, Claude 3.5 Sonnet oder Gemini 1.5 Pro.", aiChromeUnavail:"Die in Chrome integrierte KI ist hier nicht verfügbar. Verwenden Sie Chrome 127+ mit aktivierter On-Device-KI oder einen anderen Anbieter.", aiThinking:"KI analysiert…", aiError:"KI-Anfrage fehlgeschlagen", aiCopy:"Kopieren", aiCopied:"Kopiert ✓", aiClose:"Schließen", aiRetry:"Wiederholen",
      aiGeoBtn:"✨ Alle Nachrichten per KI verorten", aiGeoBtnSub:"✨ Thema per KI verorten", aiGeoBtnPub:"✨ Herausgeber per KI verorten", aiGeoBusy:"Verorten…", aiGeoNone:"Nichts zu verorten.", aiGeoDone:"{n} Meldungen verortet", aiGeoErr:"Geokodierung fehlgeschlagen", aiTransBusy:"Übersetzen…", aiTransDone:"{n} Titel übersetzt", aiTransNone:"Titel bereits in Ihrer Sprache.", aiTranslate:"Übersetzen", aiShowOriginal:"Original", aiTransNoText:"Kein Artikeltext zum Übersetzen — versuchen Sie die Web-Ansicht.",
      aiSumBtn:"Dieses Gebiet mit KI zusammenfassen", popInArea:"Bevölkerung in diesem Gebiet", popCalcing:"Berechne Bevölkerung…", popFail:"Bevölkerungsabfrage fehlgeschlagen — erneut versuchen.", newsInArea:"Nachrichten in diesem Gebiet", elevProfile:"Höhenprofil", finalizeMeas:"Auf Karte behalten", aiSumTitle:"Gebiets-Briefing", aiSumSub:"{n} Nachrichten-Pins im ausgewählten Gebiet", aiSumNoArea:"Zeichnen Sie zuerst ein Gebiet oder platzieren Sie einen Kreis.", aiSumNoNews:"Keine Nachrichten-Pins in diesem Gebiet.", aiViewSumTitle:"Was auf dem Bildschirm passiert",
      aiVisHead:"KI-Änderungserkennung", aiVisBtn:"Änderungen erkennen", aiVisTitle:"Satelliten-Änderungsbericht", aiVisSub:"Vergleich {a} → {b}", aiVisBefore:"Vorher", aiVisAfter:"Nachher", aiVisCapturing:"Bilder werden erfasst…", aiVisPickDates:"Wählen Sie zwei Daten zum Vergleich.", aiVisNeedsDated:"Wechseln Sie im Satellitenmodus zu einem datumsfähigen Anbieter (MODIS / VIIRS / Sentinel-2).", aiVisCapFail:"Kartenbilder konnten nicht erfasst werden.",
      mTitleMap:"Karte", mTitleTools:"Werkzeuge", mDone:"Fertig" 
} });
