-- ============================================================================
--  #R334 — 記事ではなく「出来事」を主語にする
-- ----------------------------------------------------------------------------
--  「同一出来事の記事を Event へクラスタリングする … 一覧と地図の主語を、記事ではなく Event に
--    する … 誤統合を運用者が Merge / Split / Reassign で修正できるようにする」
--
--  `current_news` は記事単位で、実質の識別子が (lang, link) である。その形では出来事を持てない。
--  実測（本番 1,651 行・72 時間）で分かったことを、そのまま設計の根拠にしている:
--
--    · 同じ出来事の記事は言語ごとに別の link を持ち、両者を結ぶ列が無い。
--    · `fetched_at` は refresh-news が毎 run 無条件に上書きするので、「最初に観測した時刻」は
--      原理的に復元できない。upsert は破壊的で、前の title も subject も残らない。
--    · prune が pub_date < now-72h を無条件に DELETE するので、出来事をこの表に置くと
--      ★保存も共有 URL も 72 時間で失われる。
--    · Sinclair 3 局・Hearst 4 局が同一タイトルを配信していた。媒体名で数えると 1 つの出来事が
--      「7 媒体が報じた」に化ける。だから独立数は source_family で数える。
--
--  ⚠ この migration は `current_news` を 1 バイトも触らない。あれは article mode の
--    fallback として生きている（docs/NEWS-EVENTS.md §12）。
--
--  ⚠ 保持期間はここでは強制しない。記事 72 時間 / Event 30 日は ingest 側の仕事で、
--    その根拠と改訂は docs/NEWS-EVENTS.md §8 と CONSTITUTION.md §5 にある。
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
--  0. pgvector — 言い換えを拾うための最近傍検索
-- ----------------------------------------------------------------------------
--  決定論のトークン一致は「Walmart の決算」と「Walmart が Apple Pay に対応」を正しく分けるが、
--  同じ出来事の言い換えは拾えない。実測の ablation（docs/NEWS-EVENTS.md §5.1）で、決定論だけの
--  圧縮率は 1.20〜1.37 倍で頭打ちだった。
--  ⚠ Supabase の作法どおり extensions スキーマへ入れる。型は extensions.vector で明示参照する
--    （search_path に依存させない）。
-- ─────────────────────────────────────────────────────────────────────────────
create extension if not exists vector with schema extensions;

-- ─────────────────────────────────────────────────────────────────────────────
--  1. news_sources — 媒体の正本 (Source Registry)
-- ----------------------------------------------------------------------------
--  ⚠ これが唯一の媒体一覧である。js/news-sources.js が持っているのは「到着した記事の publisher を
--    数える表示フィルタ」であって収集対象ではない。二重に持たない。
--
--  source_family が独立数の単位である。KOMO / WXLV / WJAC は別の name を持つが同じ family で、
--  実測で同一タイトルを配信していた。name で数えると coverage が水増しされる。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_sources (
  id                  text        primary key,
  name                text        not null,
  slug                text        not null unique,
  aliases             text[]      not null default '{}',
  domains             text[]      not null default '{}',
  languages           text[]      not null default '{en}',
  country             text,
  region              text,
  source_type         text        not null
                        check (source_type in ('wire','broadcaster','newspaper','digital','official','aggregator')),
  source_family       text        not null,
  homepage_url        text,
  terms_url           text,
  attribution         text,
  license_notes       text,
  hq_lng              double precision,
  hq_lat              double precision,
  enabled             boolean     not null default true,
  priority            smallint    not null default 100,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
--  2. news_source_feeds — 1 媒体は複数のフィードを持つ
-- ----------------------------------------------------------------------------
--  ⚠ category はここにある。実測で、媒体のセクション別 RSS は 15/15 が稼働し、6 カテゴリを
--    フィード自体が持っていた。カテゴリの第一手段は分類器ではなく「どのフィードから来たか」である。
--  鮮度と失敗はフィード単位で持つ。「取得できなかった」を「そこには何も無い」と描かないため
--    （DECISIONS.md「描いたものの出所と鮮度を必ず画面に出す」）。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_source_feeds (
  id                  bigint      generated by default as identity primary key,
  source_id           text        not null references public.news_sources(id) on delete cascade,
  url                 text        not null unique,
  collection          text        not null
                        check (collection in ('direct_rss','google_news_site','google_news_topic')),
  category            text
                        check (category in ('world','politics','business','technology',
                                            'science_health','climate_weather','disasters','society')),
  enabled             boolean     not null default true,
  expected_interval_s integer     not null default 1200,
  last_success_at     timestamptz,
  last_item_count     integer,
  last_error_at       timestamptz,
  last_error          text,
  created_at          timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
--  3. news_articles — 正規化された記事 1 本
-- ----------------------------------------------------------------------------
--  ⚠ identity は URL ではなく fingerprint である。Google News の link は
--    news.google.com/rss/articles/CBMi… の集約リダイレクトで、同じ記事が直接 RSS 経由で来ると
--    別の文字列になる。url_fingerprint は正規化した canonical_url の SHA-256、
--    title_fingerprint は正規化した見出しの SHA-256 で、後者が転載を捕まえる。
--
--  ⚠ subject_reasons を持つ。IntMapNewsGeo は why[] を返しているのに、現行の analyzeContext は
--    それを受け取らずに捨てている。なぜその地点になったかを後から説明できないと、
--    誤った地点を運用者が直せない。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_articles (
  id                  bigint      generated by default as identity primary key,
  source_id           text        not null references public.news_sources(id) on delete restrict,
  feed_id             bigint      references public.news_source_feeds(id) on delete set null,
  canonical_url       text        not null,
  provider_url        text,
  url_fingerprint     text        not null unique,
  title               text        not null,
  title_fingerprint   text        not null,
  description         text,
  language            text        not null default 'en',
  published_at        timestamptz,
  provider_updated_at timestamptz,
  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  provider_category   text,
  entities            jsonb       not null default '{}'::jsonb,
  subject_lng         double precision,
  subject_lat         double precision,
  subject_name_en     text,
  subject_type        text,
  subject_confidence  real,
  subject_reasons     text[]      not null default '{}',
  embedding           extensions.vector(1536),
  embedding_model     text,
  embedding_version   smallint,
  correction_status   text        not null default 'none'
                        check (correction_status in ('none','corrected','retracted')),
  status              text        not null default 'active'
                        check (status in ('active','removed')),
  processing_version  smallint    not null default 1
);

-- ─────────────────────────────────────────────────────────────────────────────
--  4. news_events — 出来事 1 件
-- ----------------------------------------------------------------------------
--  ⚠ public_id は merge しても壊れない。統合された側は行を消さず status='merged' と
--    merged_into を立てるので、古い ID を持った保存・共有 URL・Atlas 参照・ブラウザ履歴は
--    canonical へ解決できる。行を消す設計は、利用者のリンクを黙って壊す設計である。
--
--  ⚠ article_count と independent_source_count を分ける。前者は記事の本数、後者は
--    source_family の異なり数。実測で「Mount Fuji」6 件のうち 3 件が Sinclair 系列の
--    同一タイトルだった——「6 媒体が報じた」は嘘になる。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_events (
  id                        bigint      generated by default as identity primary key,
  public_id                 text        not null unique,
  merged_into               bigint      references public.news_events(id) on delete set null,
  representative_title      text        not null,
  representative_article_id bigint      references public.news_articles(id) on delete set null,
  primary_category          text        not null default 'world'
                              check (primary_category in ('world','politics','business','technology',
                                                          'science_health','climate_weather','disasters','society')),
  secondary_categories      text[]      not null default '{}',
  category_confidence       real,
  classifier_version        smallint,
  category_override         boolean     not null default false,
  rep_lng                   double precision,
  rep_lat                   double precision,
  rep_place_name_en         text,
  location_confidence       real,
  location_evidence         jsonb,
  location_override         boolean     not null default false,
  first_published_at        timestamptz,
  first_seen_at             timestamptz not null default now(),
  last_article_at           timestamptz,
  materially_updated_at     timestamptz,
  article_count             integer     not null default 0,
  independent_source_count  integer     not null default 0,
  cluster_confidence        real,
  algorithm_version         smallint    not null default 1,
  status                    text        not null default 'active'
                              check (status in ('active','merged','archived')),
  manual_lock               boolean     not null default false,
  reviewed_at               timestamptz,
  -- ⚠⚠ auth.users への FOREIGN KEY を **意図的に張っていない**。
  --   public.delete_account_data() は `_owned_by_user_cols()` で「auth.users への単一列 FK」を
  --   **行の所有者を表す列**として発見し、その行を削除する（20260820120000_delete_account_txn.sql:43）。
  --   reviewed_by は所有ではなく **監査**である——運用者がアカウントを消したときに、その人が
  --   確認した公開の出来事まで消えるのは、誰も意図していない削除である。
  --   参照整合性より「消えてはいけないものが消えない」を採る。消えた運用者の uuid は
  --   宙に浮くが、それは監査記録として正しい（誰が確認したかは後から変わらない）。
  reviewed_by               uuid,
  summary                   text,
  summary_evidence          jsonb,
  summary_version           smallint,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  -- 統合された行は、統合先を必ず名指す。名指さない 'merged' は行方不明の別名でしかない。
  constraint news_events_merged_points_somewhere
    check (status <> 'merged' or merged_into is not null),
  -- 自分自身へは統合できない（1 行の輪は解決ループになる）。
  constraint news_events_no_self_merge
    check (merged_into is null or merged_into <> id)
);

-- ─────────────────────────────────────────────────────────────────────────────
--  5. news_event_articles — Event と記事の関係
-- ----------------------------------------------------------------------------
--  relation は 3 つ。'related_context' を同じ Event に吸収しないために型で分けてある。
--  ⚠ 部分 unique index が「1 記事は primary な Event を高々 1 つしか持たない」を強制する。
--    関連としてなら複数の Event にぶら下がってよい。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_event_articles (
  event_id               bigint      not null references public.news_events(id) on delete cascade,
  article_id             bigint      not null references public.news_articles(id) on delete cascade,
  relation               text        not null
                           check (relation in ('same_event','update','related_context')),
  assignment_score       real,
  deterministic_features jsonb,
  assigned_by            text        not null
                           check (assigned_by in ('deterministic','embedding','llm','human')),
  decision_reason        text,
  manual_override        boolean     not null default false,
  algorithm_version      smallint    not null default 1,
  created_at             timestamptz not null default now(),
  primary key (event_id, article_id)
);

create unique index if not exists news_event_articles_one_primary
  on public.news_event_articles (article_id)
  where relation in ('same_event','update');

-- ─────────────────────────────────────────────────────────────────────────────
--  6. news_cluster_decisions — なぜその判定になったか
-- ----------------------------------------------------------------------------
--  誤統合は必ず起きる。起きたときに「何が決め手だったのか」を答えられないと、運用者は
--  勘で直すことになる。⚠ この表だけは admin 読みである（モデルの生の応答と費用が入る）。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_cluster_decisions (
  id                  bigint      generated by default as identity primary key,
  article_id          bigint      references public.news_articles(id) on delete cascade,
  candidate_event_ids bigint[]    not null default '{}',
  scores              jsonb       not null default '{}'::jsonb,
  chosen_event_id     bigint      references public.news_events(id) on delete set null,
  relation            text,
  deterministic_evidence jsonb,
  embedding_similarity real,
  llm_response        jsonb,
  llm_model           text,
  llm_tokens_in       integer,
  llm_tokens_out      integer,
  estimated_cost_usd  numeric(10,6),
  manual_correction   boolean     not null default false,
  algorithm_version   smallint    not null default 1,
  created_at          timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
--  7. news_event_i18n — Event の訳文
-- ----------------------------------------------------------------------------
--  一次措置として lang は 'ja' だけを使う（docs/NEWS-EVENTS.md §7）。
--  ⚠ 翻訳はサーバー側で生成してここへ永続化する。クライアントの AI 枠を消費せず、
--    未ログインの読者にも同じものが見える。列の形は言語を増やしても変わらない。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_event_i18n (
  event_id        bigint      not null references public.news_events(id) on delete cascade,
  lang            text        not null,
  title           text        not null,
  summary         text,
  place_name      text,
  translator      text,
  translated_at   timestamptz not null default now(),
  source_version  smallint    not null default 1,
  primary key (event_id, lang)
);

-- ─────────────────────────────────────────────────────────────────────────────
--  8. saved_news_events — ★ を付けた Event
-- ----------------------------------------------------------------------------
--  ⚠ 既存の favorites は 1 バイトも触らない。あれは記事の link を持ち、article mode で
--    今までどおり動き続ける。ここは Event 側の受け皿である。
--  ⚠ 通常の retention でこれを失わない（docs/NEWS-EVENTS.md §8）。
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.saved_news_events (
  id          bigint      generated by default as identity primary key,
  user_id     uuid        not null references auth.users(id) on delete cascade,
  event_id    bigint      not null references public.news_events(id) on delete cascade,
  event_title text,
  created_at  timestamptz not null default now(),
  unique (user_id, event_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
--  9. INDEXES — 実際に投げる問い合わせの形に合わせる
-- ----------------------------------------------------------------------------
--  ⚠ current_news は subject_lng/lat に index を 1 本も持っていない。同じ穴を開けない。
--  ⚠ ANN index はデータが入ってから作るほうが良い品質になるので、ここでは張らない
--    （空の表に対する ivfflat は無意味なリストを作る）。Phase C で行数を測ってから足す。
-- ─────────────────────────────────────────────────────────────────────────────
create index if not exists idx_news_sources_enabled       on public.news_sources (enabled) where enabled;
create index if not exists idx_news_source_feeds_source   on public.news_source_feeds (source_id);
create index if not exists idx_news_source_feeds_enabled  on public.news_source_feeds (enabled) where enabled;

create index if not exists idx_news_articles_published    on public.news_articles (published_at desc);
create index if not exists idx_news_articles_first_seen   on public.news_articles (first_seen_at desc);
create index if not exists idx_news_articles_source       on public.news_articles (source_id);
create index if not exists idx_news_articles_titlefp      on public.news_articles (title_fingerprint);
create index if not exists idx_news_articles_geo          on public.news_articles (subject_lat, subject_lng)
  where subject_lat is not null;

create index if not exists idx_news_events_updated        on public.news_events (materially_updated_at desc)
  where status = 'active';
create index if not exists idx_news_events_last_article   on public.news_events (last_article_at desc)
  where status = 'active';
create index if not exists idx_news_events_category       on public.news_events (primary_category, materially_updated_at desc)
  where status = 'active';
create index if not exists idx_news_events_geo            on public.news_events (rep_lat, rep_lng)
  where status = 'active' and rep_lat is not null;
create index if not exists idx_news_events_merged_into    on public.news_events (merged_into)
  where merged_into is not null;

create index if not exists idx_news_event_articles_article on public.news_event_articles (article_id);
create index if not exists idx_news_cluster_decisions_art  on public.news_cluster_decisions (article_id);
create index if not exists idx_news_cluster_decisions_at   on public.news_cluster_decisions (created_at desc);
create index if not exists idx_saved_news_events_user      on public.saved_news_events (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
--  10. ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------
--  読める: 公開の地図に出るものは全部（未ログインでも地図が出せなければならない）。
--  書ける: service_role だけ。例外は saved_news_events で、そこは本人だけ。
--  ⚠ news_cluster_decisions は admin だけ。モデルの生の応答と費用が入る。
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.news_sources           enable row level security;
alter table public.news_source_feeds      enable row level security;
alter table public.news_articles          enable row level security;
alter table public.news_events            enable row level security;
alter table public.news_event_articles    enable row level security;
alter table public.news_cluster_decisions enable row level security;
alter table public.news_event_i18n        enable row level security;
alter table public.saved_news_events      enable row level security;

drop policy if exists news_sources_select_all on public.news_sources;
create policy news_sources_select_all on public.news_sources
  for select to anon, authenticated using (true);

drop policy if exists news_source_feeds_select_all on public.news_source_feeds;
create policy news_source_feeds_select_all on public.news_source_feeds
  for select to anon, authenticated using (true);

drop policy if exists news_articles_select_active on public.news_articles;
create policy news_articles_select_active on public.news_articles
  for select to anon, authenticated using (status = 'active');

drop policy if exists news_events_select_all on public.news_events;
create policy news_events_select_all on public.news_events
  for select to anon, authenticated using (true);

drop policy if exists news_event_articles_select_all on public.news_event_articles;
create policy news_event_articles_select_all on public.news_event_articles
  for select to anon, authenticated using (true);

drop policy if exists news_event_i18n_select_all on public.news_event_i18n;
create policy news_event_i18n_select_all on public.news_event_i18n
  for select to anon, authenticated using (true);

-- 判定の監査は admin だけ。profiles.is_admin を見るのは既存の表と同じ形。
drop policy if exists news_cluster_decisions_admin on public.news_cluster_decisions;
create policy news_cluster_decisions_admin on public.news_cluster_decisions
  for select to authenticated
  using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

-- ⚠ 運用者の Merge / Split / Reassign（`admin.html` の News Events タブ・docs/NEWS-EVENTS.md §11）は
--   まだ存在しない。**その UI と同じ変更で** `geo_pins` と同じ形の
--   `for all to authenticated using (public.is_admin())` を足すこと——
--   使う相手が無いうちに書き込み privilege を配ると、**誰も試していない権限**が本番に居座る。
--   今この表を書くのは service_role（ingest）だけである。
drop policy if exists saved_news_events_rw_own on public.saved_news_events;
create policy saved_news_events_rw_own on public.saved_news_events
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- ─────────────────────────────────────────────────────────────────────────────
--  11. GRANTS
-- ----------------------------------------------------------------------------
--  ⚠ ポリシーだけでは読めない。grant が要る（#R155 が同じ穴を塞いでいる）。
--  ⚠ 書き込みの grant は anon / authenticated に一切与えない。service_role は RLS を迂回する。
-- ─────────────────────────────────────────────────────────────────────────────
revoke all on public.news_sources,           public.news_source_feeds,
              public.news_articles,          public.news_events,
              public.news_event_articles,    public.news_cluster_decisions,
              public.news_event_i18n,        public.saved_news_events
  from anon, authenticated;

grant select on public.news_sources, public.news_source_feeds, public.news_articles,
                public.news_events,  public.news_event_articles, public.news_event_i18n
  to anon, authenticated;

grant select on public.news_cluster_decisions to authenticated;

grant select, insert, update, delete on public.saved_news_events to authenticated;

-- ⚠⚠ service_role への表の grant を**明示する**。
--   baseline の `grant all on all tables in schema public to service_role` は
--   **その時点のスナップショット**であって、あとから作られた表には届かない。
--   ここを既定の privilege 頼みにすると、ingest が本番でだけ書けない——
--   しかも RLS を迂回する role なので、失敗の理由が「権限」だと分かりにくい。
grant select, insert, update, delete on
  public.news_sources,           public.news_source_feeds,
  public.news_articles,          public.news_events,
  public.news_event_articles,    public.news_cluster_decisions,
  public.news_event_i18n,        public.saved_news_events
  to service_role;

grant usage, select on sequence public.news_articles_id_seq,
                                public.news_events_id_seq,
                                public.news_source_feeds_id_seq,
                                public.news_cluster_decisions_id_seq,
                                public.saved_news_events_id_seq
  to service_role;
