-- ============================================================================
--  #R351 — 出来事パイプラインを実際に回すために、器へ足りなかった 2 つ
-- ----------------------------------------------------------------------------
--  #R334 の migration は 8 表を作り、本番へ適用され、pgTAP 123 件が通っている。
--  そこへ ingest（`supabase/functions/news-ingest/`）を載せるにあたり、実装して
--  初めて必要と分かったものだけをここで足す。**表は 1 つも作り直さない。**
--
--  1. `news_event_i18n.source_title_fp`
--     翻訳は Event の**代表見出し**に対して行う。代表見出しは記事が増えると変わる
--     （medoid で選び直す）ので、訳文が古くなったことを検出できなければならない。
--     ⚠ `news_events.updated_at` では判定できない——あれは記事が 1 本増えただけでも
--       動くので、**同じ見出しを何度も翻訳し直して課金される**。見出しそのものの
--       指紋を持てば、「見出しが変わったときだけ払う」が言える。
--
--  2. `news_ingest_runs`
--     docs/NEWS-EVENTS.md §13 の telemetry の置き場。1 回の取り込みにつき 1 行。
--     ⚠ **フィードごとの鮮度は `news_source_feeds` の 4 列（last_success_at /
--       last_item_count / last_error_at / last_error）が持っている**ので、ここには
--       書かない。同じ事実を 2 か所に置かない。ここが持つのは「その run 全体で
--       何が起きたか」——件数・却下の内訳・段ごとの所要・LLM の費用。
--     ⚠ 運用の記録であって公開データではない。`news_cluster_decisions` と同じく
--       **admin だけが読み、service_role だけが書く。**
--
--  ⚠ pgvector の ANN index (ivfflat / hnsw) はここでも作らない。
--    `news_articles.embedding` は 1 行も埋まっていない——**空の表に張った ivfflat は
--    リストを学習できず、あとで作り直すことになる**（docs/NEWS-EVENTS.md §5.2）。
--    embedding の段は Phase C。
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
--  1. 訳文が古くなったことを検出できるようにする
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.news_event_i18n
  add column if not exists source_title_fp text;

comment on column public.news_event_i18n.source_title_fp is
  '訳の元になった代表見出しの SHA-256。これが現在の代表見出しと違えば訳は古い。'
  '⚠ news_events.updated_at で判定すると、記事が増えるたびに同じ見出しを翻訳し直す。';

-- ─────────────────────────────────────────────────────────────────────────────
--  1b. 分類の根拠を置く場所
-- ----------------------------------------------------------------------------
--  #R334 は `category_confidence` と `classifier_version` を作ったが、**なぜその分類に
--  なったか**を置く列が無かった（`location_evidence` は地点側にある）。docs/NEWS-EVENTS.md
--  §11 は「自動化が間違った理由を隠さない」を運用者への要件にしているので、分類にも要る。
--  中身は `{by:'feed'|'publisher_tags'|'classifier'|'default', …}` ——どの段が決めたか、
--  何を根拠にしたか（媒体のタグ／当たった語／フィードの票）。
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.news_events
  add column if not exists category_evidence jsonb;

comment on column public.news_events.category_evidence is
  'どの段がカテゴリを決めたかと、その根拠（フィードの票 / 媒体のタグ / 当たった語）。'
  '#R351 news-ingest が書く。運用者が Merge/Split を判断するために読む。';

-- ─────────────────────────────────────────────────────────────────────────────
--  2. 取り込み 1 回ぶんの計測 (docs/NEWS-EVENTS.md §13)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.news_ingest_runs (
  id                  bigint      generated by default as identity primary key,
  started_at          timestamptz not null default now(),
  finished_at         timestamptz,
  stages              text[]      not null default '{}',
  ok                  boolean     not null default false,

  -- 収集
  feeds_total         integer     not null default 0,
  feeds_ok            integer     not null default 0,
  items_fetched       integer     not null default 0,
  articles_new        integer     not null default 0,
  articles_seen       integer     not null default 0,
  -- ⚠ 却下の内訳は「何を捨てたか」であって、捨てた事実そのものが計測対象である。
  --   見出しの門は近似なので、効きすぎたときに気づけるのはこの列だけ。
  rejects             jsonb       not null default '{}'::jsonb,

  -- Event への割り当て
  articles_assigned   integer     not null default 0,
  events_created      integer     not null default 0,
  events_updated      integer     not null default 0,
  evictions           integer     not null default 0,

  -- 翻訳
  translations        integer     not null default 0,
  llm_tokens_in       integer     not null default 0,
  llm_tokens_out      integer     not null default 0,
  estimated_cost_usd  numeric(10,6) not null default 0,

  -- 保持
  pruned_articles     integer     not null default 0,
  pruned_events       integer     not null default 0,
  pruned_decisions    integer     not null default 0,

  -- 所要（段ごとの ms と、1 本あたりの p50/p95）
  timings             jsonb       not null default '{}'::jsonb,
  notes               jsonb       not null default '{}'::jsonb,
  algorithm_version   smallint    not null default 1
);

create index if not exists idx_news_ingest_runs_started
  on public.news_ingest_runs (started_at desc);

comment on table public.news_ingest_runs is
  '#R351 news-ingest の 1 回ぶんの計測 (docs/NEWS-EVENTS.md §13)。'
  'フィード個々の鮮度は news_source_feeds が持つ——ここには書かない。';

-- ─────────────────────────────────────────────────────────────────────────────
--  3. RLS と grant
-- ----------------------------------------------------------------------------
--  ⚠ baseline の `grant all on all tables in schema public to service_role` は
--    **その時点のスナップショット**で、あとから作られた表には届かない（#R334 と同じ注意）。
--    だから明示する。
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.news_ingest_runs enable row level security;

-- 公開データではない。admin だけが読める（news_cluster_decisions と同じ形）。
drop policy if exists news_ingest_runs_admin on public.news_ingest_runs;
create policy news_ingest_runs_admin on public.news_ingest_runs
  for select to authenticated
  using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin));

revoke all on public.news_ingest_runs from anon, authenticated;
grant select on public.news_ingest_runs to authenticated;
grant select, insert, update, delete on public.news_ingest_runs to service_role;
grant usage, select on sequence public.news_ingest_runs_id_seq to service_role;
